(()=>{"use strict";
const $=id=>document.getElementById(id);
const E=Object.fromEntries(["apiBtn","apiDot","apiText","runBtn","playBtn","trace","sourcePane","codePane","soundPane","sourceState","codeState","soundState","prompt","drawBtn","clearBtn","makeBtn","sketchWrap","sketch","clearInk","gutter","code","timeline","spec","stones","keepBtn","mobileCode","mobileSound","sheetBack","keyInput","modelInput","routeInput","connectBtn","sheetDot","sheetStatus","forgetBtn","closeSheet","workspace"].map(id=>[id,$(id)]));
const ROOTS={C:0,"C#":1,Db:1,D:2,"D#":3,Eb:3,E:4,F:5,"F#":6,Gb:6,G:7,"G#":8,Ab:8,A:9,"A#":10,Bb:10,B:11};
const MODES={major:[0,2,4,5,7,9,11],minor:[0,2,3,5,7,8,10],dorian:[0,2,3,5,7,9,10],mixolydian:[0,2,4,5,7,9,10],phrygian:[0,1,3,5,7,8,10],pentatonic:[0,2,4,7,9]};
const GROOVES=["backbeat","shuffle","broken","halftime","motorik","clave","garage","triplet","afro_lilt","dub_space","free_pulse"];
const ROLES=["DRUMS","PERCUSSION","BASS","GUITAR","KEYS","VOCAL","BRASS","STRINGS","SYNTH","WORLD","TEXTURE","FX"];
const BEHAVIORS=["loop","one_shot","chop","punctuate"];
const STATIC="https://earsketch.gatech.edu/backend-static";
const state={key:sessionStorage.getItem("es.key")||"",model:sessionStorage.getItem("es.model")||"gpt-5.6-terra",route:sessionStorage.getItem("es.route")||"https://api.openai.com/v1",connected:false,pending:false,busy:false,strokes:[],drawing:null,stones:[],stoneIndex:-1,plan:null,ir:null,dirty:true,catalog:null,catalogPromise:null,catalogError:null,buffers:new Map(),usedSounds:new Set(),audio:null,master:null,nodes:[],raf:0,playing:false,widths:[34,32,34]};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const seeded=seed=>{let x=seed||123456789;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)%100000)/100000}};
const uid=()=>`stone_${Date.now().toString(36)}_${Math.floor(Math.random()*1e6).toString(36)}`;
const mobile=()=>matchMedia("(max-width:720px)").matches,current=()=>state.stones[state.stoneIndex]||null;
function setTrace(a,b="",c=""){E.trace.innerHTML=`<strong>${esc(a)}</strong>${b?`&nbsp; → &nbsp;${esc(b)}`:""}${c?`&nbsp; → &nbsp;${esc(c)}`:""}`}
function showSheet(){E.keyInput.value=state.key;E.modelInput.value=state.model;E.routeInput.value=state.route;E.sheetBack.classList.add("open")}
function hideSheet(){E.sheetBack.classList.remove("open")}
E.apiBtn.onclick=showSheet;E.closeSheet.onclick=hideSheet;E.sheetBack.onclick=e=>{if(e.target===E.sheetBack)hideSheet()};
E.forgetBtn.onclick=()=>{state.key="";state.connected=false;sessionStorage.removeItem("es.key");E.apiDot.className="dot";E.apiText.textContent="API";E.keyInput.value=""};
async function apiFetch(path,opt={}){const headers={...(opt.headers||{}),Authorization:`Bearer ${state.key}`};if(opt.body)headers["Content-Type"]="application/json";const r=await fetch(`${state.route.replace(/\/$/,"")}${path}`,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error?.message||`${r.status} ${r.statusText}`);return d}
async function connect(){state.key=E.keyInput.value.trim();state.model=E.modelInput.value.trim()||"gpt-5.6-terra";state.route=E.routeInput.value.trim()||"https://api.openai.com/v1";if(!state.key){E.sheetDot.className="dot bad";E.sheetStatus.textContent="key required";return}E.connectBtn.disabled=true;E.sheetStatus.textContent="checking…";E.sheetDot.className="dot";try{await apiFetch(`/models/${encodeURIComponent(state.model)}`);state.connected=true;sessionStorage.setItem("es.key",state.key);sessionStorage.setItem("es.model",state.model);sessionStorage.setItem("es.route",state.route);E.sheetDot.className="dot ok";E.sheetStatus.textContent="connected";E.apiDot.className="dot ok";E.apiText.textContent=state.model;setTimeout(hideSheet,100);if(state.pending){state.pending=false;setTimeout(make,130)}}catch(e){E.sheetDot.className="dot bad";E.sheetStatus.textContent=e.message}finally{E.connectBtn.disabled=false}}
E.connectBtn.onclick=connect;
(async()=>{if(!state.key)return;try{await apiFetch(`/models/${encodeURIComponent(state.model)}`);state.connected=true;E.apiDot.className="dot ok";E.apiText.textContent=state.model}catch(_){E.apiDot.className="dot bad"}})();
async function loadCatalog(){if(state.catalog)return state.catalog;if(state.catalogPromise)return state.catalogPromise;state.catalogPromise=(async()=>{const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),6500);try{const r=await fetch(`${STATIC}/audio-standard_4.json`,{signal:ctl.signal,cache:"force-cache"});if(!r.ok)throw Error(`catalog ${r.status}`);const d=await r.json();state.catalog=Array.isArray(d)?d.filter(x=>x&&x.name&&x.path):[];setTrace("READY",`${state.catalog.length} EarSketch sounds`,"describe or draw");return state.catalog}catch(e){state.catalogError=e;state.catalog=[];setTrace("READY","catalog unavailable","genre synth fallback");return state.catalog}finally{clearTimeout(timer)}})();return state.catalogPromise}
loadCatalog();
function fitSketch(){const r=E.sketch.getBoundingClientRect(),d=Math.max(1,devicePixelRatio||1);if(r.width<1||r.height<1)return;E.sketch.width=Math.round(r.width*d);E.sketch.height=Math.round(r.height*d);const c=E.sketch.getContext("2d");c.setTransform(d,0,0,d,0,0);redraw()}
function redraw(){const c=E.sketch.getContext("2d"),r=E.sketch.getBoundingClientRect();c.clearRect(0,0,r.width,r.height);c.fillStyle="#fff";c.fillRect(0,0,r.width,r.height);c.strokeStyle="#111";c.lineWidth=2;c.lineCap="round";c.lineJoin="round";for(const s of state.strokes){if(s.length<2)continue;c.beginPath();c.moveTo(s[0].x,s[0].y);for(const p of s.slice(1))c.lineTo(p.x,p.y);c.stroke()}}
function pt(e){const r=E.sketch.getBoundingClientRect();return{x:clamp(e.clientX-r.left,0,r.width),y:clamp(e.clientY-r.top,0,r.height)}}
E.sketch.onpointerdown=e=>{E.sketch.setPointerCapture(e.pointerId);state.drawing=[pt(e)];state.strokes.push(state.drawing);redraw();reportDrawing()};
E.sketch.onpointermove=e=>{if(!state.drawing)return;const p=pt(e),q=state.drawing.at(-1);if(Math.hypot(p.x-q.x,p.y-q.y)>2){state.drawing.push(p);redraw();reportDrawing()}};
E.sketch.onpointerup=E.sketch.onpointercancel=()=>{state.drawing=null;reportDrawing()};
E.clearInk.onclick=()=>{state.strokes=[];redraw();reportDrawing()};
E.drawBtn.onclick=()=>{E.sketchWrap.hidden=!E.sketchWrap.hidden;E.drawBtn.textContent=E.sketchWrap.hidden?"DRAW":"HIDE";if(!E.sketchWrap.hidden)setTimeout(fitSketch,0)};
E.clearBtn.onclick=()=>{E.prompt.value="";state.strokes=[];redraw();setTrace("START","describe or draw","MAKE");E.prompt.focus()};
function drawingDNA(){const r=E.sketch.getBoundingClientRect(),W=Math.max(1,r.width),H=Math.max(1,r.height),pts=state.strokes.flat();if(!pts.length)return{active:false,strokes:0,rhythm:Array(16).fill(0),contour:[0,0,0,0,0,0,0,0],energy:[.65,.65,.65,.65],blank:[false,false,false,false],partBias:0};const bins=Array.from({length:16},()=>[]),eBins=Array.from({length:4},()=>[]);for(const p of pts){bins[clamp(Math.floor(p.x/W*16),0,15)].push(p);eBins[clamp(Math.floor(p.x/W*4),0,3)].push(p)}const mx=Math.max(1,...bins.map(b=>b.length)),em=Math.max(1,...eBins.map(b=>b.length));const rhythm=bins.map(b=>b.length/mx>.14?1:0);const contour=[];for(let i=0;i<8;i++){const pair=[...bins[i*2],...bins[i*2+1]];const y=pair.length?pair.reduce((a,p)=>a+p.y,0)/pair.length:H/2;contour.push(clamp(Math.round((1-y/H)*10)-5,-5,5))}const energy=eBins.map(b=>clamp(.2+.8*b.length/em,.2,1));const blank=eBins.map(b=>b.length===0);return{active:true,strokes:state.strokes.length,rhythm,contour,energy,blank,partBias:clamp(state.strokes.length-2,-2,4)}}
function reportDrawing(){const d=drawingDNA();if(!d.active){setTrace("SOURCE","drawing empty","type or draw");return}setTrace(`${d.strokes} strokes`,`${d.rhythm.reduce((a,b)=>a+b,0)}/16 rhythm`,`contour ${d.contour.join(" ")}`)}
function sketchImage(){if(!state.strokes.length)return null;const r=E.sketch.getBoundingClientRect(),c=document.createElement("canvas");c.width=Math.max(320,Math.round(r.width*1.4));c.height=Math.max(240,Math.round(r.height*1.4));const x=c.getContext("2d"),sx=c.width/r.width,sy=c.height/r.height;x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);x.strokeStyle="#111";x.lineWidth=3;x.lineCap="round";x.lineJoin="round";for(const s of state.strokes){if(s.length<2)continue;x.beginPath();x.moveTo(s[0].x*sx,s[0].y*sy);for(const p of s.slice(1))x.lineTo(p.x*sx,p.y*sy);x.stroke()}return c.toDataURL("image/png")}
function schema(){const pal={type:"object",additionalProperties:false,required:["role","query","behavior","level"],properties:{role:{type:"string",enum:ROLES},query:{type:"string",maxLength:48},behavior:{type:"string",enum:BEHAVIORS},level:{type:"number",minimum:.15,maximum:.95}}};const stone={type:"object",additionalProperties:false,required:["name","genre","lineage","hook","tempo","key","mode","swing","bars","groove","palette","progression","bassMotif","leadMotif","density","drawingUse","surprise"],properties:{name:{type:"string",maxLength:28},genre:{type:"string",maxLength:42},lineage:{type:"string",maxLength:80},hook:{type:"string",maxLength:90},tempo:{type:"integer",minimum:50,maximum:170},key:{type:"string",enum:Object.keys(ROOTS)},mode:{type:"string",enum:Object.keys(MODES)},swing:{type:"number",minimum:0,maximum:.35},bars:{type:"integer",enum:[8,12,16]},groove:{type:"string",enum:GROOVES},palette:{type:"array",minItems:4,maxItems:8,items:pal},progression:{type:"array",minItems:2,maxItems:8,items:{type:"integer",minimum:1,maximum:7}},bassMotif:{type:"array",minItems:3,maxItems:8,items:{type:"integer",minimum:-7,maximum:12}},leadMotif:{type:"array",minItems:4,maxItems:12,items:{type:"integer",minimum:-7,maximum:12}},density:{type:"number",minimum:.2,maximum:.95},drawingUse:{type:"string",enum:["rhythm","contour","energy","orchestration","all"]},surprise:{type:"string",maxLength:90}}};return{type:"object",additionalProperties:false,required:["stones"],properties:{stones:{type:"array",minItems:4,maxItems:4,items:stone}}}}
function outputText(d){if(typeof d.output_text==="string")return d.output_text;return(d.output||[]).flatMap(i=>i.content||[]).filter(c=>c.type==="output_text").map(c=>c.text||"").join("")}
function debt(){try{return JSON.parse(localStorage.getItem("es.genreDebt")||"[]").slice(-8)}catch(_){return[]}}
function remember(s){const a=debt();a.push({genre:s.genre,groove:s.groove,roles:s.palette.map(p=>p.role),queries:s.palette.map(p=>p.query),key:s.key,mode:s.mode});localStorage.setItem("es.genreDebt",JSON.stringify(a.slice(-8)))}
function normalize(s){return{id:uid(),...s,tempo:clamp(Math.round(s.tempo),50,170),bars:[8,12,16].includes(s.bars)?s.bars:12,palette:s.palette.slice(0,8),kept:false,resolved:[],drawing:drawingDNA()}}
async function make(){if(state.busy)return;const text=E.prompt.value.trim(),draw=drawingDNA();if(!text&&!draw.active){E.prompt.focus();setTrace("START","describe or draw","MAKE");return}if(!state.connected){state.pending=true;showSheet();return}state.busy=true;E.makeBtn.disabled=true;E.makeBtn.textContent="WORKING";E.sourceState.textContent="thinking";setTrace("CAST","4 different musical worlds","real palette + drawing");const content=[{type:"input_text",text:`SOURCE:\n${text||"(drawing only)"}\n\nDRAWING DNA (this WILL be compiled into the music locally, so compose with it rather than ignoring it):\n${JSON.stringify(draw)}\n\nRECENTLY USED — depart from these:\n${JSON.stringify(debt())}\n\nCreate FOUR musically incompatible but buildable stones.\nGenre must change instrumentation, production logic, groove, register, and source material — not only labels.\nFor each palette entry, write a concrete EarSketch catalogue search such as "southern soul organ", "live gospel drums", "gnawa percussion", "dub bass", "gamelan metal", "female vocal", "garage synth", "mbira", "psychedelic guitar".\nUse 4–8 roles. Do not give all stones the same band.\nAt least one stone must foreground an unusual recorded-material lineage (voice, world instrument, field texture, brass, strings, etc.).\nIf drawing is active, state how it participates, but local code will force its rhythm/contour/energy into the result regardless.\nGive coherent hooks and phrase-level development, not random events.\nReturn schema only.`}];const img=sketchImage();if(img)content.push({type:"input_image",image_url:img,detail:"low"});try{const d=await apiFetch("/responses",{method:"POST",body:JSON.stringify({model:state.model,instructions:"You are a record digger, arranger, and instrument builder. Different genres must use different musical materials and production grammars.",input:[{role:"user",content}],text:{format:{type:"json_schema",name:"es_material_stones",strict:true,schema:schema()}}})});const parsed=JSON.parse(outputText(d));state.stones=parsed.stones.map(normalize);state.stoneIndex=0;renderStones();await loadStone(current());remember(current());expandAll();run();setTrace(current().genre,current().palette.map(p=>p.role).join(" + "),current().hook)}catch(e){E.sourceState.textContent="retry";setTrace("FAULT","source preserved",e.message||"retry");if(/401|api key|model/i.test(e.message||"")){state.connected=false;E.apiDot.className="dot bad"}}finally{state.busy=false;E.makeBtn.disabled=false;E.makeBtn.textContent="MAKE"}}
E.makeBtn.onclick=make;
function words(s){return String(s||"").toLowerCase().split(/[^a-z0-9]+/).filter(Boolean)}
function soundHay(s){return`${s.name||""} ${s.genreGroup||""} ${s.genre||""} ${s.instrument||""} ${s.folder||""} ${s.artist||""}`.toLowerCase()}
function resolveSound(role,query,genre){const cat=state.catalog||[];if(!cat.length)return null;const qs=words(`${query} ${role} ${genre}`),used=state.usedSounds;let best=null,bestScore=-1e9;for(const s of cat){const h=soundHay(s);let score=0;for(const w of qs)if(h.includes(w))score+=w.length>5?4:2;if(String(s.instrument||"").toUpperCase().includes(role))score+=5;if(used.has(s.name))score-=8;if(s.tempo)score+=1;score+=(hash(s.name+query)%100)/500;if(score>bestScore){best=s;bestScore=score}}if(best&&bestScore>0)return best;return cat[hash(query+genre)%cat.length]||null}
async function resolvePalette(stone){await loadCatalog();stone.resolved=stone.palette.map(p=>({...p,sound:resolveSound(p.role,p.query,stone.genre)}));for(const x of stone.resolved)if(x.sound)state.usedSounds.add(x.sound.name);return stone.resolved}
function stoneCode(s){const d=s.drawing||drawingDNA(),lines=[`# ES+ ${s.name}`,`# ${s.genre} | ${s.lineage}`,`# ${s.hook}`,`genre(${JSON.stringify(s.genre)})`,`tempo(${s.tempo})`,`key(${JSON.stringify(s.key)}, ${JSON.stringify(s.mode)})`,`groove(${JSON.stringify(s.groove)}, ${Number(s.swing).toFixed(2)})`,`bars(${s.bars})`,`density(${Number(s.density).toFixed(2)})`];for(const p of s.palette)lines.push(`palette(${JSON.stringify(p.role)}, ${JSON.stringify(p.query)}, ${JSON.stringify(p.behavior)}, ${Number(p.level).toFixed(2)})`);lines.push(`progression(${JSON.stringify(s.progression)})`,`bass(${JSON.stringify(s.bassMotif)})`,`lead(${JSON.stringify(s.leadMotif)})`);if(d.active){lines.push(`drawRhythm(${JSON.stringify(d.rhythm.join(""))})`,`drawContour(${JSON.stringify(d.contour)})`,`drawEnergy(${JSON.stringify(d.energy.map(x=>+x.toFixed(2)))})`,`drawBlank(${JSON.stringify(d.blank)})`)}lines.push(`surprise(${JSON.stringify(s.surprise)})`);return lines.join("\n")}
async function loadStone(s){if(!s)return;E.code.value=stoneCode(s);state.plan=null;state.ir=null;state.dirty=true;E.codeState.textContent="ready";E.soundState.textContent="not run";E.runBtn.disabled=false;E.playBtn.disabled=true;E.mobileCode.disabled=false;E.keepBtn.disabled=false;E.timeline.innerHTML='<div class="empty">RUN to arrange it.</div>';updateGutter();resolvePalette(s).then(()=>{if(current()===s)setTrace(s.genre,s.resolved.filter(x=>x.sound).map(x=>x.sound.name).slice(0,3).join(" · ")||"genre synth fallback",s.hook)}).catch(()=>{})}
function renderStones(){E.stones.innerHTML="";state.stones.forEach((s,i)=>{const b=document.createElement("button");b.className="stoneDot"+(i===state.stoneIndex?" on":"")+(s.kept?" kept":"");b.textContent=`${i+1} ${s.name}`;b.title=`${s.genre} — ${s.hook}`;b.onclick=async()=>{state.stoneIndex=i;renderStones();await loadStone(s);remember(s);run();if(mobile())showMobile("sound")};E.stones.appendChild(b)});E.keepBtn.classList.toggle("on",!!current()?.kept)}
E.keepBtn.onclick=()=>{const s=current();if(!s)return;s.kept=!s.kept;renderStones()};
function splitArgs(t){const o=[];let c="",q=null,d=0;for(let i=0;i<t.length;i++){const x=t[i];if((x==='"'||x==="'")&&t[i-1]!=="\\")q=q===x?null:(q||x);if(!q&&(x==="["||x==="("||x==="{"))d++;if(!q&&(x==="]"||x===")"||x==="}"))d--;if(!q&&d===0&&x===","){o.push(c.trim());c="";continue}c+=x}if(c.trim())o.push(c.trim());return o}
function parseVal(s){s=s.trim();if(/^".*"$/.test(s)||/^'.*'$/.test(s))return s.slice(1,-1);if(/^-?\d+(\.\d+)?$/.test(s))return Number(s);if(s==="true")return true;if(s==="false")return false;try{return JSON.parse(s)}catch(_){return s}}
function parseCode(src){const p={genre:"hybrid",tempo:100,key:"C",mode:"minor",swing:0,bars:8,groove:"backbeat",density:.65,palette:[],progression:[1,4,6,5],bass:[0,0,3,5],lead:[0,2,4,7,5],surprise:"",drawRhythm:null,drawContour:null,drawEnergy:null,drawBlank:null};for(const line0 of src.split("\n")){const line=line0.replace(/#.*$/,"").trim();if(!line)continue;const m=line.match(/^([A-Za-z_]\w*)\((.*)\)$/);if(!m)throw Error(`cannot read: ${line.slice(0,28)}`);const a=splitArgs(m[2]).map(parseVal);switch(m[1]){case"genre":p.genre=String(a[0]);break;case"tempo":p.tempo=clamp(+a[0],40,220);break;case"key":p.key=String(a[0]);p.mode=String(a[1]);break;case"groove":p.groove=String(a[0]);p.swing=clamp(+a[1]||0,0,.45);break;case"bars":p.bars=clamp(Math.round(+a[0]),2,32);break;case"density":p.density=clamp(+a[0],.05,1);break;case"palette":p.palette.push({role:String(a[0]),query:String(a[1]),behavior:String(a[2]),level:clamp(+a[3],.05,1)});break;case"progression":p.progression=Array.isArray(a[0])?a[0]:p.progression;break;case"bass":p.bass=Array.isArray(a[0])?a[0]:p.bass;break;case"lead":p.lead=Array.isArray(a[0])?a[0]:p.lead;break;case"drawRhythm":p.drawRhythm=String(a[0]).split("").map(x=>x==="1"?1:0);break;case"drawContour":p.drawContour=Array.isArray(a[0])?a[0]:null;break;case"drawEnergy":p.drawEnergy=Array.isArray(a[0])?a[0]:null;break;case"drawBlank":p.drawBlank=Array.isArray(a[0])?a[0]:null;break;case"surprise":p.surprise=String(a[0]||"");break;default:throw Error(`unknown ${m[1]}()`);}}return p}
function family(genre,palette=[]){const s=(genre+" "+palette.map(p=>p.query).join(" ")).toLowerCase();if(/dub|reggae/.test(s))return"dub";if(/gospel|soul|funk|r&b|motown/.test(s))return"soul";if(/techno|house|garage|electro|club/.test(s))return"electronic";if(/ambient|drone|electroacoustic|field/.test(s))return"ambient";if(/gamelan|bali|java|gong/.test(s))return"gamelan";if(/afro|mbira|kora|gnawa|morocc|oud|world|latin|samba/.test(s))return"world";if(/rock|psych|guitar|punk|surf/.test(s))return"rock";if(/jazz|bebop|swing/.test(s))return"jazz";if(/hip.?hop|trap|boom.?bap/.test(s))return"hiphop";return"hybrid"}
function degreeMidi(p,degree,oct=4){const mode=MODES[p.mode]||MODES.minor,root=ROOTS[p.key]??0,d=Math.max(1,Math.round(degree||1))-1;return 12*(oct+1)+root+mode[d%mode.length]+12*Math.floor(d/mode.length)}
function drawingGate(p,step){return!p.drawRhythm||!p.drawRhythm.length?1:(p.drawRhythm[step%p.drawRhythm.length]?1:.28)}
function sectionEnergy(p,bar){if(p.drawEnergy?.length)return clamp(+p.drawEnergy[Math.floor(bar/p.bars*p.drawEnergy.length)]||.5,.15,1);return .55+.3*Math.sin((bar+1)/p.bars*Math.PI)}
function blankSection(p,bar){if(!p.drawBlank?.length)return false;return !!p.drawBlank[Math.floor(bar/p.bars*p.drawBlank.length)]}
function drumPattern(g){const K={backbeat:[[0,8],[4,12],[2,6,10,14]],shuffle:[[0,7,10],[4,12],[2,5,8,11,14]],broken:[[0,6,11],[4,13],[2,7,10,15]],halftime:[[0,10],[8],[2,6,10,14]],motorik:[[0,4,8,12],[4,12],[2,6,10,14]],clave:[[0,6,10],[4,12],[0,3,6,10,12]],garage:[[0,7,10],[4,12],[2,6,10,14]],triplet:[[0,8],[5,13],[0,3,6,9,12,15]],afro_lilt:[[0,6,10,14],[4,12],[1,4,7,10,13]],dub_space:[[0,10],[12],[3,7,11,15]],free_pulse:[[0,9],[5,13],[1,6,12]]};return K[g]||K.backbeat}
function arrange(p){const events=[],fam=family(p.genre,p.palette),seed=hash(JSON.stringify(p)),r=seeded(seed),dr=drumPattern(p.groove),barDur=4;const add=(type,track,start,dur,note=0,vel=.7,meta={})=>events.push({id:`e${events.length+1}`,type,track,start,dur,note,vel,...meta});for(let bar=0;bar<p.bars;bar++){const base=bar*barDur,en=sectionEnergy(p,bar),blank=blankSection(p,bar);if(blank&&bar%2===1)continue;dr[0].forEach(st=>{if(r()<p.density*en*drawingGate(p,st))add("kick",1,base+st/4,.12,36,.8*en)});dr[1].forEach(st=>{if(r()<Math.min(1,.7+p.density*.3))add("snare",2,base+st/4,.1,38,.68*en)});dr[2].forEach(st=>{if(r()<p.density*en*drawingGate(p,st))add("hat",3,base+st/4,.05,42,.3+.3*en)});const deg=p.progression[bar%p.progression.length]||1;add("chord",5,base,.9,degreeMidi(p,deg,4),.36*en,{degree:deg,family:fam});const bm=p.bass.length?p.bass:[0];for(let i=0;i<4;i++){const st=i*4;if(r()<(.55+p.density*.35)*drawingGate(p,st)){const off=bm[(bar*2+i)%bm.length]||0;add("bass",4,base+i,.55,degreeMidi(p,deg,2)+off,.55*en,{family:fam})}}const lm=p.lead.length?p.lead:[0,2,4,5],cont=p.drawContour?.length?p.drawContour:null;for(let i=0;i<4;i++){const st=i*4;if(r()<p.density*.52*en*drawingGate(p,st)){const off=lm[(bar*3+i)%lm.length]||0,co=cont?cont[(bar+i)%cont.length]:0;add("lead",6,base+i+.25,.35,degreeMidi(p,1,5)+off+co,.38*en,{family:fam})}}}p.palette.forEach((x,idx)=>{const every=x.behavior==="loop"?4:x.behavior==="punctuate"?3:x.behavior==="chop"?2:Math.max(4,p.bars);for(let bar=idx%2;bar<p.bars;bar+=every)add("sample",7+idx,bar*4,x.behavior==="one_shot"?.8:3.8,0,x.level,{paletteIndex:idx,role:x.role,query:x.query,behavior:x.behavior})});if(p.drawRhythm){for(let st=0;st<16;st++)if(p.drawRhythm[st])add("draw",20,st/4,.04,72+(p.drawContour?.[st%8]||0),.22)}events.sort((a,b)=>a.start-b.start||a.track-b.track);return{...p,family:fam,events,length:p.bars*4}}
function run(){stop();try{state.plan=parseCode(E.code.value);state.ir=arrange(state.plan);state.dirty=false;renderTimeline();drawSpec();E.codeState.textContent="matches sound";E.soundState.textContent=`${state.ir.events.length} events · ${state.ir.family}`;E.playBtn.disabled=!state.ir.events.length;E.mobileSound.disabled=false;if(mobile())showMobile("sound")}catch(e){E.codeState.textContent="fix";setTrace("FAULT","code preserved",e.message)}}
E.runBtn.onclick=run;
function renderTimeline(){const ir=state.ir,bars=ir.bars,width=Math.max(620,bars*75);E.timeline.style.minWidth=`${width}px`;E.timeline.innerHTML="";E.timeline.style.setProperty("--measures",bars);const ruler=document.createElement("div");ruler.className="ruler";for(let b=0;b<=bars;b++){const s=document.createElement("span");s.className="mnum";s.textContent=b+1;s.style.left=`${b/bars*100}%`;ruler.appendChild(s)}E.timeline.appendChild(ruler);const ph=document.createElement("div");ph.className="playhead";E.timeline.appendChild(ph);const tracks=[...new Set(ir.events.map(e=>e.track))].sort((a,b)=>a-b);for(const tr of tracks){const row=document.createElement("div");row.className="track";const lab=document.createElement("div");lab.className="tlabel";lab.textContent=tr;const lane=document.createElement("div");lane.className="lane";for(const e of ir.events.filter(x=>x.track===tr)){const c=document.createElement("button");c.className="clip";c.dataset.id=e.id;c.style.left=`${e.start/ir.length*100}%`;c.style.width=`${Math.max(.45,e.dur/ir.length*100)}%`;c.innerHTML=`<b>${esc(e.type==="sample"?(e.role||"sample"):e.type)}</b><span>${esc(e.query||ir.family)}</span>`;lane.appendChild(c)}row.append(lab,lane);E.timeline.appendChild(row)}}
function drawSpec(){const r=E.spec.getBoundingClientRect(),d=Math.max(1,devicePixelRatio||1);if(r.width<1||r.height<1)return;E.spec.width=Math.round(r.width*d);E.spec.height=Math.round(r.height*d);const c=E.spec.getContext("2d");c.setTransform(d,0,0,d,0,0);c.fillStyle="#fff";c.fillRect(0,0,r.width,r.height);if(!state.ir)return;c.strokeStyle="#ebe7dc";for(let x=0;x<r.width;x+=32){c.beginPath();c.moveTo(x,0);c.lineTo(x,r.height);c.stroke()}const maxT=state.ir.length;for(const e of state.ir.events){const x=e.start/maxT*r.width,w=Math.max(2,e.dur/maxT*r.width),y=e.type==="bass"?r.height*.78:e.type==="kick"?r.height*.88:e.type==="lead"?r.height*.28:e.type==="chord"?r.height*.48:e.type==="sample"?r.height*.38:r.height*.65;c.fillStyle=e.type==="sample"?"rgba(20,80,65,.38)":"rgba(17,17,15,.26)";c.fillRect(x,y,w,4+(hash(e.type)%9))}}
function ctx(){if(!state.audio){state.audio=new(window.AudioContext||window.webkitAudioContext)();const comp=state.audio.createDynamicsCompressor();comp.threshold.value=-18;comp.ratio.value=4;comp.connect(state.audio.destination);state.master=comp}if(state.audio.state==="suspended")state.audio.resume();return state.audio}
async function bufferFor(sound){if(!sound?.path)return null;if(state.buffers.has(sound.name))return state.buffers.get(sound.name);const promise=(async()=>{const c=ctx(),ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),5500);try{const r=await fetch(`${STATIC}/${sound.path}`,{signal:ctl.signal});if(!r.ok)throw Error("audio");const a=await r.arrayBuffer();return await c.decodeAudioData(a.slice(0))}catch(_){return null}finally{clearTimeout(timer)}})();state.buffers.set(sound.name,promise);return promise}
function oscVoice(when,note,dur,vel,fam,kind){const c=ctx(),g=c.createGain(),f=c.createBiquadFilter(),o=c.createOscillator();let wave="triangle",cut=2200,attack=.008,release=.18;if(fam==="electronic"){wave=kind==="bass"?"sawtooth":"square";cut=kind==="bass"?650:3600}else if(fam==="ambient"){wave="sine";cut=1600;attack=.18;release=1.2}else if(fam==="gamelan"){wave="sine";cut=7000;release=.5}else if(fam==="world"){wave="triangle";cut=3800;release=.28}else if(fam==="rock"){wave="sawtooth";cut=2400;release=.22}else if(fam==="hiphop"){wave=kind==="bass"?"sine":"square";cut=kind==="bass"?500:1800}else if(fam==="dub"){wave=kind==="bass"?"sine":"triangle";cut=kind==="bass"?420:1600;release=.5}else if(fam==="soul"){wave=kind==="chord"?"triangle":"sine";cut=2600;release=.35}else if(fam==="jazz"){wave="triangle";cut=2100;release=.3}o.type=wave;o.frequency.value=440*Math.pow(2,(note-69)/12);f.type="lowpass";f.frequency.value=cut;g.gain.setValueAtTime(.0001,when);g.gain.linearRampToValueAtTime(Math.max(.001,vel*.14),when+attack);g.gain.exponentialRampToValueAtTime(.0001,when+Math.max(attack+.03,dur+release));o.connect(f);f.connect(g);g.connect(state.master);o.start(when);o.stop(when+dur+release+.05);state.nodes.push(o);if(fam==="gamelan"){const o2=c.createOscillator();o2.type="sine";o2.frequency.value=o.frequency.value*2.73;o2.connect(g);o2.start(when);o2.stop(when+dur+.25);state.nodes.push(o2)}}
function noiseHit(when,dur,vel,type){const c=ctx(),b=c.createBuffer(1,Math.max(1,Math.floor(c.sampleRate*dur)),c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;const s=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();s.buffer=b;f.type=type==="hat"?"highpass":"bandpass";f.frequency.value=type==="hat"?6500:1700;g.gain.setValueAtTime(vel*.18,when);g.gain.exponentialRampToValueAtTime(.0001,when+dur);s.connect(f);f.connect(g);g.connect(state.master);s.start(when);s.stop(when+dur+.02);state.nodes.push(s)}
function kick(when,vel){const c=ctx(),o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(120,when);o.frequency.exponentialRampToValueAtTime(42,when+.14);g.gain.setValueAtTime(vel*.28,when);g.gain.exponentialRampToValueAtTime(.0001,when+.22);o.connect(g);g.connect(state.master);o.start(when);o.stop(when+.24);state.nodes.push(o)}
async function scheduleSample(e,when,spb){const s=current(),rp=s?.resolved?.[e.paletteIndex],sound=rp?.sound;if(!sound)return false;const b=await bufferFor(sound);if(!b)return false;const c=ctx(),src=c.createBufferSource(),g=c.createGain();src.buffer=b;const sourceTempo=Number(sound.tempo)>20?Number(sound.tempo):null;src.playbackRate.value=sourceTempo?state.ir.tempo/sourceTempo:1;g.gain.value=clamp(e.vel*.65,.04,.55);src.connect(g);g.connect(state.master);src.start(Math.max(c.currentTime+.01,when),0,Math.min(b.duration,Math.max(.15,e.dur*spb*src.playbackRate.value)));state.nodes.push(src);return true}
async function play(){if(!state.ir)return;if(state.playing){stop();return}stop();const c=ctx(),ir=state.ir,spb=60/ir.tempo,start=c.currentTime+.12;state.playing=true;E.playBtn.textContent="STOP";const s=current(),preloads=[];if(s?.resolved)for(const rp of s.resolved.slice(0,7))if(rp.sound)preloads.push(bufferFor(rp.sound));Promise.allSettled(preloads).catch(()=>{});for(const e of ir.events){const when=start+e.start*spb;if(e.type==="kick")kick(when,e.vel);else if(e.type==="snare")noiseHit(when,.12,e.vel,"snare");else if(e.type==="hat")noiseHit(when,.05,e.vel,"hat");else if(e.type==="bass")oscVoice(when,e.note,e.dur*spb,e.vel,ir.family,"bass");else if(e.type==="lead"||e.type==="draw")oscVoice(when,e.note,e.dur*spb,e.vel,ir.family,"lead");else if(e.type==="chord"){for(const n of[e.note,e.note+4,e.note+7])oscVoice(when,n,e.dur*spb,e.vel*.7,ir.family,"chord")}else if(e.type==="sample")scheduleSample(e,when,spb)}const total=ir.length*spb+.5;const tick=()=>{if(!state.playing)return;const sec=c.currentTime-start;if(sec>=total){stop();return}const beat=sec/spb,ph=document.querySelector(".playhead");if(ph){ph.style.display="block";ph.style.left=`calc(48px + (100% - 48px) * ${beat/ir.length})`}const ids=new Set(ir.events.filter(e=>beat>=e.start&&beat<e.start+e.dur).map(e=>e.id));document.querySelectorAll(".clip").forEach(x=>x.classList.toggle("playing",ids.has(x.dataset.id)));state.raf=requestAnimationFrame(tick)};state.raf=requestAnimationFrame(tick)}
function stop(){cancelAnimationFrame(state.raf);for(const n of state.nodes){try{n.stop()}catch(_){}}state.nodes=[];state.playing=false;E.playBtn.textContent="PLAY";document.querySelectorAll(".clip.playing").forEach(x=>x.classList.remove("playing"));const p=document.querySelector(".playhead");if(p)p.style.display="none"}
E.playBtn.onclick=play;
function updateGutter(){const n=E.code.value.split("\n").length;E.gutter.innerHTML="";for(let i=1;i<=n;i++){const d=document.createElement("div");d.className="ln";d.textContent=i;E.gutter.appendChild(d)}E.gutter.scrollTop=E.code.scrollTop}
E.code.oninput=()=>{state.dirty=true;E.codeState.textContent="changed";E.playBtn.disabled=true;updateGutter()};E.code.onscroll=()=>E.gutter.scrollTop=E.code.scrollTop;E.code.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter"){e.preventDefault();run()}if(e.key==="Tab"){e.preventDefault();E.code.setRangeText("    ",E.code.selectionStart,E.code.selectionEnd,"end")}};
function setWidths(){if(mobile())return;const p=[E.sourcePane,E.codePane,E.soundPane],vis=p.map(x=>!x.classList.contains("min")),sum=state.widths.reduce((a,b,i)=>a+(vis[i]?b:0),0)||1;p.forEach((x,i)=>x.style.flex=vis[i]?`0 0 ${state.widths[i]/sum*100}%`:"0 0 34px");document.querySelectorAll(".grip").forEach((g,i)=>g.hidden=!(vis[i]&&vis[i+1]))}
function expandAll(){if(mobile()){showMobile("sound");return}for(const p of[E.sourcePane,E.codePane,E.soundPane]){p.classList.remove("min");p.querySelector(".minBtn").textContent="−"}state.widths=[31,32,37];setWidths()}
document.querySelectorAll("[data-min]").forEach(b=>b.onclick=()=>{const p={source:E.sourcePane,code:E.codePane,sound:E.soundPane}[b.dataset.min];p.classList.toggle("min");b.textContent=p.classList.contains("min")?"+":"−";setWidths()});
function showMobile(name){if(!mobile())return;document.querySelectorAll(".pane").forEach(p=>p.classList.toggle("mobileOn",p.dataset.pane===name));document.querySelectorAll("[data-mobile]").forEach(b=>b.classList.toggle("on",b.dataset.mobile===name));if(name==="source")setTimeout(fitSketch,0);if(name==="sound")setTimeout(drawSpec,0)}
document.querySelectorAll("[data-mobile]").forEach(b=>b.onclick=()=>{if(!b.disabled)showMobile(b.dataset.mobile)});
window.addEventListener("resize",()=>{if(mobile())showMobile(document.querySelector("[data-mobile].on")?.dataset.mobile||"source");else setWidths();fitSketch();drawSpec()});
E.sketchWrap.hidden=true;E.prompt.value="";if(mobile())showMobile("source");else setWidths();updateGutter();setTrace("READY","loading EarSketch catalogue","describe or draw");
})();