
'use strict';
const C=globalThis.PondCore,$=id=>document.getElementById(id);
let initial=C.starter(),drafts={},key='',model='gpt-5.6-terra';
function validDrafts(raw,bars){const out={};if(!raw||typeof raw!=='object')return out;for(const [k,v] of Object.entries(raw)){const parts=k.split(':').map(Number);if(parts.length===2&&parts.every(Number.isInteger)&&parts[0]>=0&&parts[1]>=parts[0]&&parts[1]<bars&&typeof v==='string'&&v.length<=17000)out[k]=v;}return out;}
try{const saved=JSON.parse(localStorage.getItem('pond.project')||'null');if(saved){initial=C.validate(saved.composition);drafts=validDrafts(saved.drafts,initial.bars);$('direction').value=typeof saved.direction==='string'?saved.direction:''}}catch{}
try{key=sessionStorage.getItem('pond.key')||'';model=sessionStorage.getItem('pond.model')||model}catch{}
const session=C.session(initial),colors=['#ba883e','#5a87b6','#4c9a7d','#9176b6'];
let requesting=false,requestId=0,controller=null,variationNumber=0;
let audio=null,audioMaster=null,audioNodes=[],audioTimer=0,audioToken=0,playing=false,auditionMode='';
function status(t){$('status').textContent=t}
function state(){return session.snapshot()}
function draftKey(){const s=state();return s.selection.start+':'+s.selection.end}
function persist(){try{localStorage.setItem('pond.project',JSON.stringify({composition:state().composition,direction:$('direction').value,drafts}))}catch{status('Autosave unavailable. Use Project → Save project.')}}
function cancelRequest(){requestId++;if(controller)controller.abort();controller=null;requesting=false}
function stopAudio(){audioToken++;clearInterval(audioTimer);audioNodes.forEach(n=>{try{n.stop()}catch{}});audioNodes=[];if(audioMaster){audioMaster.disconnect();audioMaster=null}playing=false;auditionMode='';$('play').textContent='▶ Play';$('original').classList.remove('active');$('candidate').classList.remove('active');document.querySelectorAll('.sounding').forEach(e=>e.classList.remove('sounding'))}
function beforeChange(){cancelRequest();stopAudio()}
function change(label,fn){try{beforeChange();session.mutate(label,fn);drafts={};persist();render();status(label)}catch(e){status(e.message);render()}}
function select(start,end){try{C.assert(Number.isInteger(start)&&Number.isInteger(end),'Select whole bar numbers.');beforeChange();session.select(Math.min(start,end),Math.max(start,end));render();status('Selected bars '+(Math.min(start,end)+1)+'–'+(Math.max(start,end)+1)+'.')}catch(e){status(e.message);render()}}
function install(raw,scope='both',base=state()){session.propose(raw,scope,base.revision,base.selection);render();status('Candidate ready. Audition both versions before using it.')}
function summary(p,c){let music=0,lyrics=0;p.tracks.forEach(t=>{const old=c.tracks.find(x=>x.id===t.id);t.bars.forEach((bar,i)=>{if(!C.equal(bar,old.bars[p.start+i]))music++})});p.lyrics.forEach((line,i)=>{if(line!==c.lyrics[p.start+i].text)lyrics++});return p.summary+'\n\n'+music+' track-bars changed · '+lyrics+' lyric lines changed\nMaterial outside bars '+(p.start+1)+'–'+(p.end+1)+' is preserved.'}
function render(){const s=state(),c=s.composition,r=s.selection;$('tempo').value=c.tempo;$('length').value=c.bars;$('start').max=$('end').max=c.bars;$('start').value=r.start+1;$('end').value=r.end+1;$('rangeTitle').textContent='Bars '+(r.start+1)+'–'+(r.end+1);$('lyrics').value=drafts[draftKey()]??c.lyrics.slice(r.start,r.end+1).map(x=>x.text).join('\n');const locks=c.lyrics.slice(r.start,r.end+1).filter(x=>x.locked).length;$('lockLyrics').textContent=locks===r.end-r.start+1?'Unlock lyrics':'Lock lyrics';$('lyricHint').textContent=locks+' locked lines. Unapplied writing stays with this selection until the composition changes.';$('undo').disabled=!s.history.length;renderCandidate();renderTimeline()}
function renderCandidate(){const s=state(),ready=!!s.candidate;$('phase').textContent=requesting?'Requesting':ready?'Candidate ready':'Editing';$('summary').textContent=ready?summary(s.candidate.proposal,s.composition):'Select a passage and propose a change. The composition stays intact until you use a candidate.';['candidate','commit','discard'].forEach(id=>$(id).disabled=!ready);$('generate').disabled=requesting;$('variation').disabled=requesting;$('cancel').hidden=!requesting}
function cell(bar,s){const d=document.createElement('div');d.className='cell'+(bar>=s.selection.start&&bar<=s.selection.end?' selected':'')+(s.candidate&&bar>=s.selection.start&&bar<=s.selection.end?' hasCandidate':'');d.dataset.timebar=bar;return d}
function renderTimeline(){const s=state(),c=s.candidate&&auditionMode==='candidate'?C.apply(s.composition,s.candidate.proposal):s.composition,root=$('timeline');root.innerHTML='';root.style.setProperty('--bars',c.bars);root.style.minWidth=(122+80*c.bars)+'px';const ruler=document.createElement('div');ruler.className='row ruler';const label=document.createElement('div');label.className='trackLabel';label.textContent='BAR / 4 BEATS';ruler.append(label);for(let b=0;b<c.bars;b++){const button=document.createElement('button');button.className='cell'+(b>=s.selection.start&&b<=s.selection.end?' selected':'');button.textContent=b+1;button.setAttribute('aria-label','Select bar '+(b+1));button.onclick=e=>select(e.shiftKey?s.selection.start:b,b);ruler.append(button)}root.append(ruler);
c.tracks.forEach((t,ti)=>{const row=document.createElement('div');row.className='row';const label=document.createElement('div');label.className='trackLabel';const lock=document.createElement('button');lock.textContent=t.locked?'●':'○';lock.setAttribute('aria-label',(t.locked?'Unlock ':'Lock ')+t.name);lock.setAttribute('aria-pressed',String(t.locked));lock.onclick=()=>change((t.locked?'Unlocked ':'Locked ')+t.name,c=>c.tracks[ti].locked=!c.tracks[ti].locked);const name=document.createElement('span');name.textContent=t.name;label.append(lock,name);row.append(label);t.bars.forEach((notes,b)=>{const d=cell(b,s);notes.forEach(n=>{const mark=document.createElement('span');mark.className='note';mark.style.left=n.beat/4*100+'%';mark.style.width=Math.max(1,n.duration/4*100)+'%';mark.style.top=(9+(96-n.pitch)/72*33)+'px';mark.style.background=colors[ti%colors.length];d.append(mark)});row.append(d)});root.append(row)});
const row=document.createElement('div');row.className='row lyricRow';const name=document.createElement('div');name.className='trackLabel';name.textContent='LYRICS';row.append(name);c.lyrics.forEach((line,b)=>{const d=cell(b,s);if(line.locked){const l=document.createElement('div');l.className='lockMark';l.textContent='LOCKED';d.append(l)}const t=document.createElement('div');t.className='lyricText';t.textContent=line.text||'·';d.append(t);d.ondblclick=()=>{select(b,b);$('lyrics').focus()};row.append(d)});root.append(row)}
$('start').onchange=()=>select(Number($('start').value)-1,state().selection.end);
$('end').onchange=()=>select(state().selection.start,Number($('end').value)-1);
$('tempo').onchange=()=>change('Changed tempo',c=>c.tempo=Number($('tempo').value));
$('length').onchange=()=>{const n=Number($('length').value);if(!Number.isInteger(n)||n<4||n>32){status('Use 4–32 bars.');render();return}change('Resized composition to '+n+' bars',c=>{c.bars=n;c.tracks.forEach(t=>{while(t.bars.length<n)t.bars.push([]);t.bars.length=n});while(c.lyrics.length<n)c.lyrics.push({text:'',locked:false});c.lyrics.length=n})};
$('lyrics').oninput=()=>{drafts[draftKey()]=$('lyrics').value;persist()};
$('direction').oninput=persist;
$('applyLyrics').onclick=()=>{const s=state(),r=s.selection,count=r.end-r.start+1,lines=$('lyrics').value.split('\n');if(lines.length>count){status('Use one line per selected bar.');return}while(lines.length<count)lines.push('');if(lines.some((line,i)=>line.length>500||(s.composition.lyrics[r.start+i].locked&&line!==s.composition.lyrics[r.start+i].text))){status('A locked lyric changed or a line exceeds 500 characters.');return}change('Applied lyric edits',c=>lines.forEach((text,i)=>c.lyrics[r.start+i].text=text))};
$('lockLyrics').onclick=()=>{const s=state(),r=s.selection,locked=s.composition.lyrics.slice(r.start,r.end+1).every(l=>l.locked);change(locked?'Unlocked selected lyrics':'Locked selected lyrics',c=>{for(let i=r.start;i<=r.end;i++)c.lyrics[i].locked=!locked})};
$('variation').onclick=()=>{beforeChange();session.discard();const s=state(),p=C.passage(s.composition,s.selection);variationNumber++;p.summary='Local music variation: alternate melody steps and vary accents. Lyrics and locks preserved. No model used.';p.tracks.forEach((t,ti)=>{const original=s.composition.tracks[ti];if(original.locked)return;t.bars.forEach(bar=>bar.forEach((n,i)=>{n.velocity=Math.max(.1,Math.min(.9,n.velocity+((i+variationNumber)%2?.1:-.1)));if(original.kind!=='drums')n.pitch=Math.max(24,Math.min(96,n.pitch+(variationNumber%2?2:-2)))}))});try{install(p,'music',s)}catch(e){status(e.message)}};
$('commit').onclick=()=>{try{beforeChange();session.commit();drafts={};persist();render();status('Candidate committed. Undo restores the previous composition.')}catch(e){status(e.message)}};
$('discard').onclick=()=>{beforeChange();session.discard();render();status('Candidate discarded. Original preserved.')};
$('undo').onclick=()=>{try{beforeChange();session.undo();drafts={};persist();render();status('Previous composition restored.')}catch(e){status(e.message)}};
$('score').onclick=()=>{const s=state();$('scoreText').value=JSON.stringify(s.candidate?.proposal||C.passage(s.composition,s.selection),null,2);$('scoreError').textContent='';$('scoreDialog').showModal()};
$('previewScore').onclick=()=>{try{beforeChange();install(JSON.parse($('scoreText').value));$('scoreDialog').close()}catch(e){$('scoreError').textContent=e.message}};
async function play(c,start,end,mode){stopAudio();const token=audioToken;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();await audio.resume();if(token!==audioToken)return;audioMaster=audio.createGain();audioMaster.gain.value=.18;audioMaster.connect(audio.destination);const beat=60/c.tempo,origin=audio.currentTime+.05,finish=origin+(end-start+1)*4*beat;playing=true;auditionMode=mode;$('play').textContent='■ Stop';if(mode==='original'||mode==='candidate')$(mode).classList.add('active');renderTimeline();for(const t of c.tracks){for(let b=start;b<=end;b++){for(const n of t.bars[b]){if(n.velocity===0)continue;const at=origin+((b-start)*4+n.beat)*beat,duration=Math.max(.06,n.duration*beat),osc=audio.createOscillator(),gain=audio.createGain();osc.type=t.kind==='bass'||t.kind==='drums'?'triangle':'sine';osc.frequency.setValueAtTime(t.kind==='drums'?(n.pitch===36?130:260):440*2**((n.pitch-69)/12),at);if(t.kind==='drums')osc.frequency.exponentialRampToValueAtTime(45,at+.12);gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(n.velocity*.5,at+.012);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);osc.connect(gain).connect(audioMaster);osc.start(at);osc.stop(at+duration+.02);audioNodes.push(osc)}}}audioTimer=setInterval(()=>{const bar=start+Math.floor((audio.currentTime-origin)/(beat*4));document.querySelectorAll('[data-timebar]').forEach(e=>e.classList.toggle('sounding',Number(e.dataset.timebar)===bar));if(audio.currentTime>finish+.1){stopAudio();renderTimeline()}},40)}catch(e){stopAudio();status('Audio could not start: '+e.message)}}
$('play').onclick=()=>{if(playing){stopAudio();renderTimeline()}else{const s=state();play(s.composition,0,s.composition.bars-1,'all')}};
$('original').onclick=()=>{const s=state();play(s.composition,s.selection.start,s.selection.end,'original')};
$('candidate').onclick=()=>{const s=state();if(s.candidate)play(C.apply(s.composition,s.candidate.proposal),s.selection.start,s.selection.end,'candidate')};
$('api').onclick=()=>{$('apiKey').value=key;$('model').value=model;$('apiDialog').showModal()};
$('saveApi').onclick=()=>{key=$('apiKey').value.trim();model=$('model').value.trim();if(!key||!model){status('Enter an API key and model.');return}try{sessionStorage.setItem('pond.key',key);sessionStorage.setItem('pond.model',model)}catch{}$('apiDialog').close();status('Connection set. Propose a passage change.')};
$('forgetApi').onclick=()=>{key='';try{sessionStorage.removeItem('pond.key')}catch{}$('apiKey').value='';status('Key forgotten.')};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('cancel').onclick=()=>{cancelRequest();renderCandidate();status('Request cancelled. Original preserved.')};
$('generate').onclick=async()=>{if(!key){$('api').click();return}const direction=$('direction').value.trim();if(!direction){status('Describe the change first.');$('direction').focus();return}beforeChange();session.discard();const base=state(),scope=$('scope').value,id=++requestId,ctl=new AbortController();controller=ctl;requesting=true;renderCandidate();renderTimeline();status('Requesting a passage candidate…');const timer=setTimeout(()=>ctl.abort(),90000);
const context={tempo:base.composition.tempo,timeSignature:'4/4',scope,tracks:base.composition.tracks.map(t=>({id:t.id,instrument:t.kind,locked:t.locked})),lyricLocks:base.composition.lyrics.slice(base.selection.start,base.selection.end+1).map(l=>l.locked),passage:C.passage(base.composition,base.selection)};
try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',signal:ctl.signal,headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify({model,instructions:'Edit the supplied musical passage. Return ONLY JSON with exactly its passage shape: start,end,tracks:[{id,bars:[[notes]]}],lyrics:[one string per bar],summary. Each note has beat,pitch,duration,velocity. Beats 0–4; duration >=0.05; beat+duration<=4; integer MIDI pitch 24–96; velocity 0–1. Keep all track IDs and bar counts. Locked tracks and locked lyric lines must be copied exactly. Scope lyrics means all music unchanged. Scope music means all lyrics unchanged. Write original lyrics when requested. No global changes. Summarize concrete edits.',input:JSON.stringify({direction,context}),text:{format:{type:'json_object'}}})});const result=await r.json();if(!r.ok)throw Error(result.error?.message||'Generation failed.');if(id!==requestId||ctl.signal.aborted)return;const text=result.output_text||(result.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join('');install(JSON.parse(text),scope,base)}catch(e){if(id===requestId)status(e.name==='AbortError'?'Request timed out. Original preserved.':'Candidate rejected: '+e.message)}finally{clearTimeout(timer);if(id===requestId){controller=null;requesting=false;renderCandidate()}}};
$('project').onclick=()=>{const s=state();$('history').innerHTML='';if(!s.history.length)$('history').textContent='No committed changes yet.';s.history.slice().reverse().forEach(h=>{const d=document.createElement('div');d.textContent=new Date(h.at).toLocaleTimeString()+' · '+h.label;$('history').append(d)});$('projectDialog').showModal()};
$('saveProject').onclick=()=>{const payload={format:'pond-project',composition:state().composition,direction:$('direction').value,drafts};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='pond-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Project saved. Credentials excluded.')};
$('openProject').onclick=()=>$('fileInput').click();
$('fileInput').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;C.assert(f.size<3000000,'Project is too large.');const p=JSON.parse(await f.text());C.assert(p.format==='pond-project','Not a Pond project.');const next=C.validate(p.composition);beforeChange();session.replace(next);drafts=validDrafts(p.drafts,next.bars);$('direction').value=typeof p.direction==='string'?p.direction.slice(0,10000):'';persist();render();$('projectDialog').close();status('Project opened. Undo restores the previous score.')}catch(e){status('Project not opened: '+e.message)}finally{$('fileInput').value=''}};
globalThis.Pond={session,core:C};render();
