const COMPOSER_PROMPT=`You are TRACE Composer inside a theory-building music environment.
Treat prompting, programming, and producing as different operational descriptions of one evolving musical object.
Never produce a whole finished song when a bounded change will do.
Use the selected section/event as scope.
Prefer compact loop constructions over repeated event objects.
Output only the requested schema; never executable JavaScript.
Musical time is zero-based beats; four beats is one bar.
Use existing track ids. Keep pitch mainly 36–96.
Each operation needs a short plain reason.
Preserve ambiguity: interpretation must say how you chose to carry the user's words into controllable musical dimensions.
If the user asks why, debug, teach, or otherwise, propose the smallest audible experiment that helps them compare alternatives.`;

const OBSERVER_PROMPT=`You are TRACE Observer, a second-pass teacher.
You DO NOT receive or reveal hidden chain-of-thought.
You inspect only public artifacts: user words, selected scope, composer plan, generated TRACE source, resulting composition, and a bounded trail digest.
Infer relationships probabilistically.
Use plain plumber English: what seems connected, why, visible evidence, another plausible reading, and downstream consequence.
Also look for repeated choices across the trail: the set of alternatives the learner tends to choose from.
Do not diagnose personality or learning style. Do not say a choice is best.
Help the learner distinguish PROMPT (words), PROGRAM (operation), MUSIC (structure), and PERCEPTION (what they report hearing).
A useful teacher exposes alternatives and asks operative questions rather than depositing definitions.`;

const COMPOSER_SCHEMA={type:"object",additionalProperties:false,required:["summary","interpretation","dimensions","alternatives","tempo","clear_ranges","note_loops","drum_loops","effects"],properties:{summary:{type:"string"},interpretation:{type:"array",maxItems:5,items:{type:"string"}},dimensions:{type:"array",maxItems:5,items:{type:"string",enum:["rhythm","pitch","time","timbre","space","form"]}},alternatives:{type:"array",maxItems:3,items:{type:"string"}},tempo:{type:["integer","null"]},clear_ranges:{type:"array",maxItems:5,items:{type:"object",additionalProperties:false,required:["track","start","end","reason"],properties:{track:{type:"integer"},start:{type:"number"},end:{type:"number"},reason:{type:"string"}}}},note_loops:{type:"array",maxItems:8,items:{type:"object",additionalProperties:false,required:["track","pitches","start","step","duration","repeats","velocity","wave","reason"],properties:{track:{type:"integer"},pitches:{type:"array",maxItems:16,items:{type:"integer"}},start:{type:"number"},step:{type:"number"},duration:{type:"number"},repeats:{type:"integer"},velocity:{type:"integer"},wave:{type:"string",enum:["square","triangle","sawtooth","sine","pulse"]},reason:{type:"string"}}}},drum_loops:{type:"array",maxItems:8,items:{type:"object",additionalProperties:false,required:["track","drum","start","step","repeats","velocity","reason"],properties:{track:{type:"integer"},drum:{type:"string",enum:["kick","snare","hat","noise","knock","mallet"]},start:{type:"number"},step:{type:"number"},repeats:{type:"integer"},velocity:{type:"integer"},reason:{type:"string"}}}},effects:{type:"array",maxItems:8,items:{type:"object",additionalProperties:false,required:["track","parameter","value","reason"],properties:{track:{type:"integer"},parameter:{type:"string",enum:["cutoff","resonance","delay","reverb","distortion","attack","release","sustain","tremolo","tremoloRate"]},value:{type:"number"},reason:{type:"string"}}}}}};

const OBSERVER_SCHEMA={type:"object",additionalProperties:false,required:["summary","relationships","habits","lessons","questions"],properties:{summary:{type:"string"},relationships:{type:"array",maxItems:12,items:{type:"object",additionalProperties:false,required:["prompt_fragment","target_kind","target_index","confidence","plain_explanation","evidence","alternate_reading","downstream"],properties:{prompt_fragment:{type:"string"},target_kind:{type:"string",enum:["tempo","clear_range","note_loop","drum_loop","effect"]},target_index:{type:"integer"},confidence:{type:"number"},plain_explanation:{type:"string"},evidence:{type:"string"},alternate_reading:{type:"string"},downstream:{type:"string"}}}},habits:{type:"array",maxItems:4,items:{type:"object",additionalProperties:false,required:["confidence","pattern","evidence","other_move"],properties:{confidence:{type:"number"},pattern:{type:"string"},evidence:{type:"string"},other_move:{type:"string"}}}},lessons:{type:"object",additionalProperties:false,required:["prompting","programming","music"],properties:{prompting:{type:"string"},programming:{type:"string"},music:{type:"string"}}},questions:{type:"array",maxItems:4,items:{type:"string"}}}};

function context(){const c=state.composition,s=scopeObject(),sel=c.events.find(e=>e.id===state.selectedEventId)||null;return{project:state.project,scope:s,selected:sel?{id:sel.id,type:sel.type,track:sel.track,start:sel.start,pitch:sel.pitch||null,drum:sel.drum||null,reason:sel.provenance.reason}:null,sketch:sketchSummary(),bpm:c.bpm,bars:c.bars,tracks:c.tracks,effects:c.fx,events:c.events.filter(e=>e.start>=s.start&&e.start<s.end).slice(0,100).map(e=>e.type==="note"?{id:e.id,k:"n",t:e.track,p:e.pitch,s:e.start,d:e.duration,v:e.velocity,w:e.wave}:{id:e.id,k:"d",t:e.track,dr:e.drum,s:e.start,v:e.velocity})}}
function validatePlan(p){if(!p||typeof p!=="object")throw Error("Model returned no plan.");for(const k of ["clear_ranges","note_loops","drum_loops","effects","interpretation","dimensions","alternatives"])if(!Array.isArray(p[k]))throw Error(`Model plan missing ${k}.`);if(p.note_loops.length>LIMITS.noteLoops||p.drum_loops.length>LIMITS.drumLoops||p.effects.length>LIMITS.effects)throw Error("Model plan exceeded bounds.");for(const x of p.note_loops)if(x.repeats<1||x.repeats>64||!Array.isArray(x.pitches)||x.pitches.length<1||x.pitches.length>16)throw Error("Model note loop invalid.");for(const x of p.drum_loops)if(x.repeats<1||x.repeats>64)throw Error("Model drum loop invalid.");return p}
function planOperations(plan){const ops=[];if(plan.tempo!==null)ops.push({kind:"tempo",index:0,reason:"tempo",data:{bpm:plan.tempo}});plan.clear_ranges.forEach((x,i)=>ops.push({kind:"clear_range",index:i,reason:x.reason,data:x}));plan.note_loops.forEach((x,i)=>ops.push({kind:"note_loop",index:i,reason:x.reason,data:x}));plan.drum_loops.forEach((x,i)=>ops.push({kind:"drum_loop",index:i,reason:x.reason,data:x}));plan.effects.forEach((x,i)=>ops.push({kind:"effect",index:i,reason:x.reason,data:x}));return ops}
function sourcePatch(plan){const lines=[];if(plan.tempo!==null)lines.push(`tempo(${plan.tempo})`);for(const x of plan.clear_ranges)lines.push(`# clear track ${x.track} beats ${trim(x.start)}–${trim(x.end)} · ${x.reason}`);for(const x of plan.note_loops)lines.push(`loopNote(${x.track}, ${JSON.stringify(x.pitches)}, ${trim(x.start)}, ${trim(x.step)}, ${trim(x.duration)}, ${x.repeats}, ${x.velocity}, ${JSON.stringify(x.wave)})`);for(const x of plan.drum_loops)lines.push(`loopDrum(${x.track}, ${JSON.stringify(x.drum)}, ${trim(x.start)}, ${trim(x.step)}, ${x.repeats}, ${x.velocity})`);for(const x of plan.effects)lines.push(`fx(${x.track}, ${JSON.stringify(x.parameter)}, ${trim(x.value)})`);return lines.join("\n")}
function applyPlan(base,plan,promptId,preview=true){const c=clone(base);let oi=0;const prov=(reason,opIndex)=>({origin:"ai",reason,promptId,opIndex});if(plan.tempo!==null)c.bpm=clamp(Math.round(plan.tempo),40,240);for(const x of plan.clear_ranges){c.events=c.events.filter(e=>!(e.track===x.track&&e.start>=x.start&&e.start<x.end));oi++}for(const x of plan.note_loops){for(let i=0;i<x.repeats;i++){c.events.push(note(x.track,x.pitches[i%x.pitches.length],x.start+i*x.step,x.duration,x.velocity,x.wave,prov(x.reason,oi)));if(c.events.length>LIMITS.events)throw Error("Plan would exceed event limit.")}oi++}for(const x of plan.drum_loops){for(let i=0;i<x.repeats;i++){c.events.push(drum(x.track,x.drum,x.start+i*x.step,.12,x.velocity,prov(x.reason,oi)));if(c.events.length>LIMITS.events)throw Error("Plan would exceed event limit.")}oi++}for(const x of plan.effects){c.fx[String(x.track)]||=fx0();c.fx[String(x.track)][x.parameter]=x.value;oi++}if(preview)for(const e of c.events)if(e.provenance.promptId===promptId)e.preview=true;return ensure(c)}
function publicRead(text){const l=text.toLowerCase(),scores={rhythm:0,pitch:0,time:0,timbre:0,space:0,form:0},add=(d,words)=>{for(const w of words)if(l.includes(w))scores[d]++};add("rhythm",["rhythm","beat","panic","drive","dense","repeat","stutter","nervous"]);add("pitch",["melody","rise","fall","high","low","bright","hook","pitch"]);add("time",["faster","slower","tempo","rush","drag","accelerat"]);add("timbre",["dark","rough","grit","soft","harsh","filter","distort"]);add("space",["echo","reverb","space","far","close","ghost","memory"]);add("form",["section","break","intro","outro","drop","structure","repeat"]);const carriers=Object.entries(scores).sort((a,b)=>b[1]-a[1]).map(([name,score])=>({name,score}));if(!carriers[0].score)carriers[0].score=1;return carriers}
function demoPlan(text){const lower=text.toLowerCase(),s=scopeObject(),p={summary:"Small bounded detour",interpretation:[],dimensions:[],alternatives:["keep the same notes and change only timbre","keep the tempo and change only event density"],tempo:null,clear_ranges:[],note_loops:[],drum_loops:[],effects:[]};if(/faster|panic|urgent|chase|accelerat|frantic/.test(lower)){p.tempo=clamp(state.composition.bpm+18,60,220);p.interpretation.push("I carried part of the request into clock speed.");p.dimensions.push("time")}if(/slow|calm|weightless|dream/.test(lower)){p.tempo=clamp(state.composition.bpm-14,50,200);p.interpretation.push("I opened more clock time.");p.dimensions.push("time")}if(/dark|grit|danger|rough/.test(lower)){p.effects.push({track:1,parameter:"cutoff",value:2600,reason:"darken the lead spectrum"},{track:1,parameter:"distortion",value:.28,reason:"roughen the edge"});p.interpretation.push("I carried the quality into timbre.");p.dimensions.push("timbre")}if(/echo|space|reverb|ghost|memory/.test(lower)){p.effects.push({track:1,parameter:"delay",value:.22,reason:"leave a repeating trace"},{track:1,parameter:"reverb",value:.32,reason:"lengthen the decay"});p.interpretation.push("I carried the request into acoustic space.");p.dimensions.push("space")}if(/drum|beat|drive|panic|rhythm|nervous/.test(lower)){p.drum_loops.push({track:3,drum:"kick",start:s.start,step:1,repeats:Math.min(16,Math.floor(s.end-s.start)),velocity:116,reason:"anchor the section with a pulse"},{track:3,drum:"hat",start:s.start+.5,step:.5,repeats:Math.min(32,Math.floor((s.end-s.start)*2)),velocity:66,reason:"make the subdivision audible"});p.interpretation.push("I carried the request into attack density.");p.dimensions.push("rhythm")}const sk=sketchSummary();if(sk&&sk.contour.length>=4){const seq=sk.contour.slice(0,12).map(y=>clamp(Math.round(48+y*36),42,92));p.note_loops.push({track:1,pitches:seq,start:s.start,step:.5,duration:.36,repeats:Math.min(24,Math.floor((s.end-s.start)*2)),velocity:104,wave:"square",reason:`carry the drawn ${sk.direction} contour into pitch`});p.interpretation.push(`I read the sketch as a ${sk.direction} contour with ${sk.turns} turns.`);p.dimensions.push("pitch")}else if(/melody|lead|rise|bright|hook|victory|strange/.test(lower)||p.note_loops.length===0&&p.drum_loops.length===0&&p.effects.length===0&&p.tempo===null){const seq=/strange/.test(lower)?[72,73,79,76,82,75]:[72,76,79,76];p.note_loops.push({track:1,pitches:seq,start:s.start,step:.5,duration:.36,repeats:Math.min(24,Math.floor((s.end-s.start)*2)),velocity:104,wave:"square",reason:"give the selected span a repeatable contour"});p.interpretation.push("I carried the words into a pitch contour.");p.dimensions.push("pitch")}p.dimensions=[...new Set(p.dimensions)];p.summary=`DEMO · ${p.dimensions.join(" + ")||"pitch"}`;return validatePlan(p)}
function localObserver(text,plan){const rel=[],ops=planOperations(plan),lower=text.toLowerCase();ops.slice(0,8).forEach(op=>{const keys={tempo:["faster","slower","panic","calm"],note_loop:["melody","lead","rise","hook","strange"],drum_loop:["drum","beat","rhythm","drive","panic"],effect:["dark","echo","space","reverb","grit"]}[op.kind]||[],hit=keys.find(k=>lower.includes(k)),frag=hit||text.split(/\s+/).filter(Boolean).slice(0,4).join(" ")||"your request";rel.push({prompt_fragment:frag,target_kind:op.kind,target_index:op.index,confidence:hit?.8:.58,plain_explanation:`I connect “${frag}” to this ${op.kind.replace("_"," ")} because they point at the same controllable musical dimension.`,evidence:op.reason||"The generated operation is the visible evidence.",alternate_reading:"The words could have been carried by another musical dimension; this is a plausible reading, not the true one.",downstream:op.kind==="tempo"?"Events keep their measure positions but land closer together in seconds.":op.kind==="drum_loop"?"More attacks appear in WORLD.":op.kind==="note_loop"?"A repeated pitch contour appears in WORLD.":"Sound color changes without moving the notes."})});const habits=habitDigest().map(h=>({confidence:h.confidence,pattern:h.title,evidence:h.explain,other_move:h.other}));return{summary:"A public observer read of prompt → program → consequence.",relationships:rel,habits,lessons:{prompting:"Words leave some control unspecified. That ambiguity can be either room for surprise or a source of mismatch.",programming:"A loop is not merely shorter syntax; it asserts that several events are instances of one reusable idea.",music:"Tempo, event density, pitch and timbre can carry similar perceptual words in different ways."},questions:["Which change did you expect before you heard it?","Could the same intention survive if tempo stayed fixed?","Is this repetition one musical idea or several?"]}}
async function requestStructured(kind,prompt,schema,payload,maxTokens){const controller=new AbortController(),to=setTimeout(()=>controller.abort(),LIMITS.timeoutMs);try{const body={model:state.ai.model,input:[{role:"developer",content:[{type:"input_text",text:prompt}]},{role:"user",content:[{type:"input_text",text:JSON.stringify(payload)}]}],text:{format:{type:"json_schema",name:kind,strict:true,schema}},max_output_tokens:maxTokens},headers={"content-type":"application/json"};let url=state.ai.endpoint;if(state.ai.mode==="direct"){url="https://api.openai.com/v1/responses";if(!apiKeyMemory)throw Error("Add a session key in MENU → SYSTEM → AI SETUP.");headers.authorization=`Bearer ${apiKeyMemory}`}const r=await fetch(url,{method:"POST",headers,body:JSON.stringify(body),signal:controller.signal}),data=await r.json().catch(()=>null);if(!r.ok)throw Error(data?.error?.message||data?.error||`AI ${r.status}`);if(kind==="trace_composer"&&data?.summary&&Array.isArray(data.note_loops))return data;if(kind==="trace_observer"&&data?.summary&&Array.isArray(data.relationships))return data;if(data?.status==="incomplete")throw Error(`MODEL INCOMPLETE · ${data?.incomplete_details?.reason||"unknown"}`);const refusal=data?.output?.flatMap(x=>x.content||[]).find(x=>x.type==="refusal");if(refusal)throw Error(`MODEL REFUSED · ${refusal.refusal||"request"}`);let text=data?.output_text||"";if(!text&&Array.isArray(data?.output)){const part=data.output.flatMap(x=>x.content||[]).find(x=>x.type==="output_text"&&typeof x.text==="string");text=part?.text||""}if(!text)throw Error("MODEL RETURNED NO STRUCTURED OUTPUT");try{return JSON.parse(text)}catch(e){throw Error(`MODEL JSON INVALID · complete response but parser failed near ${String(e.message).slice(0,90)}`)}}catch(e){if(e?.name==="AbortError")throw Error("MODEL TIMEOUT");throw e}finally{clearTimeout(to)}}
async function compose(text){if(state.ai.mode==="demo")return demoPlan(text);return validatePlan(await requestStructured("trace_composer",COMPOSER_PROMPT,COMPOSER_SCHEMA,{request:text,context:context()},2800))}
async function observe(text,plan,patch){if(!state.teacher)return null;if(state.ai.mode==="demo")return localObserver(text,plan);try{return await requestStructured("trace_observer",OBSERVER_PROMPT,OBSERVER_SCHEMA,{request:text,context:context(),plan,generated_source:patch,trail:trailDigest()},3000)}catch(e){log("observer_error",{message:e.message});return localObserver(text,plan)}}
