function ctx(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();return audioCtx}
function noiseBuf(c,n=.2){const b=c.createBuffer(1,Math.max(1,Math.floor(c.sampleRate*n)),c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;return b}
function distortion(c,a){const n=256,curve=new Float32Array(n),k=a*80;for(let i=0;i<n;i++){const x=i*2/n-1;curve[i]=(1+k)*x/(1+k*Math.abs(x))}const w=c.createWaveShaper();w.curve=curve;w.oversample="2x";return w}
let verbBuf=null;function verb(c){if(verbBuf&&verbBuf.sampleRate===c.sampleRate)return verbBuf;const len=Math.floor(c.sampleRate*1.3),b=c.createBuffer(2,len,c.sampleRate);for(let ch=0;ch<2;ch++){const d=b.getChannelData(ch);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,2.2)}verbBuf=b;return b}
function chain(c,f,dest){const input=c.createGain(),filter=c.createBiquadFilter(),dist=distortion(c,clamp(+f.distortion||0,0,1)),dry=c.createGain(),del=c.createDelay(1),dg=c.createGain(),conv=c.createConvolver(),rg=c.createGain();filter.type="lowpass";filter.frequency.value=clamp(+f.cutoff||12000,80,20000);filter.Q.value=clamp(+f.resonance||0,0,24);del.delayTime.value=clamp(+f.delay||0,0,1)*.6;dg.gain.value=clamp(+f.delay||0,0,.8);conv.buffer=verb(c);rg.gain.value=clamp(+f.reverb||0,0,.8);input.connect(filter);filter.connect(dist);dist.connect(dry);dry.connect(dest);dist.connect(del);del.connect(dg);dg.connect(dest);dist.connect(conv);conv.connect(rg);rg.connect(dest);return input}
function schedNote(c,e,when,s,input,f){const o=c.createOscillator(),g=c.createGain(),dur=Math.max(.03,e.duration*s),a=clamp(+f.attack||.01,.002,.5),r=clamp(+f.release||.06,.01,1),v=e.velocity/127;o.type=e.wave==="pulse"?"square":e.wave;o.frequency.value=440*Math.pow(2,(e.pitch-69)/12);g.gain.setValueAtTime(0,when);g.gain.linearRampToValueAtTime(v*.22,when+a);g.gain.setValueAtTime(v*.22*Math.max(.15,+f.sustain||.75),Math.max(when+a,when+dur-r));g.gain.linearRampToValueAtTime(0,when+dur);o.connect(g);g.connect(input);o.start(when);o.stop(when+dur+.02);activeAudio.push(o)}
function schedDrum(c,e,when,input){const v=e.velocity/127;if(e.drum==="kick"||e.drum==="knock"){const o=c.createOscillator(),g=c.createGain();o.type="sine";o.frequency.setValueAtTime(e.drum==="kick"?150:230,when);o.frequency.exponentialRampToValueAtTime(e.drum==="kick"?42:90,when+.12);g.gain.setValueAtTime(v*.5,when);g.gain.exponentialRampToValueAtTime(.001,when+.16);o.connect(g);g.connect(input);o.start(when);o.stop(when+.18);activeAudio.push(o)}else{const s=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();s.buffer=noiseBuf(c,.18);f.type=e.drum==="hat"?"highpass":"bandpass";f.frequency.value=e.drum==="hat"?6500:1800;g.gain.setValueAtTime(v*(e.drum==="hat"?.12:.26),when);g.gain.exponentialRampToValueAtTime(.001,when+(e.drum==="hat"?.07:.18));s.connect(f);f.connect(g);g.connect(input);s.start(when);s.stop(when+.2);activeAudio.push(s)}}
async function play(){stop();const c=current(),a=ctx();if(a.state==="suspended")await a.resume();const master=a.createGain();master.gain.value=.74;analyser=a.createAnalyser();analyser.fftSize=1024;master.connect(analyser);analyser.connect(a.destination);const chains=new Map();for(const t of c.tracks)chains.set(t.id,chain(a,c.fx[String(t.id)]||fx0(),master));const s=spb(c),base=a.currentTime+.06;for(const e of c.events){const input=chains.get(e.track);if(!input)continue;e.type==="note"?schedNote(a,e,base+e.start*s,s,input,c.fx[String(e.track)]||fx0()):schedDrum(a,e,base+e.start*s,input)}playStart=performance.now()/1000+.06;playDuration=beats(c)*s;setStatus("HEARING",true);tickPlay();drawTrace();log("play",{run:state.currentRunId})}
function stop(){for(const n of activeAudio){try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}}activeAudio=[];if(raf)cancelAnimationFrame(raf);raf=0;document.getElementById("playhead")?.style.setProperty("display","none");if(!state.busy)setStatus("READY",false)}
function tickPlay(){const e=performance.now()/1000-playStart;if(e<0){raf=requestAnimationFrame(tickPlay);return}if(e>=playDuration){stop();return}const c=current(),beat=e/spb(c),pct=clamp(beat/beats(c),0,1),ph=document.getElementById("playhead");if(ph){ph.style.display="block";ph.style.left=`calc(62px + (100% - 62px) * ${pct})`}raf=requestAnimationFrame(tickPlay)}
function playPulse(){const a=ctx(),base=a.currentTime+.04;for(let i=0;i<4;i++){const e=drum(3,"kick",i,.12,116,{reason:"onboarding pulse"});schedDrum(a,e,base+i*.45,a.destination)}}
function drawTrace(){cancelAnimationFrame(traceAnim);const canvas=document.getElementById("scopeTrace");if(!canvas)return;const g=canvas.getContext("2d"),data=new Uint8Array(1024);function frame(){g.clearRect(0,0,canvas.width,canvas.height);g.fillStyle="#fff";g.fillRect(0,0,canvas.width,canvas.height);g.strokeStyle="#000";g.lineWidth=1.3;g.beginPath();if(analyser&&activeAudio.length){analyser.getByteTimeDomainData(data);for(let i=0;i<data.length;i++){const x=i/(data.length-1)*canvas.width,y=data[i]/255*canvas.height;i?g.lineTo(x,y):g.moveTo(x,y)}}else{const sel=state.composition.events.find(e=>e.id===state.selectedEventId),f=sel?state.composition.fx[String(sel.track)]||fx0():fx0(),decay=.15+(+f.delay||0)*1.5+(+f.reverb||0)*2;for(let i=0;i<220;i++){const x=i/219*canvas.width,t=i/219*5,y=canvas.height/2+Math.sin(t*18)*Math.exp(-t/decay)*canvas.height*.34;i?g.lineTo(x,y):g.moveTo(x,y)}}g.stroke();g.fillStyle="#ef2200";g.beginPath();g.arc(canvas.width-5,canvas.height/2,2.5,0,Math.PI*2);g.fill();traceAnim=requestAnimationFrame(frame)}frame()}
