"use strict";
const LIMITS=Object.freeze({tracks:10,events:480,runs:40,logs:500,messages:80,sketch:128,noteLoops:8,drumLoops:8,effects:8,observerLinks:12,timeoutMs:35000});
const WAVES=new Set(["square","triangle","sawtooth","sine","pulse"]); const DRUMS=new Set(["kick","snare","hat","noise","knock","mallet"]); const FX=new Set(["cutoff","resonance","delay","reverb","distortion","attack","release","sustain","tremolo","tremoloRate"]);
let nextEventId=1,nextMessageId=1,nextRunId=2,apiKeyMemory="",audioCtx=null,activeAudio=[],raf=0,playStart=0,playDuration=0,analyser=null,traceAnim=0,drawActive=false,sketchPoints=[];
const state={project:"UNTITLED TRACE",ai:{mode:"demo",model:"gpt-5.6-terra",endpoint:"/api/trace-ai"},teacher:true,side:"chat",mobile:"world",scope:null,selectedEventId:null,selectedLine:null,selectedRelation:null,sourceMode:"view",sourceDirty:false,busy:false,composition:null,preview:null,pending:null,messages:[],observer:null,runs:[],currentRunId:1,currentParentId:null,logs:[],onboarded:false};
function clone(v){return JSON.parse(JSON.stringify(v))} function clamp(n,a,b){return Math.max(a,Math.min(b,n))} function q(n,s=.25){return Math.round(n/s)*s} function trim(n){return Number(Number(n).toFixed(3)).toString()} function now(){return new Date().toISOString()} function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function track(id,name,kind,wave){return{id,name,kind,wave}} function fx0(){return{cutoff:12000,resonance:0,delay:0,reverb:0,distortion:0,attack:.01,release:.06,sustain:.75,tremolo:0,tremoloRate:6}}
function note(trackId,pitch,start,duration,velocity,wave,prov={}){return{id:nextEventId++,type:"note",track:trackId,pitch:clamp(Math.round(pitch),0,127),start:+start,duration:+duration,velocity:clamp(Math.round(velocity),1,127),wave:WAVES.has(wave)?wave:"square",provenance:{origin:prov.origin||"source",reason:prov.reason||"",promptId:prov.promptId||null,opIndex:Number.isInteger(prov.opIndex)?prov.opIndex:null,sourceLine:null}}}
function drum(trackId,kind,start,duration,velocity,prov={}){return{id:nextEventId++,type:"drum",track:trackId,drum:DRUMS.has(kind)?kind:"noise",start:+start,duration:+duration,velocity:clamp(Math.round(velocity),1,127),provenance:{origin:prov.origin||"source",reason:prov.reason||"",promptId:prov.promptId||null,opIndex:Number.isInteger(prov.opIndex)?prov.opIndex:null,sourceLine:null}}}
function seed(){const c={version:5,title:"FIRST TRACE",bpm:150,bars:8,beatsPerBar:4,tracks:[track(1,"LEAD","synth","square"),track(2,"BASS","synth","triangle"),track(3,"DRUMS","drum","noise")],events:[],fx:{"1":fx0(),"2":fx0(),"3":fx0()}}; const p=[72,76,79,76,74,77,81,77]; for(let i=0;i<16;i++)c.events.push(note(1,p[i%p.length],i*.5,.4,104,"square",{reason:"seed lead"})); for(let i=0;i<8;i++)c.events.push(note(2,[48,48,53,55][i%4],i,.78,92,"triangle",{reason:"seed bass"})); for(let i=0;i<16;i++){if(i%4===0)c.events.push(drum(3,"kick",i*.5,.12,116,{reason:"seed pulse"})); else if(i%4===2)c.events.push(drum(3,"snare",i*.5,.12,96,{reason:"seed backbeat"})); else c.events.push(drum(3,"hat",i*.5,.07,66,{reason:"seed subdivision"}))} return c}
function beats(c=state.composition){return c.bars*c.beatsPerBar} function current(){return state.preview||state.composition} function spb(c=current()){return 60/c.bpm}
function ensure(c){if(!c||!Number.isFinite(c.bpm)||c.bpm<40||c.bpm>240)throw Error("Tempo must be 40–240 BPM."); if(!Number.isInteger(c.bars)||c.bars<1||c.bars>64)throw Error("Bars must be 1–64."); if(!Array.isArray(c.tracks)||c.tracks.length<1||c.tracks.length>LIMITS.tracks)throw Error("Track limit exceeded."); if(!Array.isArray(c.events)||c.events.length>LIMITS.events)throw Error("Event limit exceeded."); const ids=new Set(c.tracks.map(t=>t.id)); for(const e of c.events){if(!ids.has(e.track))throw Error("Event references missing track."); if(!Number.isFinite(e.start)||!Number.isFinite(e.duration)||e.start<0||e.duration<=0||e.start>=beats(c)+.001)throw Error("Invalid event timing.")} return c}
function log(kind,detail={}){state.logs.push({time:now(),kind,detail,runId:state.currentRunId,scope:scopeObject(),selectedEventId:state.selectedEventId}); if(state.logs.length>LIMITS.logs)state.logs.shift(); saveSession()}
function saveSession(){try{localStorage.setItem("trace.v5",JSON.stringify({project:state.project,teacher:state.teacher,composition:state.composition,runs:state.runs.slice(-LIMITS.runs),currentRunId:state.currentRunId,currentParentId:state.currentParentId,logs:state.logs.slice(-LIMITS.logs),messages:state.messages.slice(-40),onboarded:state.onboarded}))}catch{}}
function loadSession(){try{const raw=localStorage.getItem("trace.v5"); if(!raw)return false; const s=JSON.parse(raw); if(s.composition)ensure(s.composition); state.project=s.project||state.project; state.teacher=s.teacher!==false; state.composition=s.composition||seed(); state.runs=Array.isArray(s.runs)?s.runs.slice(-LIMITS.runs):[]; state.currentRunId=s.currentRunId||1; state.currentParentId=s.currentParentId??null; state.logs=Array.isArray(s.logs)?s.logs.slice(-LIMITS.logs):[]; state.messages=Array.isArray(s.messages)?s.messages.slice(-40):[]; state.onboarded=!!s.onboarded; nextRunId=Math.max(2,...state.runs.map(r=>r.id+1)); nextEventId=Math.max(1,...state.composition.events.map(e=>e.id+1)); return true}catch{return false}}
function snapshot(label,prompt=""){const id=nextRunId++; const r={id,parentId:state.currentRunId||null,label:String(label).slice(0,28),time:now(),prompt:String(prompt).slice(0,180),composition:clone(state.composition)}; state.runs.push(r); if(state.runs.length>LIMITS.runs)state.runs.shift(); state.currentParentId=r.parentId; state.currentRunId=id; log("snapshot",{id,parentId:r.parentId,label:r.label}); renderPath(); updateFoot(); return r}
function restoreRun(id){const r=state.runs.find(x=>x.id===id); if(!r)return; stop(); state.composition=clone(r.composition); state.preview=null; state.pending=null; state.currentParentId=r.parentId; state.currentRunId=r.id; state.selectedEventId=null; state.selectedLine=null; syncSource(); renderAll(); addMsg("system",`RESTORED RUN ${id} · next change can leave from here.`); log("restore",{id})}
function forkHere(){const base=state.currentRunId; const r=snapshot("fork",""); r.parentId=base; state.currentParentId=base; addMsg("system",`FORKED FROM RUN ${base}. The earlier path remains in memory.`); renderPath(); log("fork",{base,newRun:r.id})}
function scopeObject(){if(state.scope===null)return{kind:"song",label:"WHOLE SONG",start:0,end:beats(state.composition)}; const start=state.scope*16; return{kind:"section",index:state.scope,label:`S${state.scope+1}`,start,end:Math.min(start+16,beats(state.composition))}}
function selectScope(index){state.scope=index; state.selectedEventId=null; state.selectedLine=null; renderAll(); setSide("chat"); addMsg("system",`${scopeObject().label} bound to CHAT. Ask from here.`); log("scope",scopeObject())}
function clearScope(){state.scope=null; renderAll(); log("scope",scopeObject())}
function compileSource(c=state.composition){const lines=[],bindings=new Map(); lines.push("# TRACE SCRIPT — readable operations, not hidden state"); lines.push(`tempo(${c.bpm})`); lines.push(`bars(${c.bars})`); lines.push(""); for(const t of c.tracks)lines.push(`track(${t.id}, ${JSON.stringify(t.name)}, ${JSON.stringify(t.kind)}, ${JSON.stringify(t.wave||"square")})`); lines.push(""); const groups=groupEvents(c.events); for(const g of groups){const lineNo=lines.length+1; const text=g.type==="noteLoop"?`loopNote(${g.track}, ${JSON.stringify(g.pitches)}, ${trim(g.start)}, ${trim(g.step)}, ${trim(g.duration)}, ${g.repeats}, ${g.velocity}, ${JSON.stringify(g.wave)})`:`loopDrum(${g.track}, ${JSON.stringify(g.drum)}, ${trim(g.start)}, ${trim(g.step)}, ${g.repeats}, ${g.velocity})`; lines.push(text); bindings.set(lineNo,{eventIds:g.ids,origin:g.origin,promptId:g.promptId,opIndex:g.opIndex}); for(const id of g.ids){const e=c.events.find(x=>x.id===id); if(e)e.provenance.sourceLine=lineNo}}
  lines.push(""); const defaults=fx0(); for(const [tid,fx] of Object.entries(c.fx||{})){for(const [k,v] of Object.entries(fx)){if(FX.has(k)&&v!==defaults[k])lines.push(`fx(${tid}, ${JSON.stringify(k)}, ${trim(v)})`)}} return{source:lines.join("\n"),bindings}}
function groupEvents(events){const sorted=[...events].sort((a,b)=>a.track-b.track||a.start-b.start); const out=[]; let i=0; while(i<sorted.length){const e=sorted[i],same=[]; for(let j=i;j<Math.min(sorted.length,i+64);j++){const x=sorted[j]; if(x.type!==e.type||x.track!==e.track||x.provenance.origin!==e.provenance.origin||x.provenance.promptId!==e.provenance.promptId||x.provenance.opIndex!==e.provenance.opIndex)break; same.push(x)} if(e.type==="note"&&same.length>=2){const step=+(same[1].start-same[0].start).toFixed(6); let n=1; while(n<same.length&&Math.abs((same[n].start-same[n-1].start)-step)<1e-6&&Math.abs(same[n].duration-e.duration)<1e-6&&same[n].velocity===e.velocity&&same[n].wave===e.wave)n++; out.push({type:"noteLoop",track:e.track,pitches:same.slice(0,n).map(x=>x.pitch),start:e.start,step,duration:e.duration,repeats:n,velocity:e.velocity,wave:e.wave,ids:same.slice(0,n).map(x=>x.id),origin:e.provenance.origin,promptId:e.provenance.promptId,opIndex:e.provenance.opIndex}); i+=n}else if(e.type==="drum"&&same.length>=2){const step=+(same[1].start-same[0].start).toFixed(6); let n=1; while(n<same.length&&same[n].drum===e.drum&&Math.abs((same[n].start-same[n-1].start)-step)<1e-6&&same[n].velocity===e.velocity)n++; out.push({type:"drumLoop",track:e.track,drum:e.drum,start:e.start,step,repeats:n,velocity:e.velocity,ids:same.slice(0,n).map(x=>x.id),origin:e.provenance.origin,promptId:e.provenance.promptId,opIndex:e.provenance.opIndex}); i+=n}else{if(e.type==="note")out.push({type:"noteLoop",track:e.track,pitches:[e.pitch],start:e.start,step:1,duration:e.duration,repeats:1,velocity:e.velocity,wave:e.wave,ids:[e.id],origin:e.provenance.origin,promptId:e.provenance.promptId,opIndex:e.provenance.opIndex}); else out.push({type:"drumLoop",track:e.track,drum:e.drum,start:e.start,step:1,repeats:1,velocity:e.velocity,ids:[e.id],origin:e.provenance.origin,promptId:e.provenance.promptId,opIndex:e.provenance.opIndex}); i++}} return out}
function parseSource(text){const c={version:5,title:state.composition.title,bpm:120,bars:8,beatsPerBar:4,tracks:[],events:[],fx:{}}; const lines=text.split(/\r?\n/); if(lines.length>900)throw Error("Source too long."); for(let li=0;li<lines.length;li++){const raw=lines[li].trim(); if(!raw||raw.startsWith("#")||raw.startsWith("//"))continue; let m; if((m=raw.match(/^tempo\(([-\d.]+)\)$/))){c.bpm=+m[1];continue} if((m=raw.match(/^bars\((\d+)\)$/))){c.bars=+m[1];continue} if((m=raw.match(/^track\((\d+),\s*("(?:[^"\\]|\\.)*"),\s*("(?:[^"\\]|\\.)*"),\s*("(?:[^"\\]|\\.)*")\)$/))){const id=+m[1],name=JSON.parse(m[2]),kind=JSON.parse(m[3]),wave=JSON.parse(m[4]); c.tracks.push(track(id,name,kind,wave)); c.fx[String(id)]=fx0(); continue} if((m=raw.match(/^loopNote\((\d+),\s*(\[[^\]]*\]),\s*([-\d.]+),\s*([-\d.]+),\s*([-\d.]+),\s*(\d+),\s*(\d+),\s*("(?:[^"\\]|\\.)*")\)$/))){const tid=+m[1],p=JSON.parse(m[2]),start=+m[3],step=+m[4],dur=+m[5],rep=+m[6],vel=+m[7],wave=JSON.parse(m[8]); if(!Array.isArray(p)||p.length<1||p.length>32||rep<1||rep>64)throw Error(`Line ${li+1}: loop bound invalid.`); for(let i=0;i<rep;i++){c.events.push(note(tid,+p[i%p.length],start+i*step,dur,vel,wave,{reason:`source line ${li+1}`})); if(c.events.length>LIMITS.events)throw Error(`Line ${li+1}: event limit exceeded.`)} continue} if((m=raw.match(/^loopDrum\((\d+),\s*("(?:[^"\\]|\\.)*"),\s*([-\d.]+),\s*([-\d.]+),\s*(\d+),\s*(\d+)\)$/))){const tid=+m[1],kind=JSON.parse(m[2]),start=+m[3],step=+m[4],rep=+m[5],vel=+m[6]; if(rep<1||rep>64)throw Error(`Line ${li+1}: loop bound invalid.`); for(let i=0;i<rep;i++)c.events.push(drum(tid,kind,start+i*step,.12,vel,{reason:`source line ${li+1}`})); continue} if((m=raw.match(/^fx\((\d+),\s*("(?:[^"\\]|\\.)*"),\s*([-\d.]+)\)$/))){const tid=String(+m[1]),p=JSON.parse(m[2]),v=+m[3]; if(!FX.has(p))throw Error(`Line ${li+1}: unknown effect.`); c.fx[tid]||=fx0(); c.fx[tid][p]=v; continue} throw Error(`Line ${li+1}: unsupported TRACE statement.`)} return ensure(c)}
