/* logs + files */
function dl(name,data,type="application/json"){const blob=data instanceof Uint8Array?new Blob([data],{type}):new Blob([typeof data==="string"?data:JSON.stringify(data,null,2)],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),800)}
function exportSession(){dl("trace-session.json",{version:5,project:state.project,composition:state.composition,runs:state.runs,logs:state.logs,messages:state.messages,teacher:state.teacher})}
function midi(c=state.composition){const ppq=480,ev=[],u16=n=>[(n>>8)&255,n&255],u32=n=>[(n>>24)&255,(n>>16)&255,(n>>8)&255,n&255],str=s=>[...s].map(ch=>ch.charCodeAt(0)&255),vlq=n=>{n=Math.max(0,Math.floor(n));let b=n&127,o=[];while((n>>=7)){b<<=8;b|=(n&127)|128}for(;;){o.push(b&255);if(b&128)b>>=8;else break}return o};const us=Math.round(60000000/c.bpm);ev.push({t:0,b:[255,81,3,(us>>16)&255,(us>>8)&255,us&255],o:0});for(const e of c.events)if(e.type==="note"){const ch=(e.track-1)%15;ev.push({t:Math.round(e.start*ppq),b:[144|ch,e.pitch,e.velocity],o:1},{t:Math.round((e.start+e.duration)*ppq),b:[128|ch,e.pitch,0],o:0})}ev.sort((a,b)=>a.t-b.t||a.o-b.o);let tr=[],last=0;for(const e of ev){tr.push(...vlq(e.t-last),...e.b);last=e.t}tr.push(0,255,47,0);return new Uint8Array([...str("MThd"),...u32(6),...u16(0),...u16(1),...u16(ppq),...str("MTrk"),...u32(tr.length),...tr])}
/* draggable widths */
function splitBind(el,which){let startX=0,startA=0,startB=0;el.addEventListener("pointerdown",e=>{if(innerWidth<=860)return;startX=e.clientX;const cs=getComputedStyle(document.documentElement);startA=parseFloat(cs.getPropertyValue("--a"));startB=parseFloat(cs.getPropertyValue("--b"));el.setPointerCapture(e.pointerId)});el.addEventListener("pointermove",e=>{if(!el.hasPointerCapture(e.pointerId))return;const delta=(e.clientX-startX)/innerWidth*100;if(which===1){const a=clamp(startA+delta,28,66),b=clamp(startB-delta,16,42);document.documentElement.style.setProperty("--a",`${a}%`);document.documentElement.style.setProperty("--b",`${b}%`)}else{const b=clamp(startB+delta,16,48);document.documentElement.style.setProperty("--b",`${b}%`)}});el.addEventListener("pointerup",e=>{if(el.hasPointerCapture(e.pointerId))el.releasePointerCapture(e.pointerId);log("resize_panels",{})})}
/* sketch */
const sketch=document.getElementById("sketch"),sg=sketch.getContext("2d");function sketchRedraw(){sg.clearRect(0,0,sketch.width,sketch.height);sg.fillStyle="#fff";sg.fillRect(0,0,sketch.width,sketch.height);if(sketchPoints.length<2)return;sg.strokeStyle="#000";sg.lineWidth=5;sg.lineCap="square";sg.beginPath();sketchPoints.forEach((p,i)=>i?sg.lineTo(p.x*sketch.width,p.y*sketch.height):sg.moveTo(p.x*sketch.width,p.y*sketch.height));sg.stroke();document.getElementById("sketchMeta").textContent=`${sketchPoints.length} POINTS`}
function sketchPoint(e){if(sketchPoints.length>=LIMITS.sketch)return;const r=sketch.getBoundingClientRect(),p={x:clamp((e.clientX-r.left)/r.width,0,1),y:clamp((e.clientY-r.top)/r.height,0,1)},last=sketchPoints.at(-1);if(!last||Math.hypot(p.x-last.x,p.y-last.y)>.01)sketchPoints.push(p)}
sketch.addEventListener("pointerdown",e=>{drawActive=true;sketchPoints=[];sketch.setPointerCapture(e.pointerId);sketchPoint(e);sketchRedraw()});sketch.addEventListener("pointermove",e=>{if(drawActive){sketchPoint(e);sketchRedraw()}});sketch.addEventListener("pointerup",()=>{drawActive=false;sketchRedraw()});sketch.addEventListener("pointercancel",()=>drawActive=false);
