"use strict";
async function v7LoadTags(){if(v7Tags.length)return v7Tags;if(v7TagPromise)return v7TagPromise;v7TagPromise=fetch("treblo_tags_v3.txt",{cache:"force-cache"}).then(r=>r.ok?r.text():"").then(text=>{const loaded=text.split(/\r?\n/).map(x=>x.trim().toLowerCase()).filter(x=>x&&x.length<64).slice(0,5000);v7Tags=loaded.length?loaded:[...V7_COMMON_TAGS];return v7Tags}).catch(()=>{v7Tags=[...V7_COMMON_TAGS];return v7Tags});return v7TagPromise}
function v7Tokens(s){return String(s).toLowerCase().replace(/[^a-z0-9À-ž+& -]/g," ").split(/\s+/).filter(x=>x.length>2)}
function v7Hash(s){let h=2166136261;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function v7TagCandidates(text){const q=String(text).toLowerCase(),qt=new Set(v7Tokens(q)),scored=[];for(const tag of v7Tags){let score=q.includes(tag)?8:0;for(const tok of v7Tokens(tag))if(qt.has(tok))score+=2;if(score)scored.push([tag,score])}scored.sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));const out=scored.slice(0,24).map(x=>x[0]),h=v7Hash(text);for(let i=0;i<6;i++){const x=V7_DISTANT_STONES[(h+i*11)%V7_DISTANT_STONES.length];if(!out.includes(x))out.push(x)}return out.slice(0,30)}

const V7_COMPOSER_PROMPT=`You are TRACE Composer v7 inside an executable music-learning environment.
The user may name multiple genres, eras, places, artists, production practices, instruments, gestures, or contradictory references. Preserve that variety instead of collapsing it into LEAD + BASS + DRUMS.

OPERATIVE LAW: descriptive variety must meet musical variety.
For a broad whole-song or hybrid request, normally use 5–10 meaningfully different channels. Do not add tracks merely to hit a count. Give each active channel a distinct job in rhythm, register, timbre, phrase behavior, or space.

AVAILABLE CHANNEL KINDS: synth, lead, bass, drum, electric-piano, organ, guitar, horn, reed, strings, flute, mallet, percussion, texture, voice.
You may rename or repurpose existing channel ids with track_changes. New ids must be 1–16. Prefer existing ids when possible.
AVAILABLE DRUM VOICES: kick, snare, hat, clap, tom, rim, shaker, cowbell, conga, clave, woodblock, tambourine, bell, knock, mallet, noise.
NOTE waves remain sine, triangle, sawtooth, square, pulse; channel kind supplies the larger timbral identity.

Translate references across independent axes: orchestration, rhythmic grammar, pitch collection, phrase length, register, density, articulation, form, and production. Do not assume every energetic request means faster tempo. Do not assume every genre is a four-on-the-floor loop.
Use off-grid starts, unequal phrase lengths, rests, call-and-response, sparse layers, contrasting registers, and local variation when the reference supports them. Repetition should have a reason.
When the prompt combines lineages, let different channels carry different lineages rather than averaging everything into one generic groove.
The context may include tag_candidates. Treat them as vocabulary clues and stepping stones, not commandments.
Do not copy a specific existing melody or recording. Translate named references into high-level musical operations.
Each operation needs a short plain reason that names the audible consequence.
Keep changes bounded to the selected scope unless the user clearly asks for a whole-song rebuild.
Output only the supplied JSON schema.`;

const V7_COMPOSER_SCHEMA={type:"object",additionalProperties:false,required:["summary","interpretation","dimensions","alternatives","tempo","track_changes","clear_ranges","note_loops","drum_loops","effects"],properties:{summary:{type:"string"},interpretation:{type:"array",maxItems:6,items:{type:"string"}},dimensions:{type:"array",maxItems:7,items:{type:"string",enum:["rhythm","pitch","time","timbre","space","form","orchestration"]}},alternatives:{type:"array",maxItems:4,items:{type:"string"}},tempo:{type:["integer","null"]},track_changes:{type:"array",maxItems:12,items:{type:"object",additionalProperties:false,required:["track","name","kind","wave","reason"],properties:{track:{type:"integer",minimum:1,maximum:16},name:{type:"string"},kind:{type:"string",enum:["synth","lead","bass","drum","electric-piano","organ","guitar","horn","reed","strings","flute","mallet","percussion","texture","voice"]},wave:{type:"string",enum:["square","triangle","sawtooth","sine","pulse"]},reason:{type:"string"}}}},clear_ranges:{type:"array",maxItems:12,items:{type:"object",additionalProperties:false,required:["track","start","end","reason"],properties:{track:{type:"integer"},start:{type:"number"},end:{type:"number"},reason:{type:"string"}}}},note_loops:{type:"array",maxItems:16,items:{type:"object",additionalProperties:false,required:["track","pitches","start","step","duration","repeats","velocity","wave","reason"],properties:{track:{type:"integer"},pitches:{type:"array",maxItems:24,items:{type:"integer"}},start:{type:"number"},step:{type:"number"},duration:{type:"number"},repeats:{type:"integer",minimum:1,maximum:64},velocity:{type:"integer",minimum:1,maximum:127},wave:{type:"string",enum:["square","triangle","sawtooth","sine","pulse"]},reason:{type:"string"}}}},drum_loops:{type:"array",maxItems:16,items:{type:"object",additionalProperties:false,required:["track","drum","start","step","repeats","velocity","reason"],properties:{track:{type:"integer"},drum:{type:"string",enum:["kick","snare","hat","clap","tom","rim","shaker","cowbell","conga","clave","woodblock","tambourine","bell","knock","mallet","noise"]},start:{type:"number"},step:{type:"number"},repeats:{type:"integer",minimum:1,maximum:64},velocity:{type:"integer",minimum:1,maximum:127},reason:{type:"string"}}}},effects:{type:"array",maxItems:16,items:{type:"object",additionalProperties:false,required:["track","parameter","value","reason"],properties:{track:{type:"integer"},parameter:{type:"string",enum:["cutoff","resonance","delay","reverb","distortion","attack","release","sustain","tremolo","tremoloRate"]},value:{type:"number"},reason:{type:"string"}}}}}};

function context(){const c=state.composition,s=scopeObject(),sel=c.events.find(e=>e.id===state.selectedEventId)||null;return{project:state.project,scope:s,selected:sel?{id:sel.id,type:sel.type,track:sel.track,start:sel.start,pitch:sel.pitch||null,drum:sel.drum||null,reason:sel.provenance.reason}:null,sketch:sketchSummary(),bpm:c.bpm,bars:c.bars,tracks:c.tracks.map(t=>({id:t.id,name:t.name,kind:t.kind,wave:t.wave})),tag_candidates:v7LastTagCandidates,effects:c.fx,events:c.events.filter(e=>e.start>=s.start&&e.start<s.end).slice(0,180).map(e=>e.type==="note"?{id:e.id,k:"n",t:e.track,p:e.pitch,s:e.start,d:e.duration,v:e.velocity,w:e.wave}:{id:e.id,k:"d",t:e.track,dr:e.drum,s:e.start,v:e.velocity})}}
function validatePlan(p){if(!p||typeof p!=="object")throw Error("Model returned no plan.");p.track_changes=Array.isArray(p.track_changes)?p.track_changes:[];for(const k of ["clear_ranges","note_loops","drum_loops","effects","interpretation","dimensions","alternatives"])if(!Array.isArray(p[k]))throw Error(`Model plan missing ${k}.`);if(p.track_changes.length>12||p.note_loops.length>V7_NOTE_LOOP_LIMIT||p.drum_loops.length>V7_DRUM_LOOP_LIMIT||p.effects.length>V7_EFFECT_LIMIT)throw Error("Model plan exceeded bounded variety limits.");for(const x of p.track_changes){if(!Number.isInteger(x.track)||x.track<1||x.track>V7_TRACK_LIMIT||!V7_KINDS.has(x.kind)||!WAVES.has(x.wave))throw Error("Model track change invalid.")}for(const x of p.note_loops)if(x.repeats<1||x.repeats>64||!Array.isArray(x.pitches)||x.pitches.length<1||x.pitches.length>24||x.step<=0||x.duration<=0)throw Error("Model note loop invalid.");for(const x of p.drum_loops)if(x.repeats<1||x.repeats>64||x.step<=0||!V7_DRUMS.has(x.drum))throw Error("Model drum loop invalid.");return p}
function planOperations(plan){const ops=[];if(plan.tempo!==null)ops.push({kind:"tempo",index:0,reason:"tempo",data:{bpm:plan.tempo}});plan.track_changes.forEach((x,i)=>ops.push({kind:"track_change",index:i,reason:x.reason,data:x}));plan.clear_ranges.forEach((x,i)=>ops.push({kind:"clear_range",index:i,reason:x.reason,data:x}));plan.note_loops.forEach((x,i)=>ops.push({kind:"note_loop",index:i,reason:x.reason,data:x}));plan.drum_loops.forEach((x,i)=>ops.push({kind:"drum_loop",index:i,reason:x.reason,data:x}));plan.effects.forEach((x,i)=>ops.push({kind:"effect",index:i,reason:x.reason,data:x}));return ops}
function sourcePatch(plan){const lines=[];if(plan.tempo!==null)lines.push(`tempo(${plan.tempo})`);for(const x of plan.track_changes){lines.push(`# ${x.reason}`);lines.push(`track(${x.track}, ${JSON.stringify(x.name)}, ${JSON.stringify(x.kind)}, ${JSON.stringify(x.wave)})`)};for(const x of plan.clear_ranges)lines.push(`# clear track ${x.track} beats ${trim(x.start)}–${trim(x.end)} · ${x.reason}`);for(const x of plan.note_loops)lines.push(`loopNote(${x.track}, ${JSON.stringify(x.pitches)}, ${trim(x.start)}, ${trim(x.step)}, ${trim(x.duration)}, ${x.repeats}, ${x.velocity}, ${JSON.stringify(x.wave)})`);for(const x of plan.drum_loops)lines.push(`loopDrum(${x.track}, ${JSON.stringify(x.drum)}, ${trim(x.start)}, ${trim(x.step)}, ${x.repeats}, ${x.velocity})`);for(const x of plan.effects)lines.push(`fx(${x.track}, ${JSON.stringify(x.parameter)}, ${trim(x.value)})`);return lines.join("\n")}
function applyPlan(base,plan,promptId,preview=true){const c=clone(base);let oi=0;const prov=(reason,opIndex)=>({origin:"ai",reason,promptId,opIndex});for(const x of plan.track_changes){const found=c.tracks.find(t=>+t.id===+x.track);if(found){found.name=String(x.name).slice(0,24);found.kind=x.kind;found.wave=x.wave}else{if(c.tracks.length>=V7_TRACK_LIMIT)throw Error("Plan would exceed track limit.");c.tracks.push(v7Track(x.track,x.name,x.kind,x.wave));c.fx[String(x.track)]=fx0()}oi++}if(plan.tempo!==null)c.bpm=clamp(Math.round(plan.tempo),30,280);for(const x of plan.clear_ranges){c.events=c.events.filter(e=>!(e.track===x.track&&e.start>=x.start&&e.start<x.end));oi++}const ids=new Set(c.tracks.map(t=>+t.id));for(const x of plan.note_loops){if(!ids.has(+x.track))throw Error(`Plan references missing track ${x.track}.`);for(let i=0;i<x.repeats;i++){c.events.push(note(x.track,x.pitches[i%x.pitches.length],x.start+i*x.step,x.duration,x.velocity,x.wave,prov(x.reason,oi)));if(c.events.length>V7_EVENT_LIMIT)throw Error("Plan would exceed event limit.")}oi++}for(const x of plan.drum_loops){if(!ids.has(+x.track))throw Error(`Plan references missing track ${x.track}.`);for(let i=0;i<x.repeats;i++){c.events.push(drum(x.track,x.drum,x.start+i*x.step,.12,x.velocity,prov(x.reason,oi)));if(c.events.length>V7_EVENT_LIMIT)throw Error("Plan would exceed event limit.")}oi++}for(const x of plan.effects){c.fx[String(x.track)]||=fx0();c.fx[String(x.track)][x.parameter]=x.value;oi++}if(preview)for(const e of c.events)if(e.provenance.promptId===promptId)e.preview=true;return ensure(c)}

function v7DemoPlan(text){const l=text.toLowerCase(),s=scopeObject(),span=Math.max(4,s.end-s.start),p={summary:"DEMO · orchestration + rhythm + timbre",interpretation:[],dimensions:["orchestration","rhythm","pitch","timbre"],alternatives:["keep the lineage split but exchange which channel carries each one","strip the ensemble to three voices and preserve only the rhythmic grammar"],tempo:null,track_changes:[],clear_ranges:[],note_loops:[],drum_loops:[],effects:[]};const use=(id,name,kind,wave,reason)=>p.track_changes.push({track:id,name,kind,wave,reason});
  use(2,"ROOT / FIFTH","bass","triangle","make the low register its own lineage carrier");use(3,"LOOSE KIT","drum","sine","separate drum grammar from melody");use(4,"RHODES","electric-piano","sine","give harmony a soft struck voice");use(5,"ORGAN","organ","sine","give sustained harmony a different body");use(7,"HORNS","horn","sawtooth","reserve a channel for calls rather than forcing the lead to do everything");use(11,"HAND PERC","percussion","sine","let cyclical percussion live outside the drum kit");
  if(/ethiop|afro.?jazz|afrojazz/.test(l)){use(8,"REED","reed","square","carry the modal horn-line reference on its own channel");p.note_loops.push({track:8,pitches:[74,77,79,78,74,70,72],start:s.start,step:.75,duration:.44,repeats:Math.min(14,Math.floor(span/.75)),velocity:88,wave:"square",reason:"asymmetric modal call with a semitone turn"});p.drum_loops.push({track:11,drum:"conga",start:s.start+.25,step:1.5,repeats:Math.min(18,Math.floor(span/1.5)),velocity:72,reason:"cyclic hand-percussion counter-pulse"});p.interpretation.push("I kept the Ethiopian-jazz reference as a modal reed/horn behavior and a separate cyclical percussion layer, not as a generic lead patch.")}
  if(/country|dolly|appalach|nashville/.test(l)){use(6,"PICKED GUITAR","guitar","triangle","give the country lineage a plucked channel");p.note_loops.push({track:6,pitches:[62,69,66,69,64,71,67,71],start:s.start+.5,step:1,duration:.28,repeats:Math.min(16,Math.floor(span)),velocity:70,wave:"triangle",reason:"open-fifth picked answer with breathing room"});p.interpretation.push("I carried the country reference through a picked response voice and open interval motion rather than averaging it into the horn line.")}
  if(/psyched|grateful|dead|jam/.test(l)){use(12,"TAPE GHOST","texture","sine","give the psychedelic production its own slow layer");p.effects.push({track:5,parameter:"delay",value:.29,reason:"organ repeats leave a decaying trace"},{track:12,parameter:"reverb",value:.52,reason:"push the texture behind the ensemble"},{track:6,parameter:"tremolo",value:.22,reason:"make the guitar shimmer without changing its notes"});p.note_loops.push({track:12,pitches:[55,62,60,67],start:s.start,step:4,duration:3.2,repeats:Math.min(8,Math.ceil(span/4)),velocity:36,wave:"sine",reason:"slow background tones resist the foreground loop grid"});p.interpretation.push("I separated psychedelic production from melodic identity by giving it a slow texture and modulation layer.")}
  if(/soul/.test(l)){p.note_loops.push({track:4,pitches:[60,64,67,70,62,65,69,72],start:s.start,step:2,duration:1.3,repeats:Math.min(16,Math.ceil(span/2)),velocity:72,wave:"sine",reason:"warm chord-tone punctuations leave air for calls"});p.note_loops.push({track:7,pitches:[72,74,77,74,70],start:s.start+3,step:2.5,duration:.55,repeats:Math.min(10,Math.ceil(span/2.5)),velocity:82,wave:"sawtooth",reason:"horn answers land in gaps instead of doubling the lead"});p.interpretation.push("I let soul live in organ/Rhodes spacing and horn answers rather than just adding reverb to a pentatonic lead.")}
  p.note_loops.push({track:2,pitches:[43,43,50,46,48,43,53],start:s.start,step:1.5,duration:.68,repeats:Math.min(20,Math.floor(span/1.5)),velocity:88,wave:"triangle",reason:"root-and-fifth motion with an uneven seven-note cycle"});p.drum_loops.push({track:3,drum:"kick",start:s.start,step:2,repeats:Math.min(16,Math.ceil(span/2)),velocity:102,reason:"leave holes between kicks"},{track:3,drum:"snare",start:s.start+2.12,step:4,repeats:Math.min(8,Math.ceil(span/4)),velocity:94,reason:"slightly late backbeat keeps the grid from feeling mechanical"},{track:11,drum:"shaker",start:s.start+.62,step:.75,repeats:Math.min(40,Math.floor(span/.75)),velocity:42,reason:"uneven peripheral subdivision creates motion without dominating"});return validatePlan(p)}
async function compose(text){await v7LoadTags();v7LastTagCandidates=v7TagCandidates(text);if(state.ai.mode==="demo")return v7DemoPlan(text);return validatePlan(await requestStructured("trace_composer",V7_COMPOSER_PROMPT,V7_COMPOSER_SCHEMA,{request:text,context:context()},4800))}

function publicRead(text){const l=String(text).toLowerCase(),scores={rhythm:0,pitch:0,time:0,timbre:0,space:0,form:0,orchestration:0},add=(d,words)=>{for(const w of words)if(l.includes(w))scores[d]++};add("rhythm",["rhythm","beat","groove","pulse","swing","shuffle","syncop","drum","footwork","afrobeat","gnawa"]);add("pitch",["melody","mode","modal","rise","fall","high","low","hook","pitch","microton"]);add("time",["faster","slower","tempo","rush","drag","accelerat","half-time","double-time"]);add("timbre",["dark","rough","grit","soft","harsh","filter","distort","tape","fuzz","acoustic","electric"]);add("space",["echo","reverb","space","far","close","ghost","memory","dub"]);add("form",["section","break","intro","outro","drop","structure","response","call","verse","chorus"]);add("orchestration",["jazz","soul","country","orchestra","band","ensemble","horn","organ","guitar","piano","rhodes","reed","flute","string","voice","vocal","percussion","afro","ethiop"]);const carriers=Object.entries(scores).sort((a,b)=>b[1]-a[1]).map(([name,score])=>({name,score}));if(!carriers[0].score)carriers[0].score=1;return carriers}