'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const API_PROXY='https://lcxykqgddnekrimawpie.supabase.co/functions/v1/openai-proxy', SUPABASE_PUBLISHABLE='sb_publishable_bF2QF1eJmzhi4Pj-dxE-0g_mnm6zRSh';
let apiKey='',verified=false,audioCtx=null,project=null,currentTrack=-1,screen='band',nodes=[],playing=false,children=[],mark={a:0,b:0},drag=false,chat=[],sampleBuffer=null;
const body=$('#body'),anno=$('#anno'),bx=body.getContext('2d'),ax=anno.getContext('2d');
function viewport(){document.documentElement.style.setProperty('--app-h',Math.round(window.visualViewport?.height||innerHeight)+'px')}viewport();window.visualViewport?.addEventListener('resize',viewport);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setState(t,k=''){$('#state').textContent=t;$('#dot').className='dot '+k}
function ensureAudio(){audioCtx=audioCtx||new(AudioContext||webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
async function api(path,body=null){const r=await fetch(API_PROXY,{method:'POST',headers:{Authorization:`Bearer ${SUPABASE_PUBLISHABLE}`,apikey:SUPABASE_PUBLISHABLE,'Content-Type':'application/json','x-openai-key':apiKey},body:JSON.stringify({path,method:body?'POST':'GET',body})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error?.message||d?.error||d?.message||String(r.status));return d}
function responseText(d){if(d.output_text)return d.output_text;for(const o of d.output||[])for(const c of o.content||[])if(typeof c.text==='string')return c.text;throw new Error('No response')}
async function structured(prompt,name,schema){const d=await api('/responses',{model:$('#model').value,input:[{role:'user',content:prompt}],text:{format:{type:'json_schema',name,schema,strict:true}}});return JSON.parse(responseText(d))}
$('#check').onclick=async()=>{apiKey=$('#key').value.trim();if(!apiKey)return $('#gateState').textContent='ENTER KEY';$('#gateState').textContent='CHECKING';try{await api('/models');verified=true;$('#gate').classList.add('hidden');setState('READY','good')}catch(e){$('#gateState').textContent=e.message}};

const PAT={type:'array',minItems:16,maxItems:16,items:{type:'integer',minimum:0,maximum:2}};
const TRACK={type:'object',additionalProperties:false,required:['name','role','engine','pitch','gain','pan','pattern','timbre'],properties:{name:{type:'string'},role:{type:'string'},engine:{type:'string',enum:['kick','snare','noise','bass','tone','pad','pluck']},pitch:{type:'integer',minimum:24,maximum:96},gain:{type:'number',minimum:.15,maximum:1},pan:{type:'number',minimum:-1,maximum:1},pattern:PAT,timbre:{type:'object',additionalProperties:false,required:['attack','decay','cutoff','drive'],properties:{attack:{type:'number',minimum:.001,maximum:.4},decay:{type:'number',minimum:.03,maximum:2},cutoff:{type:'number',minimum:100,maximum:16000},drive:{type:'number',minimum:0,maximum:1}}}}};
const PROJECT={type:'object',additionalProperties:false,required:['title','tempo','variety','theory','tracks','listener'],properties:{title:{type:'string'},tempo:{type:'integer',minimum:50,maximum:180},variety:{type:'array',minItems:4,maxItems:8,items:{type:'string'}},theory:{type:'array',minItems:3,maxItems:6,items:{type:'string'}},tracks:{type:'array',minItems:4,maxItems:8,items:TRACK},listener:{type:'string'}}};
const MUT={type:'object',additionalProperties:false,required:['axis','name','pitch','gain','pan','pattern','timbre','why'],properties:{axis:{type:'string',enum:['BODY','RHYTHM','TIMING','STRANGER']},name:{type:'string'},pitch:{type:'integer',minimum:24,maximum:96},gain:{type:'number',minimum:.15,maximum:1},pan:{type:'number',minimum:-1,maximum:1},pattern:PAT,timbre:{type:'object',additionalProperties:false,required:['attack','decay','cutoff','drive'],properties:{attack:{type:'number',minimum:.001,maximum:.4},decay:{type:'number',minimum:.03,maximum:2},cutoff:{type:'number',minimum:100,maximum:16000},drive:{type:'number',minimum:0,maximum:1}}},why:{type:'string'}}};
const MUT4={type:'object',additionalProperties:false,required:['children'],properties:{children:{type:'array',minItems:4,maxItems:4,items:MUT}}};
const CHAT={type:'object',additionalProperties:false,required:['answer','action','instruction'],properties:{answer:{type:'string'},action:{type:'string',enum:['NONE','MORE','REARRANGE','MICROSCOPE']},instruction:{type:'string'}}};

function busy(step,title){$('#busy').classList.add('on');$('#busyTitle').textContent=title;['bs0','bs1','bs2','bs3'].forEach((x,i)=>$('#'+x).classList.toggle('on',i<=step));setState(title,'busy')}
function endBusy(){$('#busy').classList.remove('on');setState('READY','good')}
async function arrange(){
 const prompt=$('#prompt').value.trim();if(!prompt)return;
 if(!verified){project=localProject(prompt);renderBand();return}
 busy(0,'READING SOURCE');try{
  busy(1,'CHOOSING DIFFERENCE + THEORY');
  project=await structured(`You are the whole SKETCHSONG BAND: Source Reader, Variety Hound, Theory Agent, Arranger, and Listener. Build an original 16-step one-bar band loop whose parts can later be individually opened under a sound microscope. Avoid generic instrumentation and identical patterns. Use 4-8 tracks, and make each role relationally distinct. Variety should include unusual lineage/rhythm/timbre/form stepping stones. Theory is 3-6 short causal translation rules. Listener is one terse unresolved tension.\nPROMPT: ${prompt}`,'band_project',PROJECT);
  busy(2,'THE BAND IS PLAYING');renderBand();busy(3,'LISTENER LEFT A TENSION');setTimeout(endBusy,180)
 }catch(e){setState(e.message,'bad');$('#busy').classList.remove('on')}
}
function localProject(p){return{title:p.slice(0,28)||'Untitled',tempo:92,variety:['broken pulse','dry room','modal bass','counter-rhythm'],theory:['density → event density','repetition → ostinato','contrast → register'],listener:'the pulse is too settled',tracks:[
{name:'KICK',role:'ground',engine:'kick',pitch:36,gain:.9,pan:0,pattern:[2,0,0,0,1,0,0,0,2,0,0,0,1,0,0,0],timbre:{attack:.003,decay:.18,cutoff:900,drive:.15}},
{name:'SNARE',role:'answer',engine:'snare',pitch:38,gain:.7,pan:.1,pattern:[0,0,0,0,2,0,0,0,0,0,0,1,2,0,0,0],timbre:{attack:.002,decay:.12,cutoff:5500,drive:.08}},
{name:'BASS',role:'pull',engine:'bass',pitch:43,gain:.65,pan:-.1,pattern:[2,0,1,0,0,0,1,0,2,0,0,1,0,0,1,0],timbre:{attack:.01,decay:.32,cutoff:1200,drive:.12}},
{name:'AIR',role:'friction',engine:'noise',pitch:72,gain:.28,pan:.5,pattern:[0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0],timbre:{attack:.03,decay:.18,cutoff:4800,drive:.22}}
]}}
$('#rerollBand').onclick=arrange;

function renderBand(){if(!project)return;$('#title').textContent=project.title;$('#tempo').textContent=project.tempo+' BPM';$('#seedRail').innerHTML='<span>WORD</span>'+project.variety.map(x=>`<span class="active">${esc(x)}</span>`).join('');$('#theory').innerHTML=project.theory.map(x=>`<span>${esc(x)}</span>`).join('')+`<span>LISTENER: ${esc(project.listener||'')}</span>`;$('#lanes').innerHTML=project.tracks.map((t,i)=>`<div class="lane ${i===currentTrack?'current':''}" data-i="${i}"><div class="laneName"><b>${esc(t.name)}</b><span>${esc(t.role)} · ${esc(t.engine)}</span></div><div class="steps">${t.pattern.map((v,s)=>`<button class="step ${v?'on':''} ${v===2?'accent':''}" data-step="${i}:${s}"></button>`).join('')}</div><button class="micro" data-micro="${i}">⌕</button></div>`).join('');$$('[data-step]').forEach(b=>b.onclick=()=>{const [i,s]=b.dataset.step.split(':').map(Number);project.tracks[i].pattern[s]=(project.tracks[i].pattern[s]+1)%3;renderBand()});$$('[data-micro]').forEach(b=>b.onclick=()=>openMicro(+b.dataset.micro))}
function openMicro(i){currentTrack=i;screen='micro';$('#band').classList.remove('on');$('#micro').classList.add('on');children=[];$('#microName').textContent=project.tracks[i].name;$('#microMeta').textContent=project.tracks[i].role+' · '+project.tracks[i].engine;renderMicro()}
$('#back').onclick=()=>{screen='band';$('#micro').classList.remove('on');$('#band').classList.add('on');renderBand()};

function renderMicro(){const t=project?.tracks[currentTrack];if(!t)return;drawTrack(t);$('#cause').innerHTML='<span class="label">CAUSE</span>'+Object.entries(t.timbre).map(([k,v])=>`<span>${k} ${Number(v).toFixed(2)}</span>`).join('')+`<span>pitch ${t.pitch}</span><span>gain ${t.gain.toFixed(2)}</span><span>pan ${t.pan.toFixed(2)}</span>`;$('#cards').innerHTML=children.length?children.map((c,i)=>`<button class="child" data-child="${i}"><div><div class="axisName">${c.axis}</div><div class="name">${esc(c.name)}</div></div><div class="why">${esc(c.why)}</div><div class="mini">tap = audition · long = USE</div></button>`).join(''):['BODY','RHYTHM','TIMING','STRANGER'].map(a=>`<div class="child"><div class="axisName">${a}</div><div class="why">press MORE</div></div>`).join('');$$('[data-child]').forEach(el=>{let tm,long=false;el.onpointerdown=()=>{long=false;tm=setTimeout(()=>{long=true;useChild(+el.dataset.child)},520)};el.onpointerup=()=>{clearTimeout(tm);if(!long)auditionChild(+el.dataset.child)}})}
function drawTrack(t){const w=body.width,h=body.height;bx.fillStyle='#fffdf0';bx.fillRect(0,0,w,h);ax.clearRect(0,0,w,h);for(let s=0;s<16;s++){const x=s/16*w,v=t.pattern[s];bx.strokeStyle='#ddd8c6';bx.beginPath();bx.moveTo(x,0);bx.lineTo(x,h);bx.stroke();if(v){const amp=v===2?.8:.48,bars=engineBands(t.engine,t.pitch);for(const [y0,height,alpha] of bars){bx.fillStyle=`rgba(17,18,15,${alpha*amp})`;bx.fillRect(x+3,y0*h,w/16-6,height*h)}}}const mid=h*.68;bx.strokeStyle='#11120f';bx.lineWidth=2;bx.beginPath();for(let x=0;x<w;x++){const st=Math.floor(x/w*16),v=t.pattern[st],ph=(x/w*16-st),wave=Math.sin(ph*Math.PI*2*(2+(t.pitch%7)))*v*.18;bx.lineTo(x,mid+wave*h)}bx.stroke();if(mark.b>mark.a){ax.fillStyle='rgba(234,255,79,.42)';ax.fillRect(mark.a*w,0,(mark.b-mark.a)*w,h)}}
function engineBands(e,p){const y=Math.max(.08,Math.min(.88,1-(p-24)/84));if(e==='kick')return[[.72,.18,.55],[.84,.08,.3]];if(e==='snare'||e==='noise')return[[.15,.72,.2],[.45,.2,.34]];if(e==='bass')return[[.65,.16,.5],[.54,.07,.25]];if(e==='pad')return[[y,.18,.25],[Math.max(0,y-.22),.1,.17]];return[[y,.09,.48],[Math.max(0,y-.13),.05,.2]]}
function point(e){const r=anno.getBoundingClientRect();return{x:(e.clientX-r.left)*anno.width/r.width}}anno.onpointerdown=e=>{drag=true;mark.a=mark.b=point(e).x/anno.width};anno.onpointermove=e=>{if(!drag)return;mark.b=Math.max(0,Math.min(1,point(e).x/anno.width));if(mark.b<mark.a)[mark.a,mark.b]=[mark.b,mark.a];renderMicro()};anno.onpointerup=()=>drag=false;

async function moreTrack(){const t=project.tracks[currentTrack];if(!verified){children=localChildren(t);renderMicro();return}busy(0,'LISTENING TO '+t.name);try{const r=await structured(`You are the ${t.name} player plus its Microscope agent. Produce exactly four orthogonal playable alternatives for this track:\nBODY changes timbre but preserves pattern.\nRHYTHM changes pattern but preserves sonic identity.\nTIMING alters pattern placement/space while retaining motif.\nSTRANGER makes the largest coherent jump.\nThe result must remain useful inside the WHOLE BAND, not become a solo demo.\nBAND:${JSON.stringify({title:project.title,tempo:project.tempo,theory:project.theory,other_tracks:project.tracks.filter((_,i)=>i!==currentTrack).map(x=>({name:x.name,role:x.role,engine:x.engine,pattern:x.pattern}))})}\nTRACK:${JSON.stringify(t)}\nMARKED NORMALIZED REGION:${JSON.stringify(mark)}`,'track_children',MUT4);children=r.children;busy(2,'FOUR PLAYERS ANSWERED');renderMicro();setTimeout(endBusy,150)}catch(e){setState(e.message,'bad');$('#busy').classList.remove('on')}}
function localChildren(t){const copy=()=>JSON.parse(JSON.stringify(t));let a=copy(),b=copy(),c=copy(),d=copy();a.timbre.cutoff=Math.max(150,Math.min(16000,a.timbre.cutoff*(.4+Math.random()*1.7)));a.timbre.drive=Math.min(1,a.timbre.drive+.25);b.pattern=b.pattern.map((v,i)=>i%3===0?(v?0:1):v);c.pattern=c.pattern.map((v,i)=>((i+1)%4===0?v:0)||v);d.pitch=Math.max(24,Math.min(96,d.pitch+(Math.random()<.5?-12:12)));d.pan=-d.pan;d.pattern=d.pattern.map((v,i)=>i%5===0?2:(Math.random()<.22?1:v));return[{axis:'BODY',name:'new body',pitch:a.pitch,gain:a.gain,pan:a.pan,pattern:a.pattern,timbre:a.timbre,why:'same rhythm, altered body'},{axis:'RHYTHM',name:'new rhythm',pitch:b.pitch,gain:b.gain,pan:b.pan,pattern:b.pattern,timbre:b.timbre,why:'same player, different pulse'},{axis:'TIMING',name:'new timing',pitch:c.pitch,gain:c.gain,pan:c.pan,pattern:c.pattern,timbre:c.timbre,why:'more space around motif'},{axis:'STRANGER',name:'far player',pitch:d.pitch,gain:d.gain,pan:d.pan,pattern:d.pattern,timbre:d.timbre,why:'largest coherent jump'}]}
function useChild(i){const c=children[i],t=project.tracks[currentTrack];Object.assign(t,{name:c.name,role:t.role,engine:t.engine,pitch:c.pitch,gain:c.gain,pan:c.pan,pattern:[...c.pattern],timbre:{...c.timbre}});children=[];mark={a:0,b:0};renderMicro();setState('USED IN BAND','good')}
function auditionChild(i){const c=children[i],base=project.tracks[currentTrack],tmp={...base,...c,timbre:{...c.timbre},pattern:[...c.pattern]};playTrack(tmp)}
function makeChildTrack(c){return {...project.tracks[currentTrack],...c,timbre:{...c.timbre},pattern:[...c.pattern]}}

function voice(t,at,dur,accent=1,destination=null){const c=ensureAudio(),dest=destination||c.destination;if(t.engine==='kick'){const o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(150,at);o.frequency.exponentialRampToValueAtTime(42,at+.11);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(t.gain*.8*accent,at+.004);g.gain.exponentialRampToValueAtTime(.0001,at+Math.min(.35,dur));o.connect(g);g.connect(dest);o.start(at);o.stop(at+.4);nodes.push(o,g);return}
 if(t.engine==='snare'||t.engine==='noise'){const b=c.createBuffer(1,Math.floor(c.sampleRate*.3),c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=b;f.type=t.engine==='snare'?'bandpass':'highpass';f.frequency.value=t.timbre.cutoff;g.gain.setValueAtTime(t.gain*.36*accent,at);g.gain.exponentialRampToValueAtTime(.0001,at+Math.min(.28,t.timbre.decay));s.connect(f);f.connect(g);g.connect(dest);s.start(at);s.stop(at+.32);nodes.push(s,f,g);return}
 const o=c.createOscillator(),f=c.createBiquadFilter(),g=c.createGain(),p=c.createStereoPanner?c.createStereoPanner():null;o.type=t.engine==='bass'?'sawtooth':t.engine==='pluck'?'square':'triangle';o.frequency.value=440*Math.pow(2,(t.pitch-69)/12);f.type='lowpass';f.frequency.value=t.timbre.cutoff;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(t.gain*.14*accent,at+t.timbre.attack);g.gain.exponentialRampToValueAtTime(.0001,at+Math.min(dur,t.timbre.decay));o.connect(f);f.connect(g);if(p){p.pan.value=t.pan;g.connect(p);p.connect(dest)}else g.connect(dest);o.start(at);o.stop(at+Math.max(.06,Math.min(dur,t.timbre.decay))+.02);nodes.push(o,f,g,p)}
function stop(){nodes.forEach(n=>{try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}});nodes=[];playing=false;$('#play').textContent='▷'}
function playBand(){if(!project)return;stop();const c=ensureAudio(),step=60/project.tempo/4,base=c.currentTime+.05;project.tracks.forEach(t=>t.pattern.forEach((v,i)=>{if(v)voice(t,base+i*step,step*.9,v===2?1.25:1)}));playing=true;$('#play').textContent='Ⅱ';setTimeout(()=>{if(playing){playing=false;$('#play').textContent='▷'}},step*16*1000+120)}
function playTrack(t){stop();const c=ensureAudio(),step=60/(project?.tempo||90)/4,base=c.currentTime+.05;t.pattern.forEach((v,i)=>{if(v)voice(t,base+i*step,step*.9,v===2?1.25:1)});playing=true;$('#play').textContent='Ⅱ';setTimeout(()=>{if(playing){playing=false;$('#play').textContent='▷'}},step*16*1000+120)}
$('#play').onclick=()=>playing?stop():(screen==='band'?playBand():playTrack(project.tracks[currentTrack]));$('#more').onclick=()=>screen==='band'?arrange():moreTrack();

function openSheet(id){$$('.sheet').forEach(x=>x.classList.remove('on'));$('#'+id).classList.add('on')}$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('on'));
$('#add').onclick=()=>openSheet('addSheet');$('#upload').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const c=ensureAudio();try{sampleBuffer=await c.decodeAudioData((await f.arrayBuffer()).slice(0));setState('SAMPLE LOADED','good');if(screen==='micro'){project.tracks[currentTrack].name=f.name.replace(/\.[^.]+$/,'');project.tracks[currentTrack].engine='noise';renderMicro()}}catch{setState('SAMPLE ERROR','bad')}};
$('#newTrack').onclick=()=>{if(!project)return;project.tracks.push({name:'NEW',role:'new voice',engine:'tone',pitch:60,gain:.5,pan:0,pattern:[1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],timbre:{attack:.01,decay:.25,cutoff:2400,drive:0}});renderBand();$('#addSheet').classList.remove('on')};$('#seedTrack').onclick=()=>{if(screen==='micro'){project.tracks[currentTrack]=localProject('x').tracks[3];renderMicro()}};
$('#clearTrack').onclick=()=>{if(screen==='micro'){project.tracks[currentTrack].pattern.fill(0);renderMicro()}};

$('#ask').onclick=()=>{if(screen==='micro'&&project)openChat('ASK '+project.tracks[currentTrack].name);else openChat('ASK THE BAND')};$('#wholeAsk').onclick=()=>openChat('ASK THE BAND');
function openChat(title){$('#chatTitle').textContent=title;openSheet('chat');renderChat()}function renderChat(){$('#thread').innerHTML=chat.map((m,i)=>`<div class="msg ${m.role==='user'?'me':''}">${esc(m.text)}${m.ops?.length?`<div class="ops">${m.ops.map((o,j)=>`<button data-op="${i}:${j}">${esc(o.label)}</button>`).join('')}</div>`:''}</div>`).join('');$$('[data-op]').forEach(b=>b.onclick=()=>{const [i,j]=b.dataset.op.split(':').map(Number);runOp(chat[i].ops[j])});$('#thread').scrollTop=99999}
function pushMsg(role,text,ops=[]){chat.push({role,text,ops});renderChat()}$('#chatSend').onclick=sendChat;$('#chatInput').onkeydown=e=>{if(e.key==='Enter')sendChat()};
async function sendChat(){const q=$('#chatInput').value.trim();if(!q)return;$('#chatInput').value='';pushMsg('user',q);if(!verified){pushMsg('agent','Connect the API to let the band answer with changes.',[{label:'MORE',action:'MORE'}]);return}try{setState('LISTENING','busy');const context=screen==='band'?JSON.stringify(project):JSON.stringify({band:{title:project.title,tempo:project.tempo,theory:project.theory},track:project.tracks[currentTrack],mark});const r=await structured(`You are attached to ${screen==='band'?'the whole band':'one player inside the band'}. Explain causal musical relationships briefly. Prefer an audible next operation over a lecture.\nCONTEXT:${context}\nQUESTION:${q}`,'band_chat',CHAT);const ops=[{label:r.action==='MICROSCOPE'?'OPEN TRACK':r.action==='REARRANGE'?'REARRANGE':'MORE',action:r.action}];pushMsg('agent',r.answer,ops);setState('READY','good')}catch(e){pushMsg('agent','ERROR: '+e.message);setState('CHAT ERROR','bad')}}
function runOp(o){$('#chat').classList.remove('on');if(o.action==='REARRANGE'||o.action==='MORE')screen==='band'?arrange():moreTrack();if(o.action==='MICROSCOPE'&&project?.tracks.length)openMicro(Math.max(0,currentTrack))}

$('#exportBtn').onclick=()=>{if(!project)return;const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(project.title||'band')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};