'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const API_PROXY='https://lcxykqgddnekrimawpie.supabase.co/functions/v1/openai-proxy';
const SUPABASE_PUBLISHABLE='sb_publishable_bF2QF1eJmzhi4Pj-dxE-0g_mnm6zRSh';
let apiKey='',verified=false,ctx=null,objects=[],currentId='',selection=[],children=[],kept=new Set(),nodes=[],playing=false,mark={a:0,b:0},dragging=false,trace=[],chat=[];
const body=$('#bodyCanvas'),anno=$('#annoCanvas'),bx=body.getContext('2d'),ax=anno.getContext('2d');
function viewport(){document.documentElement.style.setProperty('--app-h',Math.round(window.visualViewport?.height||innerHeight)+'px')}viewport();window.visualViewport?.addEventListener('resize',viewport);window.addEventListener('orientationchange',()=>setTimeout(viewport,80));
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function uid(){return crypto.randomUUID?.()||('o'+Date.now()+Math.random().toString(16).slice(2))}function setState(t,k=''){$('#state').textContent=t;$('#dot').className='dot '+k}function current(){return objects.find(o=>o.id===currentId)||null}function selectedObjects(){return selection.map(id=>objects.find(o=>o.id===id)).filter(Boolean)}function addTrace(from,to,op,data={}){trace.push({time:new Date().toISOString(),from,to,op,data});if(trace.length>600)trace.shift()}function ensureAudio(){ctx=ctx||new(AudioContext||webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}
async function api(path,body=null){const r=await fetch(API_PROXY,{method:'POST',headers:{Authorization:`Bearer ${SUPABASE_PUBLISHABLE}`,apikey:SUPABASE_PUBLISHABLE,'Content-Type':'application/json','x-openai-key':apiKey},body:JSON.stringify({path,method:body?'POST':'GET',body})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error?.message||d?.error||d?.message||String(r.status));return d}function responseText(d){if(d.output_text)return d.output_text;for(const o of d.output||[])for(const c of o.content||[])if(typeof c.text==='string')return c.text;throw new Error('No response')}async function structured(prompt,name,schema,images=[]){const content=[{type:'input_text',text:prompt},...images.flatMap(i=>[{type:'input_text',text:i.label},{type:'input_image',image_url:i.url,detail:'high'}])];const d=await api('/responses',{model:$('#model').value,input:[{role:'user',content}],text:{format:{type:'json_schema',name,schema,strict:true}}});return JSON.parse(responseText(d))}
$('#checkKey').onclick=async()=>{apiKey=$('#apiKey').value.trim();if(!apiKey)return $('#gateState').textContent='ENTER KEY';$('#gateState').textContent='CHECKING';try{await api('/models');verified=true;$('#gate').classList.add('hidden');setState('READY','good')}catch(e){$('#gateState').textContent=e.message}};
function analyze(buf){if(!buf)return{duration:0,rms:0,zcr:0,density:0,brightness:0};const d=buf.getChannelData(0),step=Math.max(1,Math.floor(d.length/22000));let sum=0,z=0,p=0,a=0,h=0,n=0;for(let i=0;i<d.length;i+=step){const v=d[i];sum+=v*v;if(Math.abs(v)>.03)a++;if(n&&Math.sign(v)!==Math.sign(p))z++;h+=Math.abs(v-p);p=v;n++}return{duration:+buf.duration.toFixed(3),rms:+Math.sqrt(sum/n).toFixed(4),zcr:+(z/n).toFixed(4),density:+(a/n).toFixed(4),brightness:+(h/n).toFixed(4)}}function makeObj(name,buffer,parents=[],recipe={},why='',kind='sound',axis='SOURCE'){return{id:uid(),name:name||'untitled',buffer,parents:[...parents],recipe:{...recipe},why,kind,axis,created:Date.now(),features:analyze(buffer)}}
async function loadFiles(files){const audio=[...files].filter(f=>f.type.startsWith('audio/'));if(!audio.length)return;const c=ensureAudio();for(const f of audio){try{const ab=await f.arrayBuffer(),buf=await c.decodeAudioData(ab.slice(0)),o=makeObj(f.name.replace(/\.[^.]+$/,''),buf,[],{source:'file'},'uploaded sample');objects.push(o);currentId=o.id;selection=[];addTrace('external',o.id,'UPLOAD',{name:f.name})}catch(e){setState('COULD NOT READ '+f.name,'bad')}}children=[];mark={a:0,b:0};render()}document.addEventListener('dragover',e=>{e.preventDefault();setState('DROP TO ADD','busy')});document.addEventListener('drop',e=>{e.preventDefault();loadFiles(e.dataTransfer.files);setState('READY','good')});
async function seed(){const c=ensureAudio(),sr=44100,dur=3.5,b=c.createBuffer(1,sr*dur,sr),d=b.getChannelData(0),f=42+Math.random()*130,pulse=2+Math.floor(Math.random()*7);for(let i=0;i<d.length;i++){const t=i/sr,g=Math.sin(t*Math.PI*2*pulse)>.15?1:.13;d[i]=(Math.sin(t*f*Math.PI*2)+.32*Math.sin(t*f*1.49*Math.PI*2))*g*.18+(Math.random()*2-1)*.013}const o=makeObj('seed '+Math.floor(f),b,[],{source:'seed',frequency:+f.toFixed(2),pulse},'local synthetic seed');objects.push(o);currentId=o.id;selection=[];children=[];addTrace('local',o.id,'SEED',o.recipe);render()}$('#seedBtn').onclick=seed;$('#recordBtn').onclick=()=>{closeSheets();seed()};
function drawObject(){const o=current(),w=body.width,h=body.height;bx.fillStyle='#fffdf0';bx.fillRect(0,0,w,h);ax.clearRect(0,0,w,h);if(!o?.buffer){$('#dropHint').classList.remove('hidden');return}$('#dropHint').classList.add('hidden');const d=o.buffer.getChannelData(0),mid=h*.52,cols=95,bins=28,win=56;for(let cx=0;cx<cols;cx++){const center=Math.floor(cx/(cols-1)*(d.length-win-1));for(let k=1;k<bins;k++){let re=0,im=0,fr=k/bins*Math.PI;for(let j=0;j<win;j++){const v=d[center+j]||0,ph=fr*j;re+=v*Math.cos(ph);im-=v*Math.sin(ph)}const mag=Math.min(1,Math.sqrt(re*re+im*im)/8);if(mag>.03){bx.fillStyle=`rgba(17,18,15,${mag*.22})`;bx.fillRect(cx/cols*w,h-(k/bins*h),w/cols+1,h/bins+1)}}}bx.strokeStyle='#11120f';bx.lineWidth=2;bx.beginPath();for(let x=0;x<w;x++){const a=Math.floor(x/w*d.length),b=Math.min(d.length,Math.floor((x+1)/w*d.length));let mn=1,mx=-1;for(let i=a;i<b;i++){if(d[i]<mn)mn=d[i];if(d[i]>mx)mx=d[i]}bx.moveTo(x,mid+mn*h*.32);bx.lineTo(x,mid+mx*h*.32)}bx.stroke();bx.strokeStyle='rgba(17,18,15,.25)';bx.beginPath();bx.moveTo(0,mid);bx.lineTo(w,mid);bx.stroke();if(mark.b>mark.a){ax.fillStyle='rgba(233,255,79,.44)';ax.fillRect(mark.a*w,0,(mark.b-mark.a)*w,h);ax.strokeStyle='#11120f';ax.lineWidth=2;ax.strokeRect(mark.a*w,0,(mark.b-mark.a)*w,h);$('#markLabel').style.display='block'}else $('#markLabel').style.display='none'}
function render(){const o=current(),sel=selectedObjects();$('#objectName').textContent=sel.length>1?sel.map(x=>x.name).join(' + '):(o?.name||'NO SOUND');$('#objectKind').textContent=sel.length>1?'RELATIONSHIP':'SOUND';$('#objectMeta').textContent=sel.length>1?`${sel.length} sounds selected`:o?`${o.features.duration}s · ${o.parents.length}P`:'0 parents';drawObject();renderCause();renderChildren();renderSelection()}
function renderCause(){const o=current(),box=$('#cause');box.innerHTML='<div class="causeLabel">CAUSE</div>';if(!o)return;const genes=[];for(const [k,v] of Object.entries(o.recipe||{})){if(typeof v==='object'||['source','groove'].includes(k))continue;genes.push([k,v])}if(!genes.length)genes.push(['source',o.kind]);box.innerHTML+=genes.slice(0,12).map(([k,v])=>`<div class="gene changed">${esc(k)} ${esc(v)}</div>`).join('')}
function renderChildren(){$('#cards').innerHTML=children.slice(0,4).map(c=>`<button class="child ${c.id===currentId?'on':''} ${kept.has(c.id)?'kept':''}" data-id="${c.id}"><div><div class="axisName">${esc(c.axis)}</div><div class="name">${esc(c.name)}</div></div><div class="why">${esc(c.why)}</div><div class="mini">${c.features.duration}s · ${c.parents.length}P</div></button>`).join('')||['BODY','RHYTHM','TIMING','STRANGER'].map(a=>`<div class="child"><div class="axisName">${a}</div><div class="why">press MORE</div></div>`).join('');$$('.child[data-id]').forEach(bindChild)}
function bindChild(el){let timer=null,long=false,id=el.dataset.id;el.onpointerdown=()=>{long=false;timer=setTimeout(()=>{long=true;if(kept.has(id))kept.delete(id);else kept.add(id);if(!selection.includes(id)){if(selection.length>=4)selection.shift();selection.push(id)}render()},520)};el.onpointerup=()=>{clearTimeout(timer);if(!long){currentId=id;mark={a:0,b:0};render();playObject(current())}};el.onpointercancel=()=>clearTimeout(timer)}
function renderSelection(){const bar=$('#selection'),sel=selectedObjects();if(!sel.length){bar.classList.remove('on');return}bar.classList.add('on');bar.textContent=sel.length===1?`SELECTED: ${sel[0].name}`:`RELATIONSHIP: ${sel.map(s=>s.name).join(' + ')}`}
