function currentTheoryText(){if(!orchestration?.theory)return'(none)';return orchestration.theory.rules.map((r,i)=>`${i+1}. ${r.from_feature} ${r.operation} ${r.to_feature}`).join('\n')}
function currentFeedback(){return spectrumDirty?'The learner has drawn corrections directly on the spectrum.':programSong?'Revise from the current song while preserving useful motifs.':'First build.'}
async function runOrchestration(){if(!verified)return;const words=$('#wordInput').value.trim();if(!words&&!sketchDirty&&!programSong){setState('ADD WORD OR SKETCH','bad');return}resetAgentStates();busy(true,'READ',10);$('#makeBtn').disabled=true;const images=[];if(sketchDirty)images.push({label:'CURRENT SKETCH',url:canvasURL(sketch)});if(spectrumDirty)images.push({label:'MARKED SPECTRUM',url:canvasURL(spectrumInk,spectrumBase)});try{
  agentState('source','active');const sourcePrompt=`You are SOURCE AGENT in a learning instrument. Read only the learner's evidence. Do not compose yet. Identify concrete features that could become musical handles. Keep language short and contestable.\nWORDS:\n${words||'(none)'}\nFEEDBACK:\n${currentFeedback()}`;const source=await structured(imageContent(sourcePrompt,images),'source_reading',SOURCE_SCHEMA);agentState('source','done');panelReady('word');if(sketchDirty)panelReady('sketch');recordFlow(words?'word':'sketch','source-agent','READ');busy(true,'READ · '+String(source.evidence?.[0]?.observation||source.reading).slice(0,58),28);
  agentState('theory','active');const theoryPrompt=`You are THEORY AGENT. Build an explicit translation theory between the source and music. Rules are hypotheses, not truths. Exactly five rules. Each rule must say a source feature, an operation such as maps-to / repeats-as / inverts-to / gates / stretches, and a musical consequence. Also design A1/B/A2 functions.\nSOURCE JSON:\n${JSON.stringify(source)}\nEXISTING THEORY THE LEARNER MAY HAVE CHANGED:\n${currentTheoryText()}\nSTEPPING STONES SAVED:\n${JSON.stringify(loadStones())}`;const theory=await structured([{type:'input_text',text:theoryPrompt}],'translation_theory',THEORY_SCHEMA);agentState('theory','done');orchestration={...(orchestration||{}),source,theory};renderTheory();panelReady('theory');recordFlow('source-agent','theory-agent','MAP');busy(true,'MAP · '+String(theory.rules?.[0]?.from_feature||'source')+' → '+String(theory.rules?.[0]?.to_feature||'music'),52);
  agentState('code','active');const codePrompt=`You are CODE AGENT. Turn this explicit theory into one playable 12-bar A1/B/A2 song specification. A1, B, A2 are exactly four 4/4 bars each. Use 2-4 tracks. Make motifs strong enough that edits are audible. Do not imitate a copyrighted melody.\nSOURCE:\n${JSON.stringify(source)}\nTHEORY:\n${JSON.stringify(theory)}\nPREVIOUS SONG IF REVISING:\n${programSong?JSON.stringify(programSong):'(none)'}\nMARKED SPECTRUM PRESENT: ${spectrumDirty?'yes':'no'}`;const songSpec=await structured([{type:'input_text',text:codePrompt}],'playable_song',SONG_SCHEMA);agentState('code','done');$('#codeEditor').value=serializeSong(songSpec);updateGutter();programSong=parseProgram($('#codeEditor').value);panelReady('code');panelReady('song');renderSong();renderSpectrum();$('#transportTitle').textContent=programSong.title;recordFlow('theory-agent','code-agent','WRITE');recordFlow('code','song','RUN');busy(true,'CODE · '+allEvents().length+' EVENTS',76);
  agentState('listener','active');const listenPrompt=`You are LISTENER AGENT. Inspect this song specification against the learner's translation theory. Do not praise it. State what the current structure is doing, 1-4 productive tensions, and one question that could open a different branch rather than merely improve the song.\nTHEORY:\n${JSON.stringify(theory)}\nSONG:\n${JSON.stringify(programSong)}`;const listener=await structured([{type:'input_text',text:listenPrompt}],'listener_reading',LISTENER_SCHEMA);agentState('listener','done');orchestration={source,theory,listener};recordFlow('song','listener-agent','HEAR');recordFlow('listener-agent','history','LEAVE TRACE');busy(true,'LISTEN · '+String(listener.next_question||'branch').slice(0,58),100);panelReady('spectrum');saveSnapshot();sketchDirty=false;spectrumDirty=false;$$('.panel.changed').forEach(p=>p.classList.remove('changed'));setState('READY','good');setTimeout(()=>busy(false),240)
}catch(e){setState(e.message,'bad');busy(false);const active=$$('#buildPath button.active')[0];if(active)active.className='fail'}finally{updateMake()}}
$('#makeBtn').onclick=runOrchestration;

function renderTheory(){const box=$('#theoryRules');const rules=orchestration?.theory?.rules||[];if(!rules.length){box.innerHTML='<div class="emptyTheory">MAKE A SONG.<br>THE RULES APPEAR HERE.</div>';return}box.innerHTML=rules.map((r,i)=>`<div class="rule ${i===selectedRule?'selected':''}" data-rule="${i}" title="${esc(r.rationale)}"><span class="rFrom" contenteditable="true" data-field="from_feature">${esc(r.from_feature)}</span><span class="arrow">→</span><span class="rTo" contenteditable="true" data-field="to_feature">${esc(r.to_feature)}</span><span class="conf">${Math.round(r.confidence*100)}</span></div>`).join('');$$('.rule').forEach(el=>{el.onclick=e=>{selectedRule=Number(el.dataset.rule);renderTheory();activePanel='theory'};el.querySelectorAll('[contenteditable]').forEach(ed=>{ed.onblur=()=>{const i=Number(el.dataset.rule),f=ed.dataset.field;orchestration.theory.rules[i][f]=ed.textContent.trim();panelChanged('theory');recordFlow('theory','theory','REWIRE')}})})}
function loadStones(){try{return JSON.parse(localStorage.getItem('sketchsong_orchestrator_stones')||'[]')}catch{return[]}}
$('#stoneBtn').onclick=()=>{if(selectedRule<0||!orchestration?.theory)return;const stones=loadStones(),r=orchestration.theory.rules[selectedRule];stones.push({...r,savedAt:new Date().toISOString()});localStorage.setItem('sketchsong_orchestrator_stones',JSON.stringify(stones.slice(-30)));setState('RULE KEPT','good');recordFlow('theory','stones','KEEP')};

function panelContext(id){switch(id){case'word':return`WORDS:\n${$('#wordInput').value.trim()||'(empty)'}\nSOURCE READING:\n${JSON.stringify(orchestration?.source||{})}`;case'sketch':return`SKETCH is a learner-authored drawing. Current translation theory:\n${currentTheoryText()}`;case'theory':return`TRANSLATION THEORY:\n${JSON.stringify(orchestration?.theory||{})}\nSELECTED RULE: ${selectedRule>=0?JSON.stringify(orchestration.theory.rules[selectedRule]):'(none)'}`;case'code':{const ta=$('#codeEditor'),sel=ta.value.slice(ta.selectionStart,ta.selectionEnd);const line=ta.value.slice(0,ta.selectionStart).split('\n').length;return`PLAYABLE SKETCHSONG CODE. This code is canonical: RUN compiles it directly to sound.\nCURSOR LINE: ${line}\nSELECTED: ${sel||'(none)'}\nPROGRAM:\n${ta.value}`}case'song':return`SONG SPEC:\n${JSON.stringify(programSong||{})}\nLISTENER:\n${JSON.stringify(orchestration?.listener||{})}`;case'spectrum':return`This panel is a time/frequency projection of the current program. Learner marks are feedback. Marked: ${spectrumDirty?'yes':'no'}.\nTHEORY:\n${currentTheoryText()}`;default:return''}}
function agentRole(id){return({word:'SOURCE AGENT',sketch:'SKETCH AGENT',theory:'THEORY AGENT',code:'CODE AGENT',song:'LISTENER AGENT',spectrum:'SPECTRUM AGENT'})[id]||'AGENT'}
function openChat(id,contextLabel=''){activePanel=id;$('#chatDock').classList.add('on');$('#chatDock').setAttribute('aria-hidden','false');$('#chatTitle').textContent=agentRole(id);$('#chatContext').textContent=contextLabel||id.toUpperCase();renderChat();recordFlow(id,`${id}-chat`,'ASK')}
function renderChat(){const th=$('#chatThread');th.innerHTML=chats[activePanel].map((m,i)=>`<div class="msg ${m.role}">${esc(m.text)}${m.program?`<br><button class="applyPatch" data-msg="${i}">APPLY PROGRAM</button>`:''}</div>`).join('');th.scrollTop=th.scrollHeight;$$('.applyPatch').forEach(b=>b.onclick=()=>{const m=chats[activePanel][Number(b.dataset.msg)];if(m.program){$('#codeEditor').value=m.program;updateGutter();panelChanged('code');$('#codeStatus').textContent='AGENT PATCH / PRESS RUN';$('#codeStatus').className='codeStatus';closeChat();focusPanel('code');recordFlow('code-chat','code','PATCH')}})}
function closeChat(){$('#chatDock').classList.remove('on');$('#chatDock').setAttribute('aria-hidden','true');chatImageData='';$('#chatDrop').classList.remove('has');$('#chatImage').src=''}
$$('[data-chat]').forEach(b=>b.onclick=()=>openChat(b.dataset.chat));$('#chatClose').onclick=closeChat;
const quickText={why:'Explain the causal relation here in plain language. Point to the smallest thing I can inspect.',show:'Show me one concrete correspondence between this panel and another panel.',change:'Propose one reversible change that teaches me what controls what. If this is CODE, return the complete replacement program in replacement_program.',try:'Give me one small experiment whose result I should predict before running it.'};$$('[data-quick]').forEach(b=>b.onclick=()=>sendChat(quickText[b.dataset.quick]));
async function sendChat(textOverride=''){const text=(textOverride||$('#chatInput').value.trim());if(!text)return;$('#chatInput').value='';chats[activePanel].push({role:'user',text});renderChat();const role=agentRole(activePanel),ctx=panelContext(activePanel),images=[];if(activePanel==='sketch')images.push({label:'SKETCH',url:canvasURL(sketch)});if(activePanel==='spectrum')images.push({label:'SPECTRUM WITH MARKS',url:canvasURL(spectrumInk,spectrumBase)});if(chatImageData)images.push({label:'IMAGE DROPPED INTO CHAT',url:chatImageData});try{setState(role+' THINKING','busy');const prompt=`You are ${role} inside a learning-oriented music programming instrument. The learner can ask any panel what is happening. Explain causal structure, not hidden chain-of-thought. Prefer one concrete relation over a lecture. Treat code as an editable instrument. When asked to change CODE, replacement_program may contain a complete valid Sketchsong program using only TITLE, TEMPO, METER, SECTION, TRACK, NOTE. Otherwise replacement_program must be empty.\n\nPANEL CONTEXT:\n${ctx}\n\nLEARNER:\n${text}`;const r=await structured(imageContent(prompt,images),'panel_chat',CHAT_SCHEMA);chats[activePanel].push({role:'agent',text:r.answer,program:r.replacement_program||''});renderChat();recordFlow(`${activePanel}-chat`,activePanel,r.replacement_program?'PROPOSE PATCH':'EXPLAIN');setState('READY','good')}catch(e){chats[activePanel].push({role:'agent',text:'ERROR: '+e.message});renderChat();setState('CHAT ERROR','bad')}}
$('#chatSend').onclick=()=>sendChat();$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();sendChat()}});
function acceptChatImage(file){if(!file||!file.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{chatImageData=r.result;$('#chatImage').src=r.result;$('#chatDrop').classList.add('on','has')};r.readAsDataURL(file)}
$('#chatDock').addEventListener('dragover',e=>{e.preventDefault();$('#chatDrop').classList.add('on')});$('#chatDock').addEventListener('dragleave',e=>{if(!$('#chatDock').contains(e.relatedTarget))$('#chatDrop').classList.remove('on')});$('#chatDock').addEventListener('drop',e=>{e.preventDefault();acceptChatImage(e.dataTransfer.files?.[0])});document.addEventListener('paste',e=>{if(!$('#chatDock').classList.contains('on'))return;const f=[...(e.clipboardData?.files||[])].find(x=>x.type.startsWith('image/'));if(f)acceptChatImage(f)});
