function recordFlow(from,to,label){flowEvents.push({from,to,label,branch:branchId,time:Date.now()});renderFlow();}
function saveSnapshot(){snapshots.push({branch:branchId,time:new Date().toISOString(),word:$('#wordInput').value,program:$('#codeEditor').value,theory:orchestration?.theory||null,source:orchestration?.source||null,listener:orchestration?.listener||null,flow:[...flowEvents]});if(snapshots.length>50)snapshots.shift();try{localStorage.setItem('sketchsong_orchestrator_history',JSON.stringify(snapshots.slice(-20)))}catch{}}
const nodePos={word:[110,130],sketch:[110,300],'source-agent':[340,210],theory:[565,120],'theory-agent':[565,280],code:[800,120],'code-agent':[800,280],song:[1030,130],'listener-agent':[1030,310],spectrum:[1030,500],history:[800,580],stones:[565,580],'word-chat':[220,70],'sketch-chat':[220,390],'theory-chat':[565,40],'code-chat':[800,40],'song-chat':[1080,55],'spectrum-chat':[1080,590],external:[35,300]};
function renderFlow(){const svg=$('#flowSvg');$('#flowCount').textContent=`${flowEvents.length} TRANSFORMS`;const used=new Set();flowEvents.forEach(e=>{used.add(e.from);used.add(e.to)});let edges='',nodes='';for(const e of flowEvents){const a=nodePos[e.from]||[80,650],b=nodePos[e.to]||[1120,650];const mx=(a[0]+b[0])/2,my=(a[1]+b[1])/2;edges+=`<path class="flowEdge ${e.branch?'branch':''}" d="M${a[0]} ${a[1]} C${mx} ${a[1]},${mx} ${b[1]},${b[0]} ${b[1]}"/><text class="flowEdgeLabel" x="${mx}" y="${my-4}">${esc(e.label)}</text>`}for(const id of used){const p=nodePos[id]||[600,650],agent=id.includes('agent')||id.includes('chat');nodes+=`<g class="flowNode ${agent?'agent':''}" transform="translate(${p[0]-52},${p[1]-15})"><rect width="104" height="30"/><text x="52" y="19" text-anchor="middle">${esc(id.toUpperCase())}</text></g>`}svg.innerHTML=edges+nodes}
$('#flowBtn').onclick=()=>{$('#flowOverlay').classList.add('on');$('#flowOverlay').setAttribute('aria-hidden','false');renderFlow()};$('#flowClose').onclick=()=>{$('#flowOverlay').classList.remove('on');$('#flowOverlay').setAttribute('aria-hidden','true')};$('#flowBranch').onclick=()=>{branchId++;recordFlow('history','source-agent','BRANCH '+branchId);saveSnapshot();setState('BRANCH '+branchId,'good')};$('#flowExport').onclick=()=>downloadJSON('sketchsong-trace.json',{version:1,branch:branchId,events:flowEvents,snapshots});

function focusPanel(id){const p=$('#'+id+'Panel');if(document.body.classList.contains('focusMode')&&p.classList.contains('focusedPanel')){document.body.classList.remove('focusMode');p.classList.remove('focusedPanel');return}$$('.focusedPanel').forEach(x=>x.classList.remove('focusedPanel'));document.body.classList.add('focusMode');p.classList.add('focusedPanel');activePanel=id}
$$('[data-focus]').forEach(b=>b.onclick=()=>focusPanel(b.dataset.focus));$('#chatFocus').onclick=()=>{closeChat();focusPanel(activePanel)};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeChat();$('#flowOverlay').classList.remove('on');document.body.classList.remove('focusMode');$$('.focusedPanel').forEach(x=>x.classList.remove('focusedPanel'))}});

function installResize(){const ws=$('#workspace');$$('[data-col-resizer]').forEach(r=>r.addEventListener('pointerdown',e=>{if(innerWidth<=820)return;e.preventDefault();r.setPointerCapture(e.pointerId);const type=r.dataset.colResizer;const move=ev=>{const rect=ws.getBoundingClientRect(),x=ev.clientX-rect.left;if(type==='left'){document.documentElement.style.setProperty('--left',Math.max(220,Math.min(x-3,rect.width-520))+'px')}else{const left=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--left'))||rect.width*.31;document.documentElement.style.setProperty('--mid',Math.max(250,Math.min(x-left-9,rect.width-left-260))+'px')}};const up=()=>{r.removeEventListener('pointermove',move);r.removeEventListener('pointerup',up)};r.addEventListener('pointermove',move);r.addEventListener('pointerup',up)}));$$('[data-row-resizer]').forEach(r=>r.addEventListener('pointerdown',e=>{e.preventDefault();const col=r.closest('.column'),rect=col.getBoundingClientRect();r.setPointerCapture(e.pointerId);const move=ev=>{const y=ev.clientY-rect.top;const pct=Math.max(24,Math.min(76,y/rect.height*100));col.style.setProperty('--split',pct+'%')};const up=()=>{r.removeEventListener('pointermove',move);r.removeEventListener('pointerup',up)};r.addEventListener('pointermove',move);r.addEventListener('pointerup',up)}))}
installResize();
$('#mobileRail').addEventListener('click',e=>{const b=e.target.closest('[data-mobile]');if(!b)return;const cols={from:0,through:1,to:2},w=$('#workspace').clientWidth;$('#workspace').scrollTo({left:cols[b.dataset.mobile]*w,behavior:'smooth'});$$('#mobileRail button').forEach(x=>x.classList.toggle('on',x===b))});$('#workspace').addEventListener('scroll',()=>{if(innerWidth>820)return;const i=Math.round($('#workspace').scrollLeft/$('#workspace').clientWidth);$$('#mobileRail button').forEach((b,j)=>b.classList.toggle('on',j===i))});

$('#settingsBtn').onclick=()=>$('#settings').classList.toggle('on');$('#recheck').onclick=()=>{syncModels();$('#gate').classList.remove('hidden');$('#keyInput').value=apiKey;gateState('CHECK AGAIN','');};$('#newBtn').onclick=()=>{if(!confirm('Start a new branch from an empty surface?'))return;stopAudio();$('#wordInput').value='';sk.clearRect(0,0,sketch.width,sketch.height);spi.clearRect(0,0,spectrumInk.width,spectrumInk.height);spb.clearRect(0,0,spectrumBase.width,spectrumBase.height);$('#codeEditor').value='# MAKE A SONG TO BUILD PLAYABLE CODE';updateGutter();orchestration=null;programSong=null;selectedRule=-1;renderTheory();renderSong();branchId++;recordFlow('history','word','NEW BRANCH');updateMake();setState('EMPTY BRANCH','good')};

function downloadBlob(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
function downloadJSON(name,obj){downloadBlob(name,new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}))}
$('#exportBtn').onclick=e=>{const m=$('#exportMenu');m.style.right=(innerWidth-e.clientX+4)+'px';m.classList.toggle('on');m.setAttribute('aria-hidden',m.classList.contains('on')?'false':'true')};
$$('[data-export]').forEach(b=>b.onclick=async()=>{const k=b.dataset.export;$('#exportMenu').classList.remove('on');if(k==='json')downloadJSON('sketchsong-song.json',programSong||{});if(k==='code')downloadBlob('sketchsong.score.txt',new Blob([$('#codeEditor').value],{type:'text/plain'}));if(k==='trace')downloadJSON('sketchsong-trace.json',{orchestration,flowEvents,snapshots,program:$('#codeEditor').value});if(k==='html')exportPlayableHTML();if(k==='wav')await exportWav()});
function exportPlayableHTML(){if(!programSong)return;const payload=JSON.stringify({song:programSong,program:$('#codeEditor').value,theory:orchestration?.theory||null,source:orchestration?.source||null,flow:flowEvents});const html=`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(programSong.title)}</title><style>body{font-family:ui-monospace,monospace;background:#fffef3;color:#0b0c0b;margin:0;padding:24px}button{font:inherit;border:2px solid #111;background:#fff;padding:12px 18px}pre{white-space:pre-wrap;border-top:1px solid #111;padding-top:14px}</style><h1>${esc(programSong.title)}</h1><button id=p>PLAY</button><pre>${esc($('#codeEditor').value)}</pre><script>const D=${payload};function m(p){let a={C:0,D:2,E:4,F:5,G:7,A:9,B:11},x=p.match(/^([A-G])([#b]?)([0-8])$/);return(+x[3]+1)*12+a[x[1]]+(x[2]=='#'?1:x[2]=='b'?-1:0)};document.querySelector('#p').onclick=()=>{let c=new AudioContext(),b=c.currentTime+.05,s=60/D.song.tempo;D.song.sections.forEach((q,si)=>q.tracks.forEach(t=>t.notes.forEach(n=>{let o=c.createOscillator(),g=c.createGain(),z=b+(si*16+n.offset)*s,d=n.duration*s;o.frequency.value=440*Math.pow(2,(m(n.pitch)-69)/12);o.type='triangle';g.gain.setValueAtTime(.0001,z);g.gain.exponentialRampToValueAtTime(.1,z+.01);g.gain.exponentialRampToValueAtTime(.0001,z+d);o.connect(g);g.connect(c.destination);o.start(z);o.stop(z+d+.02)})))}</script>`;downloadBlob('sketchsong-playable.html',new Blob([html],{type:'text/html'}))}
async function renderOffline(){if(!programSong)throw new Error('No song');const sr=44100,dur=48*60/programSong.tempo+.5,ctx=new OfflineAudioContext(2,Math.ceil(sr*dur),sr),s=60/programSong.tempo;for(const e of allEvents()){const o=ctx.createOscillator(),g=ctx.createGain(),t=e.globalBeat*s,d=Math.max(.04,e.duration*s);o.frequency.value=hz(e.pitch);o.type=voiceType(e.program);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.003,e.velocity/127*.13),t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(ctx.destination);o.start(t);o.stop(t+d+.02)}return await ctx.startRendering()}
function wavFromBuffer(buf){const n=buf.length,ch=buf.numberOfChannels,ab=new ArrayBuffer(44+n*ch*2),v=new DataView(ab);let p=0;const str=s=>{for(const c of s)v.setUint8(p++,c.charCodeAt(0))},u16=x=>{v.setUint16(p,x,true);p+=2},u32=x=>{v.setUint32(p,x,true);p+=4};str('RIFF');u32(36+n*ch*2);str('WAVE');str('fmt ');u32(16);u16(1);u16(ch);u32(buf.sampleRate);u32(buf.sampleRate*ch*2);u16(ch*2);u16(16);str('data');u32(n*ch*2);const data=Array.from({length:ch},(_,i)=>buf.getChannelData(i));for(let i=0;i<n;i++)for(let c=0;c<ch;c++){let s=Math.max(-1,Math.min(1,data[c][i]));v.setInt16(p,s<0?s*32768:s*32767,true);p+=2}return new Blob([ab],{type:'audio/wav'})}
async function exportWav(){if(!programSong)return;try{setState('RENDER WAV','busy');const b=await renderOffline();downloadBlob((programSong.title||'sketchsong').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.wav',wavFromBuffer(b));setState('READY','good')}catch(e){setState(e.message,'bad')}}

function fitCanvases(){renderSong();renderSpectrum()}window.addEventListener('resize',fitCanvases);updateGutter();renderSong();renderSpectrum();renderFlow();updateMake();

$$('[data-agent]').forEach(b=>b.onclick=()=>{const map={source:'word',theory:'theory',code:'code',listener:'song'};openChat(map[b.dataset.agent]||'code',b.dataset.agent.toUpperCase()+' AGENT')});
