function pointFor(e,canvas){const r=canvas.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:(t.clientX-r.left)*canvas.width/r.width,y:(t.clientY-r.top)*canvas.height/r.height}}
function drawStart(e,canvas,ctx,kind){e.preventDefault();lastPt=pointFor(e,canvas);if(kind==='sketch')drawingSketch=true;else drawingSpectrum=true}
function drawMove(e,canvas,ctx,kind){const on=kind==='sketch'?drawingSketch:drawingSpectrum;if(!on)return;e.preventDefault();const p=pointFor(e,canvas);ctx.strokeStyle=kind==='sketch'?'#0b0c0b':'#ff4d25';ctx.lineWidth=kind==='sketch'?5:6;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(lastPt.x,lastPt.y);ctx.lineTo(p.x,p.y);ctx.stroke();lastPt=p;if(kind==='sketch'){sketchDirty=true;panelChanged('sketch');}else{spectrumDirty=true;panelChanged('spectrum')}updateMake()}
function drawEnd(){drawingSketch=false;drawingSpectrum=false;lastPt=null}
for(const [canvas,ctx,kind] of [[sketch,sk,'sketch'],[spectrumInk,spi,'spectrum']]){canvas.addEventListener('pointerdown',e=>drawStart(e,canvas,ctx,kind));canvas.addEventListener('pointermove',e=>drawMove(e,canvas,ctx,kind));canvas.addEventListener('pointerup',drawEnd);canvas.addEventListener('pointerleave',drawEnd)}
$('#clearSketch').onclick=()=>{sk.clearRect(0,0,sketch.width,sketch.height);sketchDirty=false;panelChanged('sketch',false);updateMake()};$('#clearSpectrum').onclick=()=>{spi.clearRect(0,0,spectrumInk.width,spectrumInk.height);spectrumDirty=false;panelChanged('spectrum',false);updateMake()};$('#uploadSketch').onclick=()=>$('#sketchFile').click();
$('#sketchFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{sk.clearRect(0,0,sketch.width,sketch.height);const s=Math.min(sketch.width/im.width,sketch.height/im.height),w=im.width*s,h=im.height*s;sk.drawImage(im,(sketch.width-w)/2,(sketch.height-h)/2,w,h);sketchDirty=true;panelChanged('sketch');recordFlow('external','sketch','UPLOAD');updateMake()};im.src=r.result};r.readAsDataURL(f)};
$('#wordInput').addEventListener('input',()=>{panelChanged('word');updateMake()});

function noteMidi(p){const m=p.match(/^([A-G])([#b]?)([0-8])$/);if(!m)throw new Error('Bad pitch '+p);const base={C:0,D:2,E:4,F:5,G:7,A:9,B:11}[m[1]]+(m[2]==='#'?1:m[2]==='b'?-1:0);return (Number(m[3])+1)*12+base}
function midiPitch(n){const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];return names[n%12]+(Math.floor(n/12)-1)}
function serializeSong(s){const out=[`TITLE ${JSON.stringify(s.title)}`,`TEMPO ${s.tempo}`,`METER ${s.meter}`];for(const sec of s.sections){out.push('',`SECTION ${sec.name}`);for(const t of sec.tracks){out.push(`TRACK ${JSON.stringify(t.name)} ${t.program}`);for(const n of t.notes)out.push(`NOTE ${n.pitch} ${trimNum(n.offset)} ${trimNum(n.duration)} ${n.velocity}`)}}return out.join('\n')}
function trimNum(n){return Number(n).toFixed(3).replace(/\.000$/,'').replace(/(\.\d*?)0+$/,'$1')}
function parseProgram(text){const lines=text.split(/\r?\n/);const s={title:'UNTITLED',tempo:90,meter:'4/4',sections:[]};let sec=null,track=null;for(let i=0;i<lines.length;i++){const raw=lines[i],line=raw.trim();if(!line||line.startsWith('#'))continue;let m;if(m=line.match(/^TITLE\s+(.+)$/)){try{s.title=JSON.parse(m[1])}catch{s.title=m[1]};continue}if(m=line.match(/^TEMPO\s+(\d+(?:\.\d+)?)$/)){s.tempo=Number(m[1]);if(s.tempo<40||s.tempo>220)throw programError(i+1,'TEMPO 40–220');continue}if(m=line.match(/^METER\s+(.+)$/)){s.meter=m[1];continue}if(m=line.match(/^SECTION\s+(A1|B|A2)$/)){sec={name:m[1],tracks:[]};s.sections.push(sec);track=null;continue}if(m=line.match(/^TRACK\s+("(?:[^"\\]|\\.)*"|\S+)\s+(\d+)$/)){if(!sec)throw programError(i+1,'TRACK needs SECTION');let name;try{name=JSON.parse(m[1])}catch{name=m[1]};track={name,program:Number(m[2]),notes:[]};sec.tracks.push(track);continue}if(m=line.match(/^NOTE\s+([A-G][#b]?[0-8])\s+(-?\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)\s+(\d+)$/)){if(!track)throw programError(i+1,'NOTE needs TRACK');const n={pitch:m[1],offset:Number(m[2]),duration:Number(m[3]),velocity:Number(m[4]),sourceLine:i+1};if(n.offset<0||n.offset>=16)throw programError(i+1,'NOTE offset 0–15.99');if(n.duration<=0||n.duration>8)throw programError(i+1,'NOTE duration 0–8');if(n.velocity<1||n.velocity>127)throw programError(i+1,'velocity 1–127');track.notes.push(n);continue}throw programError(i+1,'Unknown instruction: '+line)}if(s.sections.length!==3||s.sections.map(x=>x.name).join(',')!=='A1,B,A2')throw new Error('Program needs SECTION A1, SECTION B, SECTION A2');return s}
function programError(line,msg){const e=new Error(`LINE ${line}: ${msg}`);e.line=line;return e}
function updateGutter(){const n=$('#codeEditor').value.split('\n').length;$('#codeGutter').textContent=Array.from({length:n},(_,i)=>i+1).join('\n')}
$('#codeEditor').addEventListener('input',()=>{updateGutter();panelChanged('code');$('#codeStatus').textContent='CHANGED / PRESS RUN';$('#codeStatus').className='codeStatus';});$('#codeEditor').addEventListener('scroll',()=>{$('#codeGutter').scrollTop=$('#codeEditor').scrollTop});
$('#runCode').onclick=()=>{try{programSong=parseProgram($('#codeEditor').value);panelReady('code');panelReady('song');$('#codeStatus').textContent='RUN OK / SONG UPDATED';$('#codeStatus').className='codeStatus good';renderSong();renderSpectrum();recordFlow('code','song','RUN');setState('CODE → SONG','good');updateMake()}catch(e){$('#codeStatus').textContent=e.message;$('#codeStatus').className='codeStatus bad';setState('CODE ERROR','bad');if(e.line)selectCodeLine(e.line)}};
function selectCodeLine(line){const ta=$('#codeEditor'),ls=ta.value.split('\n');let a=0;for(let i=0;i<line-1;i++)a+=ls[i].length+1;ta.focus();ta.setSelectionRange(a,a+(ls[line-1]?.length||0));ta.scrollTop=Math.max(0,(line-4)*17.05);$('#codeGutter').scrollTop=ta.scrollTop;activePanel='code'}

function allEvents(){if(!programSong)return[];const arr=[];programSong.sections.forEach((sec,si)=>sec.tracks.forEach((t,ti)=>t.notes.forEach((n,ni)=>arr.push({...n,section:sec.name,sectionIndex:si,track:t.name,program:t.program,globalBeat:si*16+n.offset,eventKey:`${si}:${ti}:${ni}`}))));return arr}
function renderSong(highlightLine=0){const c=songViz,w=c.width,h=c.height;sv.clearRect(0,0,w,h);sv.fillStyle='#fffef3';sv.fillRect(0,0,w,h);if(!programSong){$('#songTitle').textContent='NO SONG';return}const ev=allEvents();$('#songTitle').textContent=programSong.title;$('#songMeta').textContent=`${programSong.tempo} BPM · ${programSong.meter}`;const min=ev.length?Math.min(...ev.map(e=>noteMidi(e.pitch))):48,max=ev.length?Math.max(...ev.map(e=>noteMidi(e.pitch))):72;for(let b=0;b<=48;b+=4){const x=b/48*w;sv.strokeStyle=b%16===0?'#0b0c0b':'#ddd9ca';sv.lineWidth=b%16===0?2:1;sv.beginPath();sv.moveTo(x,0);sv.lineTo(x,h);sv.stroke()}for(const e of ev){const x=e.globalBeat/48*w,y=h-((noteMidi(e.pitch)-min+1)/(max-min+2))*h,ww=Math.max(4,e.duration/48*w),hh=5;sv.fillStyle=e.sourceLine===highlightLine?'#eaff52':e.section==='B'?'#ff4d25':'#0b0c0b';sv.fillRect(x,y,ww,hh);e._hit={x,y,w:ww,h:hh}}
  const px=currentBeat/48*w;sv.strokeStyle='#0d7c5b';sv.lineWidth=2;sv.beginPath();sv.moveTo(px,0);sv.lineTo(px,h);sv.stroke();$$('.sections button').forEach(b=>b.classList.toggle('on',currentBeat>=({A1:0,B:16,A2:32}[b.dataset.section])&&currentBeat<({A1:16,B:32,A2:48}[b.dataset.section])))}
songViz.addEventListener('click',e=>{if(!programSong)return;const r=songViz.getBoundingClientRect(),x=(e.clientX-r.left)*songViz.width/r.width,y=(e.clientY-r.top)*songViz.height/r.height;let best=null,bd=1e9;for(const ev of allEvents()){const hx=ev.globalBeat/48*songViz.width;const d=Math.abs(hx-x)+Math.abs((ev._hit?.y||0)-y)*.2;if(d<bd){bd=d;best=ev}}if(best?.sourceLine){selectCodeLine(best.sourceLine);renderSong(best.sourceLine);openChat('code',`NOTE ${best.pitch} / ${best.section} / ${best.track}`)}});
$('#codeEditor').addEventListener('keyup',()=>{const ta=$('#codeEditor'),line=ta.value.slice(0,ta.selectionStart).split('\n').length;renderSong(line)});$('#codeEditor').addEventListener('click',()=>{const ta=$('#codeEditor'),line=ta.value.slice(0,ta.selectionStart).split('\n').length;renderSong(line)});
function renderSpectrum(){const w=spectrumBase.width,h=spectrumBase.height;spb.clearRect(0,0,w,h);spb.fillStyle='#fffef3';spb.fillRect(0,0,w,h);const ev=allEvents();if(!ev.length)return;for(const e of ev){const x=e.globalBeat/48*w,m=noteMidi(e.pitch),y=h-(m-24)/84*h;for(let k=0;k<5;k++){const yy=y+k*5,alpha=Math.max(.04,.22-k*.035)*(e.velocity/127);spb.fillStyle=`rgba(11,12,11,${alpha})`;spb.fillRect(x,Math.max(0,yy),Math.max(2,e.duration/48*w),3)}}for(let s=1;s<3;s++){const x=s/3*w;spb.strokeStyle='#ffb09c';spb.beginPath();spb.moveTo(x,0);spb.lineTo(x,h);spb.stroke()}}

function hz(p){return 440*Math.pow(2,(noteMidi(p)-69)/12)}
function voiceType(program){if(program<8)return'triangle';if(program<32)return'sine';if(program<48)return'sawtooth';if(program<80)return'square';return'triangle'}
function stopAudio(){scheduled.forEach(n=>{try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}});scheduled=[];cancelAnimationFrame(raf);playing=false;$('#playUse').setAttribute('href','#i-play')}
function scheduleFrom(beat=0){if(!programSong)return;stopAudio();audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const secPerBeat=60/programSong.tempo,base=audioCtx.currentTime+.05;for(const e of allEvents()){if(e.globalBeat<beat)continue;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=voiceType(e.program);o.frequency.value=hz(e.pitch);const t=base+(e.globalBeat-beat)*secPerBeat,d=Math.max(.04,e.duration*secPerBeat);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.004,(e.velocity/127)*.13),t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+d+.03);scheduled.push(o,g)}playing=true;playStartBeat=beat;playStartTime=performance.now();$('#playUse').setAttribute('href','#i-pause');tickPlayback()}
function tickPlayback(){if(!playing||!programSong)return;const elapsed=(performance.now()-playStartTime)/1000,current=playStartBeat+elapsed/(60/programSong.tempo);currentBeat=Math.min(48,current);$('#scrub').value=currentBeat;$('#transportTime').textContent=formatTime(currentBeat*60/programSong.tempo);renderSong();if(currentBeat>=48){stopAudio();currentBeat=0;$('#scrub').value=0;renderSong();return}raf=requestAnimationFrame(tickPlayback)}
function formatTime(s){return`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`}
$('#playBtn').onclick=()=>{if(!programSong)return;if(playing)stopAudio();else scheduleFrom(currentBeat)};$('#stopBtn').onclick=()=>{stopAudio();currentBeat=0;$('#scrub').value=0;renderSong()};$('#scrub').oninput=e=>{currentBeat=Number(e.target.value);if(playing)scheduleFrom(currentBeat);else renderSong()};$$('.sections button').forEach(b=>b.onclick=()=>{currentBeat={A1:0,B:16,A2:32}[b.dataset.section];$('#scrub').value=currentBeat;if(playing)scheduleFrom(currentBeat);renderSong()});
