'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],API_PROXY='https://lcxykqgddnekrimawpie.supabase.co/functions/v1/openai-proxy',SUPABASE_PUBLISHABLE='sb_publishable_bF2QF1eJmzhi4Pj-dxE-0g_mnm6zRSh';
let apiKey='',verified=false,audioCtx=null,creatures=[],currentId='',grooveSlots=[],grooveIdeas=[],mode='forage',nodes=[],playing=false,playStarted=0,playOffset=0,raf=0,mark={a:0,b:0},waveDrawing=false,specDrawing=false,lastPt=null,trace=[],chat=[];
const wave=$('#wave'),waveInk=$('#waveInk'),spec=$('#spec'),specInk=$('#specInk'),wx=wave.getContext('2d'),wix=waveInk.getContext('2d'),sx=spec.getContext('2d'),six=specInk.getContext('2d');
function syncViewport(){document.documentElement.style.setProperty('--app-h',Math.round(window.visualViewport?.height||innerHeight)+'px')}syncViewport();window.visualViewport?.addEventListener('resize',syncViewport);window.addEventListener('orientationchange',()=>setTimeout(syncViewport,100));
function setState(t,k=''){$('#state').textContent=t;$('#stateDot').className='dot '+k}function uid(){return crypto.randomUUID?.()||('c'+Date.now()+Math.random().toString(16).slice(2))}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}function current(){return creatures.find(c=>c.id===currentId)||null}function addTrace(from,to,op,data={}){trace.push({time:new Date().toISOString(),from,to,op,data});if(trace.length>500)trace.shift()}
async function api(path,body=null){const r=await fetch(API_PROXY,{method:'POST',headers:{Authorization:`Bearer ${SUPABASE_PUBLISHABLE}`,apikey:SUPABASE_PUBLISHABLE,'Content-Type':'application/json','x-openai-key':apiKey},body:JSON.stringify({path,method:body?'POST':'GET',body})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error?.message||d?.error||d?.message||`${r.status}`);return d}function responseText(d){if(d.output_text)return d.output_text;for(const o of d.output||[])for(const c of o.content||[])if(typeof c.text==='string')return c.text;throw new Error('No response')}async function structured(prompt,name,schema,images=[]){const content=[{type:'input_text',text:prompt},...images.flatMap(x=>[{type:'input_text',text:x.label},{type:'input_image',image_url:x.url,detail:'high'}])],d=await api('/responses',{model:$('#model').value,input:[{role:'user',content}],text:{format:{type:'json_schema',name,schema,strict:true}}});return JSON.parse(responseText(d))}
$('#check').onclick=async()=>{apiKey=$('#key').value.trim();if(!apiKey)return $('#gateState').textContent='ENTER KEY';$('#gateState').textContent='CHECKING';try{await api('/models');verified=true;$('#gate').classList.add('hidden');setState('READY','good')}catch(e){$('#gateState').textContent=e.message}};
function ensureAudio(){audioCtx=audioCtx||new(AudioContext||webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}function analyze(buf){if(!buf)return{};const d=buf.getChannelData(0),step=Math.max(1,Math.floor(d.length/22000));let sum=0,z=0,prev=0,active=0,hf=0,n=0;for(let i=0;i<d.length;i+=step){const v=d[i];sum+=v*v;if(Math.abs(v)>.03)active++;if(i&&Math.sign(v)!==Math.sign(prev))z++;hf+=Math.abs(v-prev);prev=v;n++}return{duration:+buf.duration.toFixed(3),rms:+Math.sqrt(sum/n).toFixed(4),zcr:+(z/n).toFixed(4),brightness:+(hf/n).toFixed(4),density:+(active/n).toFixed(4)}}function makeCreature(name,buffer,parents,recipe,why,kind='creature'){return{id:uid(),name,buffer,parents:[...parents],recipe,why,kind,features:analyze(buffer),created:Date.now(),listener:null}}
async function loadFiles(files){const list=[...files].filter(f=>f.type.startsWith('audio/'));if(!list.length)return;const c=ensureAudio();for(const f of list){try{const buf=await c.decodeAudioData((await f.arrayBuffer()).slice(0)),cr=makeCreature(f.name.replace(/\.[^.]+$/,''),buf,[],{kind:'sample',source:f.name},'uploaded sample','sample');creatures.push(cr);currentId=cr.id;addTrace('external',cr.id,'UPLOAD',{name:f.name})}catch(e){setState('COULD NOT READ '+f.name,'bad')}}renderAll()}$('#uploadBtn').onclick=()=>$('#file').click();$('#file').onchange=e=>loadFiles(e.target.files);document.addEventListener('dragover',e=>{e.preventDefault();setState('DROP TO ADD SOUND','busy')});document.addEventListener('drop',e=>{e.preventDefault();loadFiles(e.dataTransfer.files)});
async function syntheticSeed(){const c=ensureAudio(),sr=44100,dur=4,b=c.createBuffer(1,sr*dur,sr),a=b.getChannelData(0),base=45+Math.random()*75,pulse=2+Math.floor(Math.random()*7);for(let i=0;i<a.length;i++){const t=i/sr,g=Math.sin(t*Math.PI*2*pulse)>.15?1:.1;a[i]=(Math.sin(t*base*Math.PI*2)+.35*Math.sin(t*base*1.49*Math.PI*2))*.18*g+(Math.random()*2-1)*.015}const cr=makeCreature('synthetic seed',b,[],{kind:'synthetic',base,pulse},'local seed','seed');creatures.push(cr);currentId=cr.id;addTrace('local',cr.id,'SEED',{base,pulse});renderAll()}
function drawWave(cr){const w=wave.width,h=wave.height;wx.fillStyle='#fffdf0';wx.fillRect(0,0,w,h);wix.clearRect(0,0,w,h);if(!cr)return;const d=cr.buffer.getChannelData(0),mid=h/2;wx.strokeStyle='#10110f';wx.lineWidth=2;wx.beginPath();for(let x=0;x<w;x++){const a=Math.floor(x/w*d.length),b=Math.min(d.length,Math.floor((x+1)/w*d.length));let mn=1,mx=-1;for(let i=a;i<b;i++){mn=Math.min(mn,d[i]);mx=Math.max(mx,d[i])}wx.moveTo(x,mid+mn*mid*.85);wx.lineTo(x,mid+mx*mid*.85)}wx.stroke();if(mark.b>mark.a){wx.fillStyle='rgba(231,255,78,.45)';wx.fillRect(mark.a*w,0,(mark.b-mark.a)*w,h);wx.strokeStyle='#10110f';wx.strokeRect(mark.a*w,0,(mark.b-mark.a)*w,h)}}
function drawSpec(cr){const w=spec.width,h=spec.height;sx.fillStyle='#fffdf0';sx.fillRect(0,0,w,h);six.clearRect(0,0,w,h);if(!cr)return;const d=cr.buffer.getChannelData(0),cols=150,bins=44,win=80;for(let cx=0;cx<cols;cx++){const center=Math.floor(cx/(cols-1)*Math.max(1,d.length-win-1));for(let k=1;k<bins;k++){let re=0,im=0,f=k/bins*Math.PI;for(let j=0;j<win;j++){const v=d[center+j]||0,p=f*j;re+=v*Math.cos(p);im-=v*Math.sin(p)}const mag=Math.min(1,Math.sqrt(re*re+im*im)/8),yy=h-k/bins*h,xx=cx/cols*w;sx.fillStyle=`rgba(16,17,15,${Math.max(.02,mag*.7)})`;sx.fillRect(xx,yy,w/cols+1,h/bins+1)}}}function specURL(){const c=document.createElement('canvas');c.width=spec.width;c.height=spec.height;const x=c.getContext('2d');x.drawImage(spec,0,0);x.drawImage(specInk,0,0);return c.toDataURL('image/png')}
