'use strict';
function pipelinePrompt(revise=false){const prev=revise?JSON.stringify(pipeline):'(none)';const change=$('#changeInput').value.trim();return `You are a four-agent music instrument. Do not explain. Populate the JSON schema only.\n\nAGENT 1 section_decomposer: translate the current words and visual evidence into exactly A1, B, A2, four bars each.\nAGENT 2 loop_creator: design one strong repeatable 4-bar grammar for each section. B must transform the logic; A2 must be a changed return.\nAGENT 3 midi_data_generator: turn those loop grammars into playable note-event JSON with offsets in quarter-note units inside each 4-bar section (0 <= offset < 16). Use 2-5 tracks per section, practical pitches, clear motifs, percussion represented with pitched MIDI notes if necessary.\nAGENT 4 midi_assembler: assemble the final song specification and synthesis-effect intentions. Preserve causal evidence from words/drawings rather than decorating after the fact.\n\nCURRENT WORDS:\n${$('#wordInput').value.trim()||'(none)'}\n\nCURRENT CHANGE REQUEST:\n${change||'(none)'}\n\nPREVIOUS PIPELINE FOR REVISION:\n${prev}\n\nIf a sketch is supplied, read repetition as rhythm, vertical placement as register, density as note density, stroke direction as motion, negative space as rest, and contrast as section contrast. If a marked spectrum is supplied, treat marks as desired changes to temporal/frequency energy. Produce a coherent, playable 12-bar song, not generic prose.`}
async function makeOrLoop(){if(!verified){$('#gate').classList.remove('hidden');return}if(!song&&!($('#wordInput').value.trim()||hasSketchInk()))return;stop();busy(true,song?'RE-LOOPING':'MAKING');try{const images=[];if(hasSketchInk())images.push({label:'CURRENT SKETCH',url:canvasDataURL(sketch)});if(song&&dirty.spectrum)images.push({label:'CURRENT SPECTRUM WITH USER MARKS',url:canvasDataURL(specInk,specBase)});const c=contentForImages(pipelinePrompt(!!song),images);pipeline=await structured(c,'word_sketch_song_pipeline',PIPELINE_SCHEMA);song=pipeline.agent4;renderSong();if(!$('#wordInput').value.trim()){$('#wordInput').value=pipeline.agent1.source_reading;fitWord()}resetDirty();setState('READY','good');$('#makeLabel').textContent='LOOP';if(innerWidth<=760)goColumn(1)}catch(e){setState(e.message,'bad')}finally{busy(false);updateMakeState()}}
$('#makeBtn').onclick=makeOrLoop;

function resetDirty(){for(const k of Object.keys(dirty))markDirty(k,false);$('#changeInput').value=''}
function clearAll(){stop();pipeline=null;song=null;currentBeat=0;$('#wordInput').value='';fitWord();sk.clearRect(0,0,sketch.width,sketch.height);si.clearRect(0,0,specInk.width,specInk.height);sb.clearRect(0,0,specBase.width,specBase.height);sv.clearRect(0,0,songViz.width,songViz.height);$('#songTitle').textContent='NO SONG';$('#songStats').textContent='A1 / B / A2';$('#transportName').textContent='NO SONG';$('#timeText').textContent='0:00';$('#scrub').value=0;$('#specEmpty').classList.remove('hidden');$('#midiBtn').classList.add('hidden');$('#jsonDownload').classList.add('hidden');codePage=0;refreshCode();resetDirty();setState(verified?'READY':'NO KEY',verified?'good':'');updateMakeState();if(innerWidth<=760)goColumn(0)}
$('#newBtn').onclick=clearAll;

function point(canvas,e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*canvas.width,y:(e.clientY-r.top)/r.height*canvas.height}}
function startDraw(kind,e){e.preventDefault();const canvas=kind==='sketch'?sketch:specInk;lastPoint=point(canvas,e);if(kind==='sketch')drawingSketch=true;else drawingSpec=true;canvas.setPointerCapture?.(e.pointerId)}
function moveDraw(kind,e){const active=kind==='sketch'?drawingSketch:drawingSpec;if(!active)return;e.preventDefault();const canvas=kind==='sketch'?sketch:specInk,ctx=kind==='sketch'?sk:si,p=point(canvas,e);ctx.strokeStyle=kind==='sketch'?'#0b0c0b':'#ff4e26';ctx.lineWidth=kind==='sketch'?7:8;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(lastPoint.x,lastPoint.y);ctx.lineTo(p.x,p.y);ctx.stroke();lastPoint=p;markDirty(kind==='sketch'?'sketch':'spectrum',true)}
function endDraw(kind){if(kind==='sketch')drawingSketch=false;else drawingSpec=false;lastPoint=null;updateMakeState()}
for(const [canvas,kind] of [[sketch,'sketch'],[specInk,'spectrum']]){canvas.addEventListener('pointerdown',e=>startDraw(kind,e));canvas.addEventListener('pointermove',e=>moveDraw(kind,e));canvas.addEventListener('pointerup',()=>endDraw(kind));canvas.addEventListener('pointercancel',()=>endDraw(kind))}
$('#clearSketch').onclick=()=>{sk.clearRect(0,0,1024,1024);markDirty('sketch',true);updateMakeState()};$('#clearSpec').onclick=()=>{si.clearRect(0,0,1024,512);markDirty('spectrum',false)};
$('#uploadBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;await loadSketchImage(URL.createObjectURL(f));markDirty('sketch',true);e.target.value=''};
async function loadSketchImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{sk.clearRect(0,0,1024,1024);sk.fillStyle='#fff';sk.fillRect(0,0,1024,1024);const s=Math.min(1024/im.width,1024/im.height),w=im.width*s,h=im.height*s;sk.drawImage(im,(1024-w)/2,(1024-h)/2,w,h);resolve()};im.onerror=reject;im.crossOrigin='anonymous';im.src=src})}
$('#specToSketch').onclick=()=>{if(!song)return;const c=document.createElement('canvas');c.width=1024;c.height=1024;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,1024,1024);x.drawImage(specBase,0,256,1024,512);x.drawImage(specInk,0,256,1024,512);sk.clearRect(0,0,1024,1024);sk.drawImage(c,0,0);markDirty('sketch',true);if(innerWidth<=760)goColumn(0);setState('SPECTRUM RETURNED TO SKETCH','good')};

$('#wordInput').addEventListener('input',()=>{fitWord();markDirty('word',true)});$('#changeInput').addEventListener('input',()=>markDirty('change',!!$('#changeInput').value.trim()));$('#clearChange').onclick=()=>{$('#changeInput').value='';markDirty('change',false)};

function flattenEvents(s=song){if(!s)return[];const all=[];(s.sections||[]).forEach((sec,si)=>{(sec.tracks||[]).forEach((t,ti)=>{(t.notes||[]).forEach(n=>all.push({...n,offset:n.offset+si*16,section:si,track:t.name,program:t.midi_program,trackIndex:ti}))})});return all.sort((a,b)=>a.offset-b.offset)}
function pitchMidi(p){const m=/^([A-G])([#b]?)([0-8])$/.exec(p);if(!m)return 60;const base={C:0,D:2,E:4,F:5,G:7,A:9,B:11}[m[1]]+(m[2]==='#'?1:m[2]==='b'?-1:0);return (Number(m[3])+1)*12+base}
function pitchHz(p){return 440*Math.pow(2,(pitchMidi(p)-69)/12)}
function timbre(ev){const name=(ev.track||'').toLowerCase(),p=ev.program||0;if(name.includes('bass')||p>=32&&p<40)return{type:'square',gain:.075};if(name.includes('perc')||name.includes('drum'))return{type:'triangle',gain:.045};if(name.includes('pad')||name.includes('harm'))return{type:'sine',gain:.04};if(name.includes('lead')||name.includes('mel'))return{type:'square',gain:.04};return{type:'triangle',gain:.045}}
function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function stopNodes(){for(const n of scheduled){try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}}scheduled=[]}
function scheduleTone(ctx,ev,when,dur){const tm=timbre(ev),o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type=tm.type;o.frequency.setValueAtTime(pitchHz(ev.pitch),when);f.type='lowpass';f.frequency.value=650+(song?.effects?.cutoff??.5)*6200;g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(Math.max(.003,tm.gain*ev.velocity/90),when+.008);g.gain.exponentialRampToValueAtTime(.0001,when+Math.max(.04,dur));o.connect(f);f.connect(g);g.connect(ctx.destination);o.start(when);o.stop(when+dur+.03);scheduled.push(o,g,f)}
function play(){if(!song)return;const ctx=ensureAudio();stopNodes();const spb=60/song.tempo_bpm,base=ctx.currentTime+.055;for(const ev of flattenEvents()){if(ev.offset+ev.duration<=currentBeat)continue;const start=Math.max(ev.offset,currentBeat),delta=(start-currentBeat)*spb,dur=Math.max(.04,(ev.duration-(start-ev.offset))*spb);scheduleTone(ctx,ev,base+delta,dur)}playing=true;playStartBeat=currentBeat;playStartTime=performance.now()+55;iconUse($('#playUse'),'#i-pause');tick()}
function pause(){if(!playing)return;currentBeat=Math.min(48,playStartBeat+(performance.now()-playStartTime)/1000/(60/song.tempo_bpm));playing=false;stopNodes();cancelAnimationFrame(raf);iconUse($('#playUse'),'#i-play');updateTransport()}
function stop(){playing=false;stopNodes();cancelAnimationFrame(raf);iconUse($('#playUse'),'#i-play')}
function playPause(){if(!song)return;if(playing)pause();else{if(currentBeat>=48)currentBeat=0;play()}}
function tick(){if(!playing)return;currentBeat=playStartBeat+(performance.now()-playStartTime)/1000/(60/song.tempo_bpm);if(currentBeat>=48){currentBeat=0;stop();updateTransport();return}updateTransport();raf=requestAnimationFrame(tick)}
function updateTransport(){const b=Math.max(0,Math.min(48,currentBeat));$('#scrub').value=b;const seconds=song?b*60/song.tempo_bpm:0;$('#timeText').textContent=`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;const sec=Math.min(2,Math.floor(b/16));$('#transportSec').textContent=['A1','B','A2'][sec];$$('.sectionStrip div').forEach((d,i)=>d.classList.toggle('active',!!song&&i===sec));drawSongViz()}
$('#playBtn').onclick=playPause;$('#scrub').oninput=e=>{const was=playing;if(was)pause();currentBeat=Number(e.target.value);updateTransport();if(was)play()};

function drawSongViz(){const w=1024,h=420;sv.clearRect(0,0,w,h);sv.fillStyle='#fffdf4';sv.fillRect(0,0,w,h);sv.strokeStyle='rgba(0,0,0,.11)';sv.lineWidth=1;for(let i=0;i<=12;i++){const x=i/12*w;sv.beginPath();sv.moveTo(x,0);sv.lineTo(x,h);sv.stroke()}for(let i=0;i<=8;i++){const y=i/8*h;sv.beginPath();sv.moveTo(0,y);sv.lineTo(w,y);sv.stroke()}if(!song)return;for(const ev of flattenEvents()){const m=pitchMidi(ev.pitch),x=ev.offset/48*w,ww=Math.max(2,ev.duration/48*w),y=h-28-(m-36)/(96-36)*(h-62);sv.fillStyle=ev.section===1?'#ff4e26':'#0b0c0b';sv.fillRect(x,y,ww,5)}const x=currentBeat/48*w;sv.fillStyle='#0b7d52';sv.fillRect(x,0,2,h)}

async function offlineBuffer(){const sr=12000,spb=60/song.tempo_bpm,dur=48*spb+.3,ac=new OfflineAudioContext(1,Math.ceil(sr*dur),sr),master=ac.createGain();master.gain.value=.65;master.connect(ac.destination);for(const ev of flattenEvents()){const tm=timbre(ev),o=ac.createOscillator(),g=ac.createGain(),f=ac.createBiquadFilter(),t=ev.offset*spb,d=Math.max(.04,ev.duration*spb);o.type=tm.type;o.frequency.value=pitchHz(ev.pitch);f.type='lowpass';f.frequency.value=650+(song.effects?.cutoff??.5)*6200;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.003,tm.gain*ev.velocity/90),t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(f);f.connect(g);g.connect(master);o.start(t);o.stop(t+d+.02)}return ac.startRendering()}
function fft(re,im){const n=re.length;for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[re[i],re[j]]=[re[j],re[i]];[im[i],im[j]]=[im[j],im[i]]}}for(let len=2;len<=n;len<<=1){const a=-2*Math.PI/len,lr=Math.cos(a),li=Math.sin(a);for(let i=0;i<n;i+=len){let wr=1,wi=0;for(let j=0;j<len/2;j++){const ur=re[i+j],ui=im[i+j],vr=re[i+j+len/2]*wr-im[i+j+len/2]*wi,vi=re[i+j+len/2]*wi+im[i+j+len/2]*wr;re[i+j]=ur+vr;im[i+j]=ui+vi;re[i+j+len/2]=ur-vr;im[i+j+len/2]=ui-vi;const nw=wr*lr-wi*li;wi=wr*li+wi*lr;wr=nw}}}}
async function renderSpectrum(){si.clearRect(0,0,1024,512);sb.clearRect(0,0,1024,512);sb.fillStyle='#fffdf4';sb.fillRect(0,0,1024,512);if(!song){$('#specEmpty').classList.remove('hidden');return}$('#specEmpty').classList.add('hidden');try{const buffer=await offlineBuffer(),data=buffer.getChannelData(0),N=512,bins=256,cols=320,hop=Math.max(1,Math.floor((data.length-N)/cols));for(let x=0;x<cols;x++){const re=new Float64Array(N),im=new Float64Array(N),start=x*hop;for(let i=0;i<N;i++)re[i]=(data[start+i]||0)*(.5-.5*Math.cos(2*Math.PI*i/(N-1)));fft(re,im);for(let k=2;k<bins;k++){const mag=Math.sqrt(re[k]*re[k]+im[k]*im[k]),v=Math.min(1,Math.log10(1+mag)*.72);if(v<.055)continue;sb.fillStyle=`rgba(11,12,11,${.05+v*.72})`;sb.fillRect(x/cols*1024,512-k/bins*512,Math.ceil(1024/cols)+1,3)}}for(const x of [1024/3,2048/3]){sb.strokeStyle='rgba(255,78,38,.7)';sb.beginPath();sb.moveTo(x,0);sb.lineTo(x,512);sb.stroke()}}catch{for(const ev of flattenEvents()){const x=ev.offset/48*1024,w=Math.max(2,ev.duration/48*1024),m=pitchMidi(ev.pitch),y=512-(m-36)/(96-36)*512;sb.fillStyle='rgba(11,12,11,.55)';sb.fillRect(x,y,w,4)}}}
