'use strict';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const API='https://api.openai.com/v1';
let apiKey='', verified=false, pipeline=null, song=null, codeMode='py', codePage=0, playing=false, currentBeat=0, playStartBeat=0, playStartTime=0, audioCtx=null, scheduled=[], raf=0;
let dirty={word:false,sketch:false,spectrum:false,change:false};
const sketch=$('#sketch'), sk=sketch.getContext('2d'), specBase=$('#specBase'), sb=specBase.getContext('2d'), specInk=$('#specInk'), si=specInk.getContext('2d'), songViz=$('#songViz'), sv=songViz.getContext('2d');
let drawingSketch=false,drawingSpec=false,lastPoint=null;

const EFFECT_KEYS=['delay','reverb','resonance','cutoff','distortion','noise','knock','mallet','ring_modulation','ring_mod_pitch','tremolo_rate','decay','tremolo','sustain','release','attack'];
const NOTE_SCHEMA={type:'object',additionalProperties:false,required:['pitch','offset','duration','velocity'],properties:{pitch:{type:'string',pattern:'^[A-G][#b]?[0-8]$'},offset:{type:'number',minimum:0,maximum:15.99},duration:{type:'number',exclusiveMinimum:0,maximum:8},velocity:{type:'integer',minimum:1,maximum:127}}};
const TRACK_SCHEMA={type:'object',additionalProperties:false,required:['name','midi_program','notes'],properties:{name:{type:'string'},midi_program:{type:'integer',minimum:0,maximum:127},notes:{type:'array',minItems:1,maxItems:64,items:NOTE_SCHEMA}}};
const SEC_TRACK_SCHEMA={type:'object',additionalProperties:false,required:['name','tracks'],properties:{name:{type:'string',enum:['A1','B','A2']},tracks:{type:'array',minItems:2,maxItems:5,items:TRACK_SCHEMA}}};
const PIPELINE_SCHEMA={type:'object',additionalProperties:false,required:['agent1','agent2','agent3','agent4'],properties:{
agent1:{type:'object',additionalProperties:false,required:['title','source_reading','tempo_bpm','key_center','meter','sections'],properties:{title:{type:'string'},source_reading:{type:'string'},tempo_bpm:{type:'integer',minimum:40,maximum:220},key_center:{type:'string'},meter:{type:'string'},sections:{type:'array',minItems:3,maxItems:3,items:{type:'object',additionalProperties:false,required:['name','bars','function','energy','visual_logic'],properties:{name:{type:'string',enum:['A1','B','A2']},bars:{type:'integer',enum:[4]},function:{type:'string'},energy:{type:'number',minimum:0,maximum:1},visual_logic:{type:'string'}}}}}},
agent2:{type:'object',additionalProperties:false,required:['loops'],properties:{loops:{type:'array',minItems:3,maxItems:3,items:{type:'object',additionalProperties:false,required:['section','pulse','melody','bass','harmony','percussion','variation_rule'],properties:{section:{type:'string',enum:['A1','B','A2']},pulse:{type:'string'},melody:{type:'string'},bass:{type:'string'},harmony:{type:'string'},percussion:{type:'string'},variation_rule:{type:'string'}}}}}},
agent3:{type:'object',additionalProperties:false,required:['sections'],properties:{sections:{type:'array',minItems:3,maxItems:3,items:SEC_TRACK_SCHEMA}}},
agent4:{type:'object',additionalProperties:false,required:['title','source_reading','tempo_bpm','meter','sections','effects'],properties:{title:{type:'string'},source_reading:{type:'string'},tempo_bpm:{type:'integer',minimum:40,maximum:220},meter:{type:'string'},sections:{type:'array',minItems:3,maxItems:3,items:SEC_TRACK_SCHEMA},effects:{type:'object',additionalProperties:false,required:EFFECT_KEYS,properties:Object.fromEntries(EFFECT_KEYS.map(k=>[k,{type:'number',minimum:0,maximum:1}]))}}}
}};

function iconUse(el,id){el.setAttribute('href',id)}
function setState(text,kind=''){ $('#topStateText').textContent=text; $('#topDot').className='dot '+kind; }
function gateState(text,kind=''){ const g=$('#gateState'); g.innerHTML=`<span class="dot ${kind}"></span>${escapeHtml(text)}`; }
function busy(on,text='WORKING'){ $('#busy').classList.toggle('on',on); if(on)setState(text,'busy'); }
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function markDirty(which,on=true){dirty[which]=on; const p=$('#'+which+'Panel'); if(p)p.classList.toggle('changed',on); updateMakeState()}
function updateMakeState(){const hasSource=$('#wordInput').value.trim()||hasSketchInk(); $('#makeBtn').disabled=!verified||(!song&&!hasSource); $('#makeLabel').textContent=song?'LOOP':'MAKE'}
function hasSketchInk(){try{const d=sk.getImageData(0,0,sketch.width,sketch.height).data;for(let i=3;i<d.length;i+=32)if(d[i]>0)return true}catch{}return false}
function fitWord(){const el=$('#wordInput'); let size=30; el.style.fontSize=size+'px'; while(size>17 && el.scrollHeight>el.clientHeight){size-=1;el.style.fontSize=size+'px'}}

async function apiFetch(path,opts={}){const headers={Authorization:`Bearer ${apiKey}`,...(opts.headers||{})};const r=await fetch(API+path,{...opts,headers});let data=null;try{data=await r.json()}catch{}if(!r.ok){throw new Error(data?.error?.message||data?.message||`${r.status} ${r.statusText}`)}return data}
function responseText(data){if(data.output_text)return data.output_text;for(const item of data.output||[]){for(const c of item.content||[]){if(c.type==='output_text'&&c.text)return c.text;if(typeof c.text==='string')return c.text}}throw new Error('No structured response returned')}
async function verify(){const key=$('#keyInput').value.trim()||apiKey;if(!key){gateState('ENTER KEY','bad');return}apiKey=key;$('#checkKey').disabled=true;gateState('CHECKING','busy');try{const data=await apiFetch('/models');const ids=new Set((data.data||[]).map(x=>x.id));verified=true;syncModelsFromGate();const t=$('#textModel').value, im=$('#imageModel').value;const note=(ids.has(t)&&ids.has(im))?'KEY + MODELS OK':'KEY OK / MODEL ACCESS CHECKS ON USE';gateState(note,'good');setState(note,'good');$('#gate').classList.add('hidden');$('#app').setAttribute('aria-hidden','false');updateMakeState()}catch(e){verified=false;gateState(e.message,'bad');setState('API NOT READY','bad')}finally{$('#checkKey').disabled=false}}
function syncModelsFromGate(){$('#textModel').value=$('#gateTextModel').value;$('#imageModel').value=$('#gateImageModel').value}
function syncModelsToGate(){$('#gateTextModel').value=$('#textModel').value;$('#gateImageModel').value=$('#imageModel').value}
$('#checkKey').onclick=verify;$('#keyInput').addEventListener('keydown',e=>{if(e.key==='Enter')verify()});

async function structured(content,name,schema){const data=await apiFetch('/responses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:$('#textModel').value,input:[{role:'user',content}],text:{format:{type:'json_schema',name,schema,strict:true}}})});return JSON.parse(responseText(data))}
function canvasDataURL(canvas,bgCanvas=null){if(!bgCanvas)return canvas.toDataURL('image/png');const c=document.createElement('canvas');c.width=bgCanvas.width;c.height=bgCanvas.height;const x=c.getContext('2d');x.drawImage(bgCanvas,0,0);x.drawImage(canvas,0,0);return c.toDataURL('image/png')}
function contentForImages(prompt,images=[]){const c=[{type:'input_text',text:prompt}];for(const it of images){c.push({type:'input_text',text:it.label});c.push({type:'input_image',image_url:it.url,detail:'high'})}return c}

async function generateSketch(){const words=$('#wordInput').value.trim();if(!words){setState('ADD WORDS FIRST','bad');return}busy(true,'WORD → SKETCH');try{const data=await apiFetch('/images/generations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:$('#imageModel').value,prompt:'Black graphite and ink thinking-sketch on bright warm paper. No readable text. No musical staff. Convert the following idea into rhythm, repetition, density, vertical register, motion, negative space and contrast. Keep it rough, diagrammatic, drawable, and useful as a musical control surface: '+words,size:'1024x1024',quality:'medium'})});const item=data.data?.[0];if(!item)throw new Error('No image returned');const src=item.b64_json?`data:image/png;base64,${item.b64_json}`:item.url;await loadSketchImage(src);markDirty('sketch',true);setState('SKETCH READY','good')}catch(e){setState(e.message,'bad')}finally{busy(false)}}
async function sketchReading(){if(!hasSketchInk()){setState('DRAW FIRST','bad');return}busy(true,'SKETCH → WORD');try{const schema={type:'object',additionalProperties:false,required:['reading'],properties:{reading:{type:'string'}}};const c=contentForImages('Read this drawing as musical language, not as a picture caption. Infer rhythm from repetition, register from vertical placement, density from mark concentration, motion from stroke direction, contrast from space and shape. Return one short vivid source phrase an adult can understand.',[{label:'SKETCH',url:canvasDataURL(sketch)}]);const r=await structured(c,'sketch_to_word',schema);$('#wordInput').value=r.reading;fitWord();markDirty('word',true);setState('WORD READY','good')}catch(e){setState(e.message,'bad')}finally{busy(false)}}
$('#wordToSketch').onclick=generateSketch;$('#sketchToWord').onclick=sketchReading;
