'use strict';
function songToPython(){if(!song)return'MAKE A SONG TO EXPOSE THE PROGRAM.';const lines=[`from music21 import stream, note, tempo, meter, instrument, midi`,``,`score = stream.Score()`,`score.insert(0, tempo.MetronomeMark(number=${song.tempo_bpm}))`,`score.insert(0, meter.TimeSignature(${JSON.stringify(song.meter)}))`,``,];let idx=0;for(const sec of song.sections){for(const t of sec.tracks){const v=`p${idx++}`;lines.push(`${v} = stream.Part()`,`${v}.insert(0, instrument.instrumentFromMidiProgram(${t.midi_program}))`);for(const n of t.notes){const off=(song.sections.indexOf(sec)*16+n.offset).toFixed(3).replace(/\.000$/,'');lines.push(`${v}.insert(${off}, note.Note(${JSON.stringify(n.pitch)}, quarterLength=${n.duration}))`)}lines.push(`score.insert(0, ${v})`,``)}}lines.push(`mf = midi.translate.streamToMidiFile(score)`,`mf.open("word_sketch_song.mid", "wb")`,`mf.write()`,`mf.close()`);return lines.join('\n')}
function codeText(){if(!song)return'MAKE A SONG TO EXPOSE THE PROGRAM.';return codeMode==='py'?songToPython():JSON.stringify(pipeline,null,2)}
function refreshCode(){const lines=codeText().split('\n'),per=innerWidth<=760?22:28,pages=Math.max(1,Math.ceil(lines.length/per));codePage=Math.max(0,Math.min(codePage,pages-1));$('#codeView').textContent=lines.slice(codePage*per,(codePage+1)*per).join('\n');$('#codePage').textContent=`${codePage+1}/${pages}`;$('#codePrev').disabled=codePage===0;$('#codeNext').disabled=codePage>=pages-1}
$('#pyBtn').onclick=()=>{codeMode='py';codePage=0;$('#pyBtn').classList.add('on');$('#jsonBtn').classList.remove('on');refreshCode()};$('#jsonBtn').onclick=()=>{codeMode='json';codePage=0;$('#jsonBtn').classList.add('on');$('#pyBtn').classList.remove('on');refreshCode()};$('#codePrev').onclick=()=>{codePage--;refreshCode()};$('#codeNext').onclick=()=>{codePage++;refreshCode()};$('#copyCode').onclick=async()=>{try{await navigator.clipboard.writeText(codeText());setState('CODE COPIED','good')}catch{setState('COPY BLOCKED','bad')}};

function u32(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]}function u16(n){return[(n>>>8)&255,n&255]}function vlq(n){let b=n&127,out=[b];while(n>>=7){b=(n&127)|128;out.unshift(b)}return out}
function makeMidiBlob(){const ppq=96,events=[],tempoUs=Math.round(60000000/song.tempo_bpm);events.push({t:0,b:[0xff,0x51,0x03,(tempoUs>>16)&255,(tempoUs>>8)&255,tempoUs&255],p:0});const ts=(song.meter||'4/4').split('/').map(Number),dd=Math.log2(ts[1]||4)|0;events.push({t:0,b:[0xff,0x58,0x04,ts[0]||4,dd,24,8],p:0});const channels=new Map();let ch=0;for(const ev of flattenEvents()){const key=ev.track+'|'+ev.program;if(!channels.has(key)){if(ch===9)ch++;channels.set(key,ch++%16)}const c=channels.get(key);events.push({t:0,b:[0xc0|c,ev.program&127],p:1});const on=Math.round(ev.offset*ppq),off=Math.round((ev.offset+ev.duration)*ppq),m=pitchMidi(ev.pitch);events.push({t:on,b:[0x90|c,m,ev.velocity],p:3});events.push({t:off,b:[0x80|c,m,0],p:2})}events.sort((a,b)=>a.t-b.t||a.p-b.p);const track=[];let last=0;for(const e of events){track.push(...vlq(e.t-last),...e.b);last=e.t}track.push(0,0xff,0x2f,0);const head=[0x4d,0x54,0x68,0x64,0,0,0,6,...u16(0),...u16(1),...u16(ppq)],trk=[0x4d,0x54,0x72,0x6b,...u32(track.length),...track];return new Blob([new Uint8Array([...head,...trk])],{type:'audio/midi'})}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
$('#midiBtn').onclick=()=>song&&downloadBlob(makeMidiBlob(),safeName(song.title)+'.mid');$('#jsonDownload').onclick=()=>pipeline&&downloadBlob(new Blob([JSON.stringify(pipeline,null,2)],{type:'application/json'}),safeName(song.title)+'.json');function safeName(s){return String(s||'word-sketch-song').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'song'}

async function renderSong(){currentBeat=0;$('#songTitle').textContent=song.title;$('#songStats').textContent=`${song.tempo_bpm} BPM · ${song.meter}`;$('#transportName').textContent=song.title;$('#midiBtn').classList.remove('hidden');$('#jsonDownload').classList.remove('hidden');codePage=0;refreshCode();drawSongViz();updateTransport();await renderSpectrum()}

$('#settingsBtn').onclick=()=>{$('#settings').classList.toggle('open');$('#settingsBtn').classList.toggle('on')};document.addEventListener('pointerdown',e=>{if(!$('#settings').contains(e.target)&&!$('#settingsBtn').contains(e.target)){$('#settings').classList.remove('open');$('#settingsBtn').classList.remove('on')}});$('#textModel').onchange=syncModelsToGate;$('#imageModel').onchange=syncModelsToGate;$('#recheck').onclick=()=>{syncModelsToGate();$('#gate').classList.remove('hidden');$('#keyInput').value=apiKey;gateState('CHECK AGAIN','')};

function goColumn(i){const col=$(`.column[data-col="${i}"]`);$('#stage').scrollTo({left:col.offsetLeft,behavior:'smooth'});$$('#mobileRail button').forEach((b,j)=>b.classList.toggle('on',i===j))}$$('#mobileRail button').forEach(b=>b.onclick=()=>goColumn(Number(b.dataset.go)));$('#stage').addEventListener('scroll',()=>{if(innerWidth>760)return;const i=Math.round($('#stage').scrollLeft/innerWidth);$$('#mobileRail button').forEach((b,j)=>b.classList.toggle('on',i===j))});

window.addEventListener('resize',()=>{fitWord();refreshCode();drawSongViz()});window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();makeOrLoop()}if(e.code==='Space'&&document.activeElement===document.body){e.preventDefault();playPause()}});
fitWord();drawSongViz();renderSpectrum();refreshCode();updateMakeState();
