'use strict';

const THEORY_TARGETS=['rhythm','pitch','register','velocity','duration','timbre','event density','silence','section contrast'];
const STONE_KEY='sketchsong-stones-v1';
let stones=[];
let buildTimer=null,buildStep=0;

const THEORY_PIPELINE_SCHEMA={type:'object',additionalProperties:false,required:['agent1','agent2','agent3','agent4'],properties:{
agent1:{type:'object',additionalProperties:false,required:['title','source_reading','tempo_bpm','key_center','meter','theory','sections'],properties:{title:{type:'string'},source_reading:{type:'string'},tempo_bpm:{type:'integer',minimum:40,maximum:220},key_center:{type:'string'},meter:{type:'string'},theory:{type:'array',minItems:3,maxItems:4,items:{type:'object',additionalProperties:false,required:['source','evidence','relation','target','effect'],properties:{source:{type:'string'},evidence:{type:'string'},relation:{type:'string'},target:{type:'string'},effect:{type:'string'}}}},sections:{type:'array',minItems:3,maxItems:3,items:{type:'object',additionalProperties:false,required:['name','bars','function','energy','visual_logic'],properties:{name:{type:'string',enum:['A1','B','A2']},bars:{type:'integer',enum:[4]},function:{type:'string'},energy:{type:'number',minimum:0,maximum:1},visual_logic:{type:'string'}}}}}},
agent2:{type:'object',additionalProperties:false,required:['loops'],properties:{loops:{type:'array',minItems:3,maxItems:3,items:{type:'object',additionalProperties:false,required:['section','pulse','melody','bass','harmony','percussion','variation_rule'],properties:{section:{type:'string',enum:['A1','B','A2']},pulse:{type:'string'},melody:{type:'string'},bass:{type:'string'},harmony:{type:'string'},percussion:{type:'string'},variation_rule:{type:'string'}}}}}},
agent3:{type:'object',additionalProperties:false,required:['sections'],properties:{sections:{type:'array',minItems:3,maxItems:3,items:SEC_TRACK_SCHEMA}}},
agent4:{type:'object',additionalProperties:false,required:['title','source_reading','tempo_bpm','meter','sections','effects'],properties:{title:{type:'string'},source_reading:{type:'string'},tempo_bpm:{type:'integer',minimum:40,maximum:220},meter:{type:'string'},sections:{type:'array',minItems:3,maxItems:3,items:SEC_TRACK_SCHEMA},effects:{type:'object',additionalProperties:false,required:EFFECT_KEYS,properties:Object.fromEntries(EFFECT_KEYS.map(k=>[k,{type:'number',minimum:0,maximum:1}]))}}}
}};
function theoryPipelinePrompt(revise=false){const prev=revise?JSON.stringify(pipeline):'(none)',change=$('#changeInput').value.trim();return `You are a four-agent music instrument. Populate the JSON schema only. The learner must be able to inspect and contest how a source became sound.\n\nAGENT 1 — THEORY + SECTIONS\nFirst return 3-4 compact, provisional translation rules. Each rule names source evidence, the relation you infer, the musical target, and the audible effect. Then divide the piece into A1, B, A2, exactly four bars each. Do not claim the mappings are objectively correct.\n\nAGENT 2 — LOOPS\nMake one strong repeatable 4-bar grammar for each section. B changes some rule or pressure. A2 returns with memory of B.\n\nAGENT 3 — MIDI EVENTS\nTurn the loop grammars into playable note-event JSON with offsets in quarter-note units inside each four-bar section (0 <= offset < 16). Use 2-5 tracks, practical pitches, and recognizable motifs.\n\nAGENT 4 — ASSEMBLE\nAssemble the playable 12-bar song and synthesis intentions. Preserve the causal evidence from the source.\n\nCURRENT WORDS:\n${$('#wordInput').value.trim()||'(none)'}\n\nCURRENT CHANGE / REWIRED RULE:\n${change||'(none)'}\n\nPREVIOUS PIPELINE:\n${prev}\n\nFor drawings, consider repetition, height, density, direction, negative space and contrast as possible evidence, but only keep mappings that fit this drawing. For marked spectrums, treat the marks as proposed changes to energy in time/frequency. Produce a coherent song and an inspectable theory.`}
async function theoryMakeOrLoop(){if(!verified){$('#gate').classList.remove('hidden');return}if(!song&&!($('#wordInput').value.trim()||hasSketchInk()))return;stop();const previousSong=song,previousPipeline=pipeline;busy(true,song?'RE-LOOPING':'MAKING');try{const images=[];if(hasSketchInk())images.push({label:'CURRENT SKETCH',url:canvasDataURL(sketch)});if(song&&dirty.spectrum)images.push({label:'CURRENT SPECTRUM WITH USER MARKS',url:canvasDataURL(specInk,specBase)});const promptText=theoryPipelinePrompt(!!song),c=contentForImages(promptText,images);pipeline=await structured(c,'sketchsong_theory_pipeline',THEORY_PIPELINE_SCHEMA);song=pipeline.agent4;await revealBuiltTheory(pipeline);await renderSong();if(!$('#wordInput').value.trim()){$('#wordInput').value=pipeline.agent1.source_reading;fitWord()}if(typeof recordGeneration==='function')recordGeneration(previousSong,previousPipeline,promptText);resetDirty();setState('READY · THEORY VISIBLE','good');$('#makeLabel').textContent='LOOP';modeTheory();if(innerWidth<=900)goColumn(1)}catch(e){setState(e.message,'bad')}finally{busy(false);updateMakeState()}}

function openUtility(which='guide'){$('#utility').classList.add('open');$('#utility').setAttribute('aria-hidden','false');switchUtility(which)}
function closeUtility(){$('#utility').classList.remove('open');$('#utility').setAttribute('aria-hidden','true')}
function switchUtility(which){$$('.utilityTabs button').forEach(b=>b.classList.toggle('on',b.dataset.util===which));$$('.utilityPane').forEach(p=>p.classList.toggle('on',p.dataset.pane===which));if(which==='history')renderHistory();if(which==='stones')renderStones()}
$('#utilityClose').onclick=closeUtility;$('#historyBtn').onclick=()=>openUtility('history');$$('.utilityTabs button').forEach(b=>b.onclick=()=>switchUtility(b.dataset.util));

function modeTheory(){$('#theoryBtn').classList.add('on');$('#pyBtn').classList.remove('on');$('#jsonBtn').classList.remove('on');$('#theoryBody').classList.remove('hidden');$('#codeBody').classList.add('hidden');$('#throughTitle').textContent='THEORY'}
function modeCode(mode){codeMode=mode;codePage=0;$('#theoryBtn').classList.remove('on');$('#pyBtn').classList.toggle('on',mode==='py');$('#jsonBtn').classList.toggle('on',mode==='json');$('#theoryBody').classList.add('hidden');$('#codeBody').classList.remove('hidden');$('#throughTitle').textContent=mode==='py'?'PYTHON':'JSON';refreshCode()}
$('#theoryBtn').onclick=modeTheory;$('#pyBtn').onclick=()=>modeCode('py');$('#jsonBtn').onclick=()=>modeCode('json');

function normalizeTarget(t=''){const q=t.toLowerCase();if(q.includes('rhythm')||q.includes('pulse'))return'rhythm';if(q.includes('register'))return'register';if(q.includes('pitch')||q.includes('contour'))return'pitch';if(q.includes('veloc')||q.includes('loud'))return'velocity';if(q.includes('duration')||q.includes('length'))return'duration';if(q.includes('timbre')||q.includes('instrument'))return'timbre';if(q.includes('dens'))return'event density';if(q.includes('silence')||q.includes('rest')||q.includes('space'))return'silence';if(q.includes('section')||q.includes('contrast'))return'section contrast';return THEORY_TARGETS[0]}
function theoryRules(){return pipeline?.agent1?.theory||[]}
function renderTheory(){const box=$('#theoryView'),empty=$('#theoryEmpty'),rules=theoryRules();if(!box)return;if(!rules.length){box.innerHTML='';empty.classList.remove('hidden');return}empty.classList.add('hidden');box.style.gridTemplateRows=`repeat(${Math.min(4,rules.length)},minmax(0,1fr))`;box.innerHTML=rules.slice(0,4).map((r,i)=>`<div class="theoryRule" data-rule="${i}"><button class="ruleSource ruleFocus" data-rule="${i}" aria-label="Show source evidence"><b>${escapeHtml(r.source||'source')}</b><small>${escapeHtml(r.evidence||'evidence')}</small></button><div class="ruleArrow">→</div><button class="ruleTarget ruleFocus" data-rule="${i}" aria-label="Show audible effect"><b>${escapeHtml(r.target||'sound')}</b><small>${escapeHtml(r.effect||r.relation||'effect')}</small></button><div class="ruleActions"><button class="ruleEdit" data-edit="${i}" aria-label="Change this rule"><svg class="icon"><use href="#i-loop"/></svg></button><button class="ruleKeep" data-keep="${i}" aria-label="Keep this stepping stone"><svg class="icon"><use href="#i-stone"/></svg></button></div></div>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>rewireRule(Number(b.dataset.edit)));$$('[data-keep]').forEach(b=>b.onclick=()=>keepRule(Number(b.dataset.keep)));$$('.ruleFocus').forEach(b=>b.onclick=()=>focusRule(Number(b.dataset.rule)))}
function focusRule(i){$$('.theoryRule').forEach((r,j)=>r.classList.toggle('selected',i===j));const r=theoryRules()[i];if(!r)return;$('#wordPanel').classList.add('linked');$('#sketchPanel').classList.add('linked');$('#songPanel').classList.add('linked');setTimeout(()=>{$('#wordPanel').classList.remove('linked');$('#sketchPanel').classList.remove('linked');$('#songPanel').classList.remove('linked')},650);setState(`${String(r.source).toUpperCase()} → ${String(r.target).toUpperCase()}`,'good')}
function rewireRule(i){const r=theoryRules()[i];if(!r)return;const old=normalizeTarget(r.target),idx=Math.max(0,THEORY_TARGETS.indexOf(old)),next=THEORY_TARGETS[(idx+1)%THEORY_TARGETS.length];r.target=next;r.effect=`next loop: treat ${r.source} as ${next}`;const instruction=`Change the translation theory: use ${r.source} as evidence for ${next} instead of ${old}. Preserve other useful mappings unless they conflict.`;latestCritique=instruction;$('#changeInput').value=instruction.slice(0,500);markDirty('change',true);renderTheory();setState('RULE CHANGED · LOOP TO TEST','good')}
function loadStones(){try{stones=JSON.parse(localStorage.getItem(STONE_KEY)||'[]')}catch{stones=[]}renderStones()}
function persistStones(){try{localStorage.setItem(STONE_KEY,JSON.stringify(stones.slice(-32)))}catch{}}
function keepRule(i){const r=theoryRules()[i];if(!r)return;const stone={id:`s-${Date.now().toString(36)}`,time:Date.now(),source:r.source,target:r.target,evidence:r.evidence,effect:r.effect,title:song?.title||pipeline?.agent1?.title||'new',generation:currentGenerationId};const sig=`${stone.source}|${stone.target}|${stone.evidence}`;stones=stones.filter(s=>`${s.source}|${s.target}|${s.evidence}`!==sig);stones.push(stone);persistStones();renderStones();setState('STEPPING STONE KEPT','good')}
function renderStones(){const box=$('#stonesGrid');if(!box)return;if(!stones.length){box.innerHTML='<div class="historyEmpty">NO STONES</div>';return}box.innerHTML=[...stones].reverse().slice(0,12).map(s=>`<button class="stoneCard" data-stone="${s.id}"><span class="stoneMeta">${new Date(s.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span><span class="stoneRule">${escapeHtml(s.source)} → ${escapeHtml(s.target)}</span><span class="stoneWhy">${escapeHtml(s.evidence||s.effect||'')}</span></button>`).join('');$$('[data-stone]').forEach(b=>b.onclick=()=>useStone(b.dataset.stone))}
function useStone(id){const s=stones.find(x=>x.id===id);if(!s)return;const instruction=`Reuse this stepping stone as a translation rule: ${s.source} → ${s.target}. Evidence that made it interesting before: ${s.evidence||'unknown'}. Adapt it to the current source rather than copying the old song.`;latestCritique=instruction;$('#changeInput').value=instruction.slice(0,500);markDirty('change',true);closeUtility();goColumn(1);setState('STONE LOADED · LOOP TO TRY','good')}
$('#clearStones').onclick=()=>{stones=[];persistStones();renderStones()};

function learningBusy(on,text='WORKING'){clearInterval(buildTimer);buildTimer=null;if(!on)return;const main=/MAKING|RE-LOOPING/.test(text);$('#buildVerb').textContent=text.replaceAll(' → ','→');buildStep=0;updateBuildStage(0,main?sourceEvidence():'KEEP THE CAUSE VISIBLE');if(main){buildTimer=setInterval(()=>{if(buildStep<5){buildStep++;updateBuildStage(buildStep,buildHint(buildStep))}},1250)}else{$$('#buildStages>div').forEach((d,i)=>{d.classList.toggle('active',i===0);d.classList.remove('done')});$('#buildCount').textContent='WORKING'}}
function sourceEvidence(){const w=$('#wordInput').value.trim();if(w)return `READING: ${w.slice(0,92)}`;if(hasSketchInk())return'DRAWING IS THE SOURCE: LOOKING FOR REPETITION, HEIGHT, DENSITY, SPACE';return'LOOKING FOR A SOURCE'}
function buildHint(i){return ['READ THE SOURCE','PROPOSE A RELATION','MAKE A REPEATABLE A1','LET B CHANGE THE RULE','RETURN TO A WITH MEMORY','ASSEMBLE A PLAYABLE WHOLE'][i]}
function updateBuildStage(i,text){$$('#buildStages>div').forEach((d,j)=>{d.classList.toggle('done',j<i);d.classList.toggle('active',j===i)});$('#buildCount').textContent=`${String(i+1).padStart(2,'0')} / 06`;$('#buildEvidence').textContent=text||buildHint(i)}
async function revealBuiltTheory(p){clearInterval(buildTimer);buildTimer=null;const rules=p?.agent1?.theory||[];for(let i=0;i<6;i++){updateBuildStage(i,i===1&&rules[0]?`${rules[0].source} → ${rules[0].target}`:buildHint(i));await new Promise(r=>setTimeout(r,110))}if(rules.length)$('#buildEvidence').textContent=rules.slice(0,2).map(r=>`${r.source} → ${r.target}`).join(' · ');renderTheory();await new Promise(r=>setTimeout(r,260))}
function clearTheorySurface(){const box=$('#theoryView');if(box)box.innerHTML='';$('#theoryEmpty')?.classList.remove('hidden');modeTheory()}

const oldPanelAttachment=panelAttachment;panelAttachment=function(name){if(name==='theory')return{type:'theory',label:'THEORY',text:JSON.stringify(theoryRules())};return oldPanelAttachment(name)};
attachPanel=function(name){const a=panelAttachment(name);if(!a)return;chatAttachments.push(a);if(chatAttachments.length>5)chatAttachments.shift();renderAttachments();openUtility('guide')};
const oldGuideContextPrompt=guideContextPrompt;guideContextPrompt=function(mode,q){const base=oldGuideContextPrompt(mode,q),theory=theoryRules().map(r=>`${r.source}→${r.target}`).join(', ');return `${base}\nCURRENT TRANSLATION THEORY: ${theory||'not built yet'}\nWhen helpful, explain one causal mapping between source and sound. Treat AI interpretations as provisional readings the learner can contest. Prefer SHOW ME / CHANGE IT / LET ME TRY over lecture.`};
$('#wordInput').addEventListener('input',()=>document.querySelector('.startCue')?.classList.toggle('hidden',!!$('#wordInput').value.trim()));
busy=function(on,text='WORKING'){$('#busy').classList.toggle('on',on);if(on)setState(text,'busy');learningBusy(on,text)};
const baseRenderSong=renderSong;renderSong=async function(){renderTheory();return baseRenderSong()};
$('#makeBtn').onclick=theoryMakeOrLoop;
const baseNewHandler=$('#newBtn').onclick;$('#newBtn').onclick=()=>{baseNewHandler?.();clearTheorySurface()};
$('#helpBtn').onclick=()=>{openUtility('guide');attachPanel(currentLikelyPanel());askGuide('what')};
loadStones();renderTheory();modeTheory();
